package cz.cuni.mff.auv.problem;

import cz.cuni.mff.auv.domain.types.T_Location;
import cz.cuni.mff.jpddl.PDDLEnum;

public final class E_Locations {
	
	public static final T_Location l11 = new T_Location("l-1-1");
	public static final T_Location l12 = new T_Location("l-1-2");
	public static final T_Location l13 = new T_Location("l-1-3");
	public static final T_Location l14 = new T_Location("l-1-4");
	public static final T_Location l15 = new T_Location("l-1-5");
	public static final T_Location l16 = new T_Location("l-1-6");
	public static final T_Location l17 = new T_Location("l-1-7");
	public static final T_Location l18 = new T_Location("l-1-8");
	public static final T_Location l21 = new T_Location("l-2-1");
	public static final T_Location l22 = new T_Location("l-2-2");
	public static final T_Location l23 = new T_Location("l-2-3");
	public static final T_Location l24 = new T_Location("l-2-4");
	public static final T_Location l25 = new T_Location("l-2-5");
	public static final T_Location l26 = new T_Location("l-2-6");
	public static final T_Location l27 = new T_Location("l-2-7");
	public static final T_Location l28 = new T_Location("l-2-8");
	public static final T_Location l31 = new T_Location("l-3-1");
	public static final T_Location l32 = new T_Location("l-3-2");
	public static final T_Location l33 = new T_Location("l-3-3");
	public static final T_Location l34 = new T_Location("l-3-4");
	public static final T_Location l35 = new T_Location("l-3-5");
	public static final T_Location l36 = new T_Location("l-3-6");
	public static final T_Location l37 = new T_Location("l-3-7");
	public static final T_Location l38 = new T_Location("l-3-8");
	public static final T_Location l41 = new T_Location("l-4-1");
	public static final T_Location l42 = new T_Location("l-4-2");
	public static final T_Location l43 = new T_Location("l-4-3");
	public static final T_Location l44 = new T_Location("l-4-4");
	public static final T_Location l45 = new T_Location("l-4-5");
	public static final T_Location l46 = new T_Location("l-4-6");
	public static final T_Location l47 = new T_Location("l-4-7");
	public static final T_Location l48 = new T_Location("l-4-8");
	public static final T_Location l51 = new T_Location("l-5-1");
	public static final T_Location l52 = new T_Location("l-5-2");
	public static final T_Location l53 = new T_Location("l-5-3");
	public static final T_Location l54 = new T_Location("l-5-4");
	public static final T_Location l55 = new T_Location("l-5-5");
	public static final T_Location l56 = new T_Location("l-5-6");
	public static final T_Location l57 = new T_Location("l-5-7");
	public static final T_Location l58 = new T_Location("l-5-8");
	public static final T_Location l61 = new T_Location("l-6-1");
	public static final T_Location l62 = new T_Location("l-6-2");
	public static final T_Location l63 = new T_Location("l-6-3");
	public static final T_Location l64 = new T_Location("l-6-4");
	public static final T_Location l65 = new T_Location("l-6-5");
	public static final T_Location l66 = new T_Location("l-6-6");
	public static final T_Location l67 = new T_Location("l-6-7");
	public static final T_Location l68 = new T_Location("l-6-8");
	public static final T_Location l71 = new T_Location("l-7-1");
	public static final T_Location l72 = new T_Location("l-7-2");
	public static final T_Location l73 = new T_Location("l-7-3");
	public static final T_Location l74 = new T_Location("l-7-4");
	public static final T_Location l75 = new T_Location("l-7-5");
	public static final T_Location l76 = new T_Location("l-7-6");
	public static final T_Location l77 = new T_Location("l-7-7");
	public static final T_Location l78 = new T_Location("l-7-8");
	public static final T_Location l81 = new T_Location("l-8-1");
	public static final T_Location l82 = new T_Location("l-8-2");
	public static final T_Location l83 = new T_Location("l-8-3");
	public static final T_Location l84 = new T_Location("l-8-4");
	public static final T_Location l85 = new T_Location("l-8-5");
	public static final T_Location l86 = new T_Location("l-8-6");
	public static final T_Location l87 = new T_Location("l-8-7");
	public static final T_Location l88 = new T_Location("l-8-8");
	
	static {
		E_Location.THIS.register(T_Location.getIndex(l11), l11);
		E_Location.THIS.register(T_Location.getIndex(l12), l12);
		E_Location.THIS.register(T_Location.getIndex(l13), l13);
		E_Location.THIS.register(T_Location.getIndex(l14), l14);
		E_Location.THIS.register(T_Location.getIndex(l15), l15);
		E_Location.THIS.register(T_Location.getIndex(l16), l16);
		E_Location.THIS.register(T_Location.getIndex(l17), l17);
		E_Location.THIS.register(T_Location.getIndex(l18), l18);
		E_Location.THIS.register(T_Location.getIndex(l21), l21);
		E_Location.THIS.register(T_Location.getIndex(l22), l22);
		E_Location.THIS.register(T_Location.getIndex(l23), l23);
		E_Location.THIS.register(T_Location.getIndex(l24), l24);
		E_Location.THIS.register(T_Location.getIndex(l25), l25);
		E_Location.THIS.register(T_Location.getIndex(l26), l26);
		E_Location.THIS.register(T_Location.getIndex(l27), l27);
		E_Location.THIS.register(T_Location.getIndex(l28), l28);
		E_Location.THIS.register(T_Location.getIndex(l31), l31);
		E_Location.THIS.register(T_Location.getIndex(l32), l32);
		E_Location.THIS.register(T_Location.getIndex(l33), l33);
		E_Location.THIS.register(T_Location.getIndex(l34), l34);
		E_Location.THIS.register(T_Location.getIndex(l35), l35);
		E_Location.THIS.register(T_Location.getIndex(l36), l36);
		E_Location.THIS.register(T_Location.getIndex(l37), l37);
		E_Location.THIS.register(T_Location.getIndex(l38), l38);
		E_Location.THIS.register(T_Location.getIndex(l41), l41);
		E_Location.THIS.register(T_Location.getIndex(l42), l42);
		E_Location.THIS.register(T_Location.getIndex(l43), l43);
		E_Location.THIS.register(T_Location.getIndex(l44), l44);
		E_Location.THIS.register(T_Location.getIndex(l45), l45);
		E_Location.THIS.register(T_Location.getIndex(l46), l46);
		E_Location.THIS.register(T_Location.getIndex(l47), l47);
		E_Location.THIS.register(T_Location.getIndex(l48), l48);
		E_Location.THIS.register(T_Location.getIndex(l51), l51);
		E_Location.THIS.register(T_Location.getIndex(l52), l52);
		E_Location.THIS.register(T_Location.getIndex(l53), l53);
		E_Location.THIS.register(T_Location.getIndex(l54), l54);
		E_Location.THIS.register(T_Location.getIndex(l55), l55);
		E_Location.THIS.register(T_Location.getIndex(l56), l56);
		E_Location.THIS.register(T_Location.getIndex(l57), l57);
		E_Location.THIS.register(T_Location.getIndex(l58), l58);
		E_Location.THIS.register(T_Location.getIndex(l61), l61);
		E_Location.THIS.register(T_Location.getIndex(l62), l62);
		E_Location.THIS.register(T_Location.getIndex(l63), l63);
		E_Location.THIS.register(T_Location.getIndex(l64), l64);
		E_Location.THIS.register(T_Location.getIndex(l65), l65);
		E_Location.THIS.register(T_Location.getIndex(l66), l66);
		E_Location.THIS.register(T_Location.getIndex(l67), l67);
		E_Location.THIS.register(T_Location.getIndex(l68), l68);
		E_Location.THIS.register(T_Location.getIndex(l71), l71);
		E_Location.THIS.register(T_Location.getIndex(l72), l72);
		E_Location.THIS.register(T_Location.getIndex(l73), l73);
		E_Location.THIS.register(T_Location.getIndex(l74), l74);
		E_Location.THIS.register(T_Location.getIndex(l75), l75);
		E_Location.THIS.register(T_Location.getIndex(l76), l76);
		E_Location.THIS.register(T_Location.getIndex(l77), l77);
		E_Location.THIS.register(T_Location.getIndex(l78), l78);
		E_Location.THIS.register(T_Location.getIndex(l81), l81);
		E_Location.THIS.register(T_Location.getIndex(l82), l82);
		E_Location.THIS.register(T_Location.getIndex(l83), l83);
		E_Location.THIS.register(T_Location.getIndex(l84), l84);
		E_Location.THIS.register(T_Location.getIndex(l85), l85);
		E_Location.THIS.register(T_Location.getIndex(l86), l86);
		E_Location.THIS.register(T_Location.getIndex(l87), l87);
		E_Location.THIS.register(T_Location.getIndex(l88), l88);
	}
		
	protected E_Locations() {
	}

}
