package cz.cuni.mff.perestroika.perestroika_problem_10_3_0_5_0_5_1;

import cz.cuni.mff.perestroika.domain.types.T_Location;
import cz.cuni.mff.perestroika.problem.E_Location;

public final class E_Locations {

	public static final T_Location l_1_1 = new T_Location("l-1-1");
	public static final T_Location l_1_2 = new T_Location("l-1-2");
	public static final T_Location l_1_3 = new T_Location("l-1-3");
	public static final T_Location l_1_4 = new T_Location("l-1-4");
	public static final T_Location l_1_5 = new T_Location("l-1-5");
	public static final T_Location l_1_6 = new T_Location("l-1-6");
	public static final T_Location l_1_7 = new T_Location("l-1-7");
	public static final T_Location l_1_8 = new T_Location("l-1-8");
	public static final T_Location l_1_9 = new T_Location("l-1-9");
	public static final T_Location l_1_10 = new T_Location("l-1-10");
	public static final T_Location l_2_1 = new T_Location("l-2-1");
	public static final T_Location l_2_2 = new T_Location("l-2-2");
	public static final T_Location l_2_3 = new T_Location("l-2-3");
	public static final T_Location l_2_4 = new T_Location("l-2-4");
	public static final T_Location l_2_5 = new T_Location("l-2-5");
	public static final T_Location l_2_6 = new T_Location("l-2-6");
	public static final T_Location l_2_7 = new T_Location("l-2-7");
	public static final T_Location l_2_8 = new T_Location("l-2-8");
	public static final T_Location l_2_9 = new T_Location("l-2-9");
	public static final T_Location l_2_10 = new T_Location("l-2-10");
	public static final T_Location l_3_1 = new T_Location("l-3-1");
	public static final T_Location l_3_2 = new T_Location("l-3-2");
	public static final T_Location l_3_3 = new T_Location("l-3-3");
	public static final T_Location l_3_4 = new T_Location("l-3-4");
	public static final T_Location l_3_5 = new T_Location("l-3-5");
	public static final T_Location l_3_6 = new T_Location("l-3-6");
	public static final T_Location l_3_7 = new T_Location("l-3-7");
	public static final T_Location l_3_8 = new T_Location("l-3-8");
	public static final T_Location l_3_9 = new T_Location("l-3-9");
	public static final T_Location l_3_10 = new T_Location("l-3-10");
	public static final T_Location l_4_1 = new T_Location("l-4-1");
	public static final T_Location l_4_2 = new T_Location("l-4-2");
	public static final T_Location l_4_3 = new T_Location("l-4-3");
	public static final T_Location l_4_4 = new T_Location("l-4-4");
	public static final T_Location l_4_5 = new T_Location("l-4-5");
	public static final T_Location l_4_6 = new T_Location("l-4-6");
	public static final T_Location l_4_7 = new T_Location("l-4-7");
	public static final T_Location l_4_8 = new T_Location("l-4-8");
	public static final T_Location l_4_9 = new T_Location("l-4-9");
	public static final T_Location l_4_10 = new T_Location("l-4-10");
	public static final T_Location l_5_1 = new T_Location("l-5-1");
	public static final T_Location l_5_2 = new T_Location("l-5-2");
	public static final T_Location l_5_3 = new T_Location("l-5-3");
	public static final T_Location l_5_4 = new T_Location("l-5-4");
	public static final T_Location l_5_5 = new T_Location("l-5-5");
	public static final T_Location l_5_6 = new T_Location("l-5-6");
	public static final T_Location l_5_7 = new T_Location("l-5-7");
	public static final T_Location l_5_8 = new T_Location("l-5-8");
	public static final T_Location l_5_9 = new T_Location("l-5-9");
	public static final T_Location l_5_10 = new T_Location("l-5-10");
	public static final T_Location l_6_1 = new T_Location("l-6-1");
	public static final T_Location l_6_2 = new T_Location("l-6-2");
	public static final T_Location l_6_3 = new T_Location("l-6-3");
	public static final T_Location l_6_4 = new T_Location("l-6-4");
	public static final T_Location l_6_5 = new T_Location("l-6-5");
	public static final T_Location l_6_6 = new T_Location("l-6-6");
	public static final T_Location l_6_7 = new T_Location("l-6-7");
	public static final T_Location l_6_8 = new T_Location("l-6-8");
	public static final T_Location l_6_9 = new T_Location("l-6-9");
	public static final T_Location l_6_10 = new T_Location("l-6-10");
	public static final T_Location l_7_1 = new T_Location("l-7-1");
	public static final T_Location l_7_2 = new T_Location("l-7-2");
	public static final T_Location l_7_3 = new T_Location("l-7-3");
	public static final T_Location l_7_4 = new T_Location("l-7-4");
	public static final T_Location l_7_5 = new T_Location("l-7-5");
	public static final T_Location l_7_6 = new T_Location("l-7-6");
	public static final T_Location l_7_7 = new T_Location("l-7-7");
	public static final T_Location l_7_8 = new T_Location("l-7-8");
	public static final T_Location l_7_9 = new T_Location("l-7-9");
	public static final T_Location l_7_10 = new T_Location("l-7-10");
	public static final T_Location l_8_1 = new T_Location("l-8-1");
	public static final T_Location l_8_2 = new T_Location("l-8-2");
	public static final T_Location l_8_3 = new T_Location("l-8-3");
	public static final T_Location l_8_4 = new T_Location("l-8-4");
	public static final T_Location l_8_5 = new T_Location("l-8-5");
	public static final T_Location l_8_6 = new T_Location("l-8-6");
	public static final T_Location l_8_7 = new T_Location("l-8-7");
	public static final T_Location l_8_8 = new T_Location("l-8-8");
	public static final T_Location l_8_9 = new T_Location("l-8-9");
	public static final T_Location l_8_10 = new T_Location("l-8-10");
	public static final T_Location l_9_1 = new T_Location("l-9-1");
	public static final T_Location l_9_2 = new T_Location("l-9-2");
	public static final T_Location l_9_3 = new T_Location("l-9-3");
	public static final T_Location l_9_4 = new T_Location("l-9-4");
	public static final T_Location l_9_5 = new T_Location("l-9-5");
	public static final T_Location l_9_6 = new T_Location("l-9-6");
	public static final T_Location l_9_7 = new T_Location("l-9-7");
	public static final T_Location l_9_8 = new T_Location("l-9-8");
	public static final T_Location l_9_9 = new T_Location("l-9-9");
	public static final T_Location l_9_10 = new T_Location("l-9-10");
	public static final T_Location l_10_1 = new T_Location("l-10-1");
	public static final T_Location l_10_2 = new T_Location("l-10-2");
	public static final T_Location l_10_3 = new T_Location("l-10-3");
	public static final T_Location l_10_4 = new T_Location("l-10-4");
	public static final T_Location l_10_5 = new T_Location("l-10-5");
	public static final T_Location l_10_6 = new T_Location("l-10-6");
	public static final T_Location l_10_7 = new T_Location("l-10-7");
	public static final T_Location l_10_8 = new T_Location("l-10-8");
	public static final T_Location l_10_9 = new T_Location("l-10-9");
	public static final T_Location l_10_10 = new T_Location("l-10-10");
	

	static {

		E_Location.THIS.register(T_Location.getIndex(l_1_1), l_1_1);
		E_Location.THIS.register(T_Location.getIndex(l_1_2), l_1_2);
		E_Location.THIS.register(T_Location.getIndex(l_1_3), l_1_3);
		E_Location.THIS.register(T_Location.getIndex(l_1_4), l_1_4);
		E_Location.THIS.register(T_Location.getIndex(l_1_5), l_1_5);
		E_Location.THIS.register(T_Location.getIndex(l_1_6), l_1_6);
		E_Location.THIS.register(T_Location.getIndex(l_1_7), l_1_7);
		E_Location.THIS.register(T_Location.getIndex(l_1_8), l_1_8);
		E_Location.THIS.register(T_Location.getIndex(l_1_9), l_1_9);
		E_Location.THIS.register(T_Location.getIndex(l_1_10), l_1_10);
		E_Location.THIS.register(T_Location.getIndex(l_2_1), l_2_1);
		E_Location.THIS.register(T_Location.getIndex(l_2_2), l_2_2);
		E_Location.THIS.register(T_Location.getIndex(l_2_3), l_2_3);
		E_Location.THIS.register(T_Location.getIndex(l_2_4), l_2_4);
		E_Location.THIS.register(T_Location.getIndex(l_2_5), l_2_5);
		E_Location.THIS.register(T_Location.getIndex(l_2_6), l_2_6);
		E_Location.THIS.register(T_Location.getIndex(l_2_7), l_2_7);
		E_Location.THIS.register(T_Location.getIndex(l_2_8), l_2_8);
		E_Location.THIS.register(T_Location.getIndex(l_2_9), l_2_9);
		E_Location.THIS.register(T_Location.getIndex(l_2_10), l_2_10);
		E_Location.THIS.register(T_Location.getIndex(l_3_1), l_3_1);
		E_Location.THIS.register(T_Location.getIndex(l_3_2), l_3_2);
		E_Location.THIS.register(T_Location.getIndex(l_3_3), l_3_3);
		E_Location.THIS.register(T_Location.getIndex(l_3_4), l_3_4);
		E_Location.THIS.register(T_Location.getIndex(l_3_5), l_3_5);
		E_Location.THIS.register(T_Location.getIndex(l_3_6), l_3_6);
		E_Location.THIS.register(T_Location.getIndex(l_3_7), l_3_7);
		E_Location.THIS.register(T_Location.getIndex(l_3_8), l_3_8);
		E_Location.THIS.register(T_Location.getIndex(l_3_9), l_3_9);
		E_Location.THIS.register(T_Location.getIndex(l_3_10), l_3_10);
		E_Location.THIS.register(T_Location.getIndex(l_4_1), l_4_1);
		E_Location.THIS.register(T_Location.getIndex(l_4_2), l_4_2);
		E_Location.THIS.register(T_Location.getIndex(l_4_3), l_4_3);
		E_Location.THIS.register(T_Location.getIndex(l_4_4), l_4_4);
		E_Location.THIS.register(T_Location.getIndex(l_4_5), l_4_5);
		E_Location.THIS.register(T_Location.getIndex(l_4_6), l_4_6);
		E_Location.THIS.register(T_Location.getIndex(l_4_7), l_4_7);
		E_Location.THIS.register(T_Location.getIndex(l_4_8), l_4_8);
		E_Location.THIS.register(T_Location.getIndex(l_4_9), l_4_9);
		E_Location.THIS.register(T_Location.getIndex(l_4_10), l_4_10);
		E_Location.THIS.register(T_Location.getIndex(l_5_1), l_5_1);
		E_Location.THIS.register(T_Location.getIndex(l_5_2), l_5_2);
		E_Location.THIS.register(T_Location.getIndex(l_5_3), l_5_3);
		E_Location.THIS.register(T_Location.getIndex(l_5_4), l_5_4);
		E_Location.THIS.register(T_Location.getIndex(l_5_5), l_5_5);
		E_Location.THIS.register(T_Location.getIndex(l_5_6), l_5_6);
		E_Location.THIS.register(T_Location.getIndex(l_5_7), l_5_7);
		E_Location.THIS.register(T_Location.getIndex(l_5_8), l_5_8);
		E_Location.THIS.register(T_Location.getIndex(l_5_9), l_5_9);
		E_Location.THIS.register(T_Location.getIndex(l_5_10), l_5_10);
		E_Location.THIS.register(T_Location.getIndex(l_6_1), l_6_1);
		E_Location.THIS.register(T_Location.getIndex(l_6_2), l_6_2);
		E_Location.THIS.register(T_Location.getIndex(l_6_3), l_6_3);
		E_Location.THIS.register(T_Location.getIndex(l_6_4), l_6_4);
		E_Location.THIS.register(T_Location.getIndex(l_6_5), l_6_5);
		E_Location.THIS.register(T_Location.getIndex(l_6_6), l_6_6);
		E_Location.THIS.register(T_Location.getIndex(l_6_7), l_6_7);
		E_Location.THIS.register(T_Location.getIndex(l_6_8), l_6_8);
		E_Location.THIS.register(T_Location.getIndex(l_6_9), l_6_9);
		E_Location.THIS.register(T_Location.getIndex(l_6_10), l_6_10);
		E_Location.THIS.register(T_Location.getIndex(l_7_1), l_7_1);
		E_Location.THIS.register(T_Location.getIndex(l_7_2), l_7_2);
		E_Location.THIS.register(T_Location.getIndex(l_7_3), l_7_3);
		E_Location.THIS.register(T_Location.getIndex(l_7_4), l_7_4);
		E_Location.THIS.register(T_Location.getIndex(l_7_5), l_7_5);
		E_Location.THIS.register(T_Location.getIndex(l_7_6), l_7_6);
		E_Location.THIS.register(T_Location.getIndex(l_7_7), l_7_7);
		E_Location.THIS.register(T_Location.getIndex(l_7_8), l_7_8);
		E_Location.THIS.register(T_Location.getIndex(l_7_9), l_7_9);
		E_Location.THIS.register(T_Location.getIndex(l_7_10), l_7_10);
		E_Location.THIS.register(T_Location.getIndex(l_8_1), l_8_1);
		E_Location.THIS.register(T_Location.getIndex(l_8_2), l_8_2);
		E_Location.THIS.register(T_Location.getIndex(l_8_3), l_8_3);
		E_Location.THIS.register(T_Location.getIndex(l_8_4), l_8_4);
		E_Location.THIS.register(T_Location.getIndex(l_8_5), l_8_5);
		E_Location.THIS.register(T_Location.getIndex(l_8_6), l_8_6);
		E_Location.THIS.register(T_Location.getIndex(l_8_7), l_8_7);
		E_Location.THIS.register(T_Location.getIndex(l_8_8), l_8_8);
		E_Location.THIS.register(T_Location.getIndex(l_8_9), l_8_9);
		E_Location.THIS.register(T_Location.getIndex(l_8_10), l_8_10);
		E_Location.THIS.register(T_Location.getIndex(l_9_1), l_9_1);
		E_Location.THIS.register(T_Location.getIndex(l_9_2), l_9_2);
		E_Location.THIS.register(T_Location.getIndex(l_9_3), l_9_3);
		E_Location.THIS.register(T_Location.getIndex(l_9_4), l_9_4);
		E_Location.THIS.register(T_Location.getIndex(l_9_5), l_9_5);
		E_Location.THIS.register(T_Location.getIndex(l_9_6), l_9_6);
		E_Location.THIS.register(T_Location.getIndex(l_9_7), l_9_7);
		E_Location.THIS.register(T_Location.getIndex(l_9_8), l_9_8);
		E_Location.THIS.register(T_Location.getIndex(l_9_9), l_9_9);
		E_Location.THIS.register(T_Location.getIndex(l_9_10), l_9_10);
		E_Location.THIS.register(T_Location.getIndex(l_10_1), l_10_1);
		E_Location.THIS.register(T_Location.getIndex(l_10_2), l_10_2);
		E_Location.THIS.register(T_Location.getIndex(l_10_3), l_10_3);
		E_Location.THIS.register(T_Location.getIndex(l_10_4), l_10_4);
		E_Location.THIS.register(T_Location.getIndex(l_10_5), l_10_5);
		E_Location.THIS.register(T_Location.getIndex(l_10_6), l_10_6);
		E_Location.THIS.register(T_Location.getIndex(l_10_7), l_10_7);
		E_Location.THIS.register(T_Location.getIndex(l_10_8), l_10_8);
		E_Location.THIS.register(T_Location.getIndex(l_10_9), l_10_9);
		E_Location.THIS.register(T_Location.getIndex(l_10_10), l_10_10);
		
	}
		
	protected E_Locations() {
	}

}