package cz.cuni.mff.perestroika.perestroika_problem_15_3_0_5_0_5_7;

import cz.cuni.mff.jpddl.PDDLDeadEnd;
import cz.cuni.mff.perestroika.domain.Domain;
import cz.cuni.mff.perestroika.domain.State;
import cz.cuni.mff.perestroika.problem.PerestroikaProblem;
import cz.cuni.mff.perestroika.problem1.DeadEnd;

public final class Problem extends PerestroikaProblem {
	
	static {
		// ENSURE STATIC INITIALIZATION OF THE CLASSES
		new E_Locations();
		new E_Resources();
	}
	
	public Domain domain;
	
	public State state;
	
	public Goal goal;
	
	public DeadEnd deadEnd;
	
	public Problem() {
		domain = new Domain();
		state = new State();
		goal = new Goal();
		deadEnd = new DeadEnd();
		
		state.p_ActRound.set();
		state.p_Alive.set();

		
		state.p_AtAgent.set(E_Locations.l_1_1);

		state.p_AtRes.set(E_Resources.r13, E_Locations.l_4_13);
		state.p_AtRes.set(E_Resources.r15, E_Locations.l_5_2);
		state.p_AtRes.set(E_Resources.r12, E_Locations.l_4_8);
		state.p_AtRes.set(E_Resources.r25, E_Locations.l_8_7);
		state.p_AtRes.set(E_Resources.r5, E_Locations.l_2_7);
		state.p_AtRes.set(E_Resources.r24, E_Locations.l_8_2);
		state.p_AtRes.set(E_Resources.r8, E_Locations.l_3_10);
		state.p_AtRes.set(E_Resources.r1, E_Locations.l_1_6);
		state.p_AtRes.set(E_Resources.r22, E_Locations.l_7_5);
		state.p_AtRes.set(E_Resources.r9, E_Locations.l_4_3);
		state.p_AtRes.set(E_Resources.r4, E_Locations.l_2_6);
		state.p_AtRes.set(E_Resources.r32, E_Locations.l_10_6);
		state.p_AtRes.set(E_Resources.r3, E_Locations.l_2_4);
		state.p_AtRes.set(E_Resources.r30, E_Locations.l_9_5);
		state.p_AtRes.set(E_Resources.r42, E_Locations.l_14_9);
		state.p_AtRes.set(E_Resources.r40, E_Locations.l_14_4);
		state.p_AtRes.set(E_Resources.r39, E_Locations.l_13_5);
		state.p_AtRes.set(E_Resources.r2, E_Locations.l_2_2);
		state.p_AtRes.set(E_Resources.r19, E_Locations.l_5_13);
		state.p_AtRes.set(E_Resources.r29, E_Locations.l_9_4);
		state.p_AtRes.set(E_Resources.r44, E_Locations.l_15_7);
		state.p_AtRes.set(E_Resources.r17, E_Locations.l_5_8);
		state.p_AtRes.set(E_Resources.r43, E_Locations.l_15_6);
		state.p_AtRes.set(E_Resources.r23, E_Locations.l_7_8);
		state.p_AtRes.set(E_Resources.r20, E_Locations.l_6_4);
		state.p_AtRes.set(E_Resources.r34, E_Locations.l_11_3);
		state.p_AtRes.set(E_Resources.r35, E_Locations.l_11_11);
		state.p_AtRes.set(E_Resources.r38, E_Locations.l_13_4);
		state.p_AtRes.set(E_Resources.r10, E_Locations.l_4_5);
		state.p_AtRes.set(E_Resources.r31, E_Locations.l_9_11);
		state.p_AtRes.set(E_Resources.r18, E_Locations.l_5_11);
		state.p_AtRes.set(E_Resources.r11, E_Locations.l_4_7);
		state.p_AtRes.set(E_Resources.r37, E_Locations.l_13_3);
		state.p_AtRes.set(E_Resources.r7, E_Locations.l_3_1);
		state.p_AtRes.set(E_Resources.r46, E_Locations.l_15_10);
		state.p_AtRes.set(E_Resources.r41, E_Locations.l_14_6);
		state.p_AtRes.set(E_Resources.r21, E_Locations.l_7_3);
		state.p_AtRes.set(E_Resources.r33, E_Locations.l_10_7);
		state.p_AtRes.set(E_Resources.r47, E_Locations.l_15_12);
		state.p_AtRes.set(E_Resources.r45, E_Locations.l_15_8);
		state.p_AtRes.set(E_Resources.r36, E_Locations.l_11_14);
		state.p_AtRes.set(E_Resources.r14, E_Locations.l_4_14);
		state.p_AtRes.set(E_Resources.r26, E_Locations.l_8_9);
		state.p_AtRes.set(E_Resources.r6, E_Locations.l_2_15);
		state.p_AtRes.set(E_Resources.r27, E_Locations.l_8_12);
		state.p_AtRes.set(E_Resources.r28, E_Locations.l_9_1);
		state.p_AtRes.set(E_Resources.r16, E_Locations.l_5_4);
		

		state.p_Connected.set(E_Locations.l_7_5, E_Locations.l_8_5);
		state.p_Connected.set(E_Locations.l_15_12, E_Locations.l_14_12);
		state.p_Connected.set(E_Locations.l_15_13, E_Locations.l_15_14);
		state.p_Connected.set(E_Locations.l_7_11, E_Locations.l_7_10);
		state.p_Connected.set(E_Locations.l_10_10, E_Locations.l_11_10);
		state.p_Connected.set(E_Locations.l_5_5, E_Locations.l_4_5);
		state.p_Connected.set(E_Locations.l_11_3, E_Locations.l_12_3);
		state.p_Connected.set(E_Locations.l_13_2, E_Locations.l_13_1);
		state.p_Connected.set(E_Locations.l_8_1, E_Locations.l_9_1);
		state.p_Connected.set(E_Locations.l_5_1, E_Locations.l_5_2);
		state.p_Connected.set(E_Locations.l_5_2, E_Locations.l_5_1);
		state.p_Connected.set(E_Locations.l_10_8, E_Locations.l_10_9);
		state.p_Connected.set(E_Locations.l_14_12, E_Locations.l_14_11);
		state.p_Connected.set(E_Locations.l_2_14, E_Locations.l_3_14);
		state.p_Connected.set(E_Locations.l_2_9, E_Locations.l_3_9);
		state.p_Connected.set(E_Locations.l_5_3, E_Locations.l_6_3);
		state.p_Connected.set(E_Locations.l_14_11, E_Locations.l_14_12);
		state.p_Connected.set(E_Locations.l_14_10, E_Locations.l_14_9);
		state.p_Connected.set(E_Locations.l_11_8, E_Locations.l_11_9);
		state.p_Connected.set(E_Locations.l_1_11, E_Locations.l_2_11);
		state.p_Connected.set(E_Locations.l_13_9, E_Locations.l_13_10);
		state.p_Connected.set(E_Locations.l_14_10, E_Locations.l_15_10);
		state.p_Connected.set(E_Locations.l_5_10, E_Locations.l_5_11);
		state.p_Connected.set(E_Locations.l_6_8, E_Locations.l_6_7);
		state.p_Connected.set(E_Locations.l_2_13, E_Locations.l_1_13);
		state.p_Connected.set(E_Locations.l_6_14, E_Locations.l_6_13);
		state.p_Connected.set(E_Locations.l_15_10, E_Locations.l_14_10);
		state.p_Connected.set(E_Locations.l_11_8, E_Locations.l_12_8);
		state.p_Connected.set(E_Locations.l_7_8, E_Locations.l_6_8);
		state.p_Connected.set(E_Locations.l_10_10, E_Locations.l_9_10);
		state.p_Connected.set(E_Locations.l_4_2, E_Locations.l_5_2);
		state.p_Connected.set(E_Locations.l_14_7, E_Locations.l_13_7);
		state.p_Connected.set(E_Locations.l_2_2, E_Locations.l_2_1);
		state.p_Connected.set(E_Locations.l_3_2, E_Locations.l_2_2);
		state.p_Connected.set(E_Locations.l_8_8, E_Locations.l_9_8);
		state.p_Connected.set(E_Locations.l_11_12, E_Locations.l_10_12);
		state.p_Connected.set(E_Locations.l_11_7, E_Locations.l_11_6);
		state.p_Connected.set(E_Locations.l_5_15, E_Locations.l_5_14);
		state.p_Connected.set(E_Locations.l_13_12, E_Locations.l_12_12);
		state.p_Connected.set(E_Locations.l_2_1, E_Locations.l_2_2);
		state.p_Connected.set(E_Locations.l_4_5, E_Locations.l_5_5);
		state.p_Connected.set(E_Locations.l_11_9, E_Locations.l_11_10);
		state.p_Connected.set(E_Locations.l_10_15, E_Locations.l_10_14);
		state.p_Connected.set(E_Locations.l_15_6, E_Locations.l_14_6);
		state.p_Connected.set(E_Locations.l_6_8, E_Locations.l_5_8);
		state.p_Connected.set(E_Locations.l_2_13, E_Locations.l_3_13);
		state.p_Connected.set(E_Locations.l_4_7, E_Locations.l_5_7);
		state.p_Connected.set(E_Locations.l_10_8, E_Locations.l_10_7);
		state.p_Connected.set(E_Locations.l_4_12, E_Locations.l_5_12);
		state.p_Connected.set(E_Locations.l_5_8, E_Locations.l_4_8);
		state.p_Connected.set(E_Locations.l_8_4, E_Locations.l_9_4);
		state.p_Connected.set(E_Locations.l_12_1, E_Locations.l_13_1);
		state.p_Connected.set(E_Locations.l_14_9, E_Locations.l_14_8);
		state.p_Connected.set(E_Locations.l_3_13, E_Locations.l_3_12);
		state.p_Connected.set(E_Locations.l_10_14, E_Locations.l_10_15);
		state.p_Connected.set(E_Locations.l_12_10, E_Locations.l_11_10);
		state.p_Connected.set(E_Locations.l_12_7, E_Locations.l_13_7);
		state.p_Connected.set(E_Locations.l_3_10, E_Locations.l_3_11);
		state.p_Connected.set(E_Locations.l_12_15, E_Locations.l_11_15);
		state.p_Connected.set(E_Locations.l_12_15, E_Locations.l_12_14);
		state.p_Connected.set(E_Locations.l_3_12, E_Locations.l_4_12);
		state.p_Connected.set(E_Locations.l_11_5, E_Locations.l_11_4);
		state.p_Connected.set(E_Locations.l_14_13, E_Locations.l_15_13);
		state.p_Connected.set(E_Locations.l_12_6, E_Locations.l_12_5);
		state.p_Connected.set(E_Locations.l_12_12, E_Locations.l_11_12);
		state.p_Connected.set(E_Locations.l_10_8, E_Locations.l_9_8);
		state.p_Connected.set(E_Locations.l_14_8, E_Locations.l_14_7);
		state.p_Connected.set(E_Locations.l_14_6, E_Locations.l_14_7);
		state.p_Connected.set(E_Locations.l_1_13, E_Locations.l_1_12);
		state.p_Connected.set(E_Locations.l_7_6, E_Locations.l_8_6);
		state.p_Connected.set(E_Locations.l_8_9, E_Locations.l_8_10);
		state.p_Connected.set(E_Locations.l_2_14, E_Locations.l_1_14);
		state.p_Connected.set(E_Locations.l_2_10, E_Locations.l_1_10);
		state.p_Connected.set(E_Locations.l_12_3, E_Locations.l_12_2);
		state.p_Connected.set(E_Locations.l_13_1, E_Locations.l_12_1);
		state.p_Connected.set(E_Locations.l_3_6, E_Locations.l_3_5);
		state.p_Connected.set(E_Locations.l_9_14, E_Locations.l_8_14);
		state.p_Connected.set(E_Locations.l_9_10, E_Locations.l_10_10);
		state.p_Connected.set(E_Locations.l_11_6, E_Locations.l_12_6);
		state.p_Connected.set(E_Locations.l_13_7, E_Locations.l_13_8);
		state.p_Connected.set(E_Locations.l_11_15, E_Locations.l_11_14);
		state.p_Connected.set(E_Locations.l_2_5, E_Locations.l_2_4);
		state.p_Connected.set(E_Locations.l_8_10, E_Locations.l_9_10);
		state.p_Connected.set(E_Locations.l_7_3, E_Locations.l_7_4);
		state.p_Connected.set(E_Locations.l_8_3, E_Locations.l_9_3);
		state.p_Connected.set(E_Locations.l_7_2, E_Locations.l_7_1);
		state.p_Connected.set(E_Locations.l_14_7, E_Locations.l_14_6);
		state.p_Connected.set(E_Locations.l_9_9, E_Locations.l_9_10);
		state.p_Connected.set(E_Locations.l_6_11, E_Locations.l_6_10);
		state.p_Connected.set(E_Locations.l_13_2, E_Locations.l_14_2);
		state.p_Connected.set(E_Locations.l_15_9, E_Locations.l_15_10);
		state.p_Connected.set(E_Locations.l_9_1, E_Locations.l_9_2);
		state.p_Connected.set(E_Locations.l_12_14, E_Locations.l_12_15);
		state.p_Connected.set(E_Locations.l_2_9, E_Locations.l_1_9);
		state.p_Connected.set(E_Locations.l_8_13, E_Locations.l_9_13);
		state.p_Connected.set(E_Locations.l_13_14, E_Locations.l_14_14);
		state.p_Connected.set(E_Locations.l_2_10, E_Locations.l_2_9);
		state.p_Connected.set(E_Locations.l_13_3, E_Locations.l_14_3);
		state.p_Connected.set(E_Locations.l_13_13, E_Locations.l_13_12);
		state.p_Connected.set(E_Locations.l_4_10, E_Locations.l_4_9);
		state.p_Connected.set(E_Locations.l_9_5, E_Locations.l_10_5);
		state.p_Connected.set(E_Locations.l_1_8, E_Locations.l_1_9);
		state.p_Connected.set(E_Locations.l_13_11, E_Locations.l_12_11);
		state.p_Connected.set(E_Locations.l_1_13, E_Locations.l_2_13);
		state.p_Connected.set(E_Locations.l_1_12, E_Locations.l_1_11);
		state.p_Connected.set(E_Locations.l_15_15, E_Locations.l_14_15);
		state.p_Connected.set(E_Locations.l_14_5, E_Locations.l_14_6);
		state.p_Connected.set(E_Locations.l_1_15, E_Locations.l_1_14);
		state.p_Connected.set(E_Locations.l_7_10, E_Locations.l_7_11);
		state.p_Connected.set(E_Locations.l_14_15, E_Locations.l_15_15);
		state.p_Connected.set(E_Locations.l_7_6, E_Locations.l_7_7);
		state.p_Connected.set(E_Locations.l_10_6, E_Locations.l_9_6);
		state.p_Connected.set(E_Locations.l_12_6, E_Locations.l_11_6);
		state.p_Connected.set(E_Locations.l_7_5, E_Locations.l_7_4);
		state.p_Connected.set(E_Locations.l_10_9, E_Locations.l_10_8);
		state.p_Connected.set(E_Locations.l_11_8, E_Locations.l_10_8);
		state.p_Connected.set(E_Locations.l_13_4, E_Locations.l_13_3);
		state.p_Connected.set(E_Locations.l_1_8, E_Locations.l_2_8);
		state.p_Connected.set(E_Locations.l_3_2, E_Locations.l_3_1);
		state.p_Connected.set(E_Locations.l_7_2, E_Locations.l_6_2);
		state.p_Connected.set(E_Locations.l_6_10, E_Locations.l_7_10);
		state.p_Connected.set(E_Locations.l_9_6, E_Locations.l_8_6);
		state.p_Connected.set(E_Locations.l_9_11, E_Locations.l_9_10);
		state.p_Connected.set(E_Locations.l_14_14, E_Locations.l_14_13);
		state.p_Connected.set(E_Locations.l_15_6, E_Locations.l_15_7);
		state.p_Connected.set(E_Locations.l_2_4, E_Locations.l_3_4);
		state.p_Connected.set(E_Locations.l_5_7, E_Locations.l_4_7);
		state.p_Connected.set(E_Locations.l_12_12, E_Locations.l_13_12);
		state.p_Connected.set(E_Locations.l_2_1, E_Locations.l_3_1);
		state.p_Connected.set(E_Locations.l_4_12, E_Locations.l_4_11);
		state.p_Connected.set(E_Locations.l_8_11, E_Locations.l_9_11);
		state.p_Connected.set(E_Locations.l_13_12, E_Locations.l_14_12);
		state.p_Connected.set(E_Locations.l_7_13, E_Locations.l_7_14);
		state.p_Connected.set(E_Locations.l_15_2, E_Locations.l_14_2);
		state.p_Connected.set(E_Locations.l_9_11, E_Locations.l_8_11);
		state.p_Connected.set(E_Locations.l_9_8, E_Locations.l_9_7);
		state.p_Connected.set(E_Locations.l_2_7, E_Locations.l_2_6);
		state.p_Connected.set(E_Locations.l_12_9, E_Locations.l_12_8);
		state.p_Connected.set(E_Locations.l_10_2, E_Locations.l_10_3);
		state.p_Connected.set(E_Locations.l_10_4, E_Locations.l_11_4);
		state.p_Connected.set(E_Locations.l_12_13, E_Locations.l_12_14);
		state.p_Connected.set(E_Locations.l_3_3, E_Locations.l_4_3);
		state.p_Connected.set(E_Locations.l_8_11, E_Locations.l_8_12);
		state.p_Connected.set(E_Locations.l_6_9, E_Locations.l_5_9);
		state.p_Connected.set(E_Locations.l_11_4, E_Locations.l_12_4);
		state.p_Connected.set(E_Locations.l_3_12, E_Locations.l_3_13);
		state.p_Connected.set(E_Locations.l_15_11, E_Locations.l_14_11);
		state.p_Connected.set(E_Locations.l_6_9, E_Locations.l_6_10);
		state.p_Connected.set(E_Locations.l_4_5, E_Locations.l_4_6);
		state.p_Connected.set(E_Locations.l_14_1, E_Locations.l_14_2);
		state.p_Connected.set(E_Locations.l_10_14, E_Locations.l_9_14);
		state.p_Connected.set(E_Locations.l_4_7, E_Locations.l_3_7);
		state.p_Connected.set(E_Locations.l_3_2, E_Locations.l_4_2);
		state.p_Connected.set(E_Locations.l_10_2, E_Locations.l_10_1);
		state.p_Connected.set(E_Locations.l_4_9, E_Locations.l_5_9);
		state.p_Connected.set(E_Locations.l_14_2, E_Locations.l_14_3);
		state.p_Connected.set(E_Locations.l_14_8, E_Locations.l_15_8);
		state.p_Connected.set(E_Locations.l_8_15, E_Locations.l_9_15);
		state.p_Connected.set(E_Locations.l_3_4, E_Locations.l_3_3);
		state.p_Connected.set(E_Locations.l_14_13, E_Locations.l_14_14);
		state.p_Connected.set(E_Locations.l_12_5, E_Locations.l_11_5);
		state.p_Connected.set(E_Locations.l_13_6, E_Locations.l_12_6);
		state.p_Connected.set(E_Locations.l_13_11, E_Locations.l_14_11);
		state.p_Connected.set(E_Locations.l_11_10, E_Locations.l_11_9);
		state.p_Connected.set(E_Locations.l_14_12, E_Locations.l_13_12);
		state.p_Connected.set(E_Locations.l_7_11, E_Locations.l_8_11);
		state.p_Connected.set(E_Locations.l_5_8, E_Locations.l_5_7);
		state.p_Connected.set(E_Locations.l_9_6, E_Locations.l_9_7);
		state.p_Connected.set(E_Locations.l_13_10, E_Locations.l_12_10);
		state.p_Connected.set(E_Locations.l_13_12, E_Locations.l_13_11);
		state.p_Connected.set(E_Locations.l_5_5, E_Locations.l_6_5);
		state.p_Connected.set(E_Locations.l_8_5, E_Locations.l_8_4);
		state.p_Connected.set(E_Locations.l_8_4, E_Locations.l_8_3);
		state.p_Connected.set(E_Locations.l_4_4, E_Locations.l_3_4);
		state.p_Connected.set(E_Locations.l_15_14, E_Locations.l_15_15);
		state.p_Connected.set(E_Locations.l_4_9, E_Locations.l_4_10);
		state.p_Connected.set(E_Locations.l_4_14, E_Locations.l_5_14);
		state.p_Connected.set(E_Locations.l_13_2, E_Locations.l_13_3);
		state.p_Connected.set(E_Locations.l_11_2, E_Locations.l_12_2);
		state.p_Connected.set(E_Locations.l_11_13, E_Locations.l_10_13);
		state.p_Connected.set(E_Locations.l_7_13, E_Locations.l_7_12);
		state.p_Connected.set(E_Locations.l_15_2, E_Locations.l_15_3);
		state.p_Connected.set(E_Locations.l_14_5, E_Locations.l_13_5);
		state.p_Connected.set(E_Locations.l_2_3, E_Locations.l_1_3);
		state.p_Connected.set(E_Locations.l_2_6, E_Locations.l_1_6);
		state.p_Connected.set(E_Locations.l_11_11, E_Locations.l_11_12);
		state.p_Connected.set(E_Locations.l_6_4, E_Locations.l_6_3);
		state.p_Connected.set(E_Locations.l_8_11, E_Locations.l_8_10);
		state.p_Connected.set(E_Locations.l_14_4, E_Locations.l_15_4);
		state.p_Connected.set(E_Locations.l_12_8, E_Locations.l_12_9);
		state.p_Connected.set(E_Locations.l_2_3, E_Locations.l_3_3);
		state.p_Connected.set(E_Locations.l_13_15, E_Locations.l_13_14);
		state.p_Connected.set(E_Locations.l_3_9, E_Locations.l_3_8);
		state.p_Connected.set(E_Locations.l_13_14, E_Locations.l_13_15);
		state.p_Connected.set(E_Locations.l_11_4, E_Locations.l_10_4);
		state.p_Connected.set(E_Locations.l_15_10, E_Locations.l_15_9);
		state.p_Connected.set(E_Locations.l_12_3, E_Locations.l_12_4);
		state.p_Connected.set(E_Locations.l_10_4, E_Locations.l_9_4);
		state.p_Connected.set(E_Locations.l_9_1, E_Locations.l_10_1);
		state.p_Connected.set(E_Locations.l_7_4, E_Locations.l_8_4);
		state.p_Connected.set(E_Locations.l_12_7, E_Locations.l_11_7);
		state.p_Connected.set(E_Locations.l_4_13, E_Locations.l_3_13);
		state.p_Connected.set(E_Locations.l_6_14, E_Locations.l_5_14);
		state.p_Connected.set(E_Locations.l_14_5, E_Locations.l_15_5);
		state.p_Connected.set(E_Locations.l_6_15, E_Locations.l_7_15);
		state.p_Connected.set(E_Locations.l_11_14, E_Locations.l_11_13);
		state.p_Connected.set(E_Locations.l_5_7, E_Locations.l_5_6);
		state.p_Connected.set(E_Locations.l_8_12, E_Locations.l_8_11);
		state.p_Connected.set(E_Locations.l_3_7, E_Locations.l_3_8);
		state.p_Connected.set(E_Locations.l_9_15, E_Locations.l_10_15);
		state.p_Connected.set(E_Locations.l_9_2, E_Locations.l_8_2);
		state.p_Connected.set(E_Locations.l_11_7, E_Locations.l_11_8);
		state.p_Connected.set(E_Locations.l_10_12, E_Locations.l_10_11);
		state.p_Connected.set(E_Locations.l_8_12, E_Locations.l_9_12);
		state.p_Connected.set(E_Locations.l_5_10, E_Locations.l_6_10);
		state.p_Connected.set(E_Locations.l_6_3, E_Locations.l_6_2);
		state.p_Connected.set(E_Locations.l_11_9, E_Locations.l_10_9);
		state.p_Connected.set(E_Locations.l_4_3, E_Locations.l_3_3);
		state.p_Connected.set(E_Locations.l_5_3, E_Locations.l_5_4);
		state.p_Connected.set(E_Locations.l_11_4, E_Locations.l_11_5);
		state.p_Connected.set(E_Locations.l_4_9, E_Locations.l_3_9);
		state.p_Connected.set(E_Locations.l_11_7, E_Locations.l_10_7);
		state.p_Connected.set(E_Locations.l_13_7, E_Locations.l_12_7);
		state.p_Connected.set(E_Locations.l_10_1, E_Locations.l_11_1);
		state.p_Connected.set(E_Locations.l_7_2, E_Locations.l_7_3);
		state.p_Connected.set(E_Locations.l_6_7, E_Locations.l_6_8);
		state.p_Connected.set(E_Locations.l_5_12, E_Locations.l_5_11);
		state.p_Connected.set(E_Locations.l_12_8, E_Locations.l_12_7);
		state.p_Connected.set(E_Locations.l_11_5, E_Locations.l_10_5);
		state.p_Connected.set(E_Locations.l_15_9, E_Locations.l_15_8);
		state.p_Connected.set(E_Locations.l_5_5, E_Locations.l_5_6);
		state.p_Connected.set(E_Locations.l_13_8, E_Locations.l_14_8);
		state.p_Connected.set(E_Locations.l_3_9, E_Locations.l_3_10);
		state.p_Connected.set(E_Locations.l_12_2, E_Locations.l_12_1);
		state.p_Connected.set(E_Locations.l_6_3, E_Locations.l_6_4);
		state.p_Connected.set(E_Locations.l_12_3, E_Locations.l_11_3);
		state.p_Connected.set(E_Locations.l_4_2, E_Locations.l_4_3);
		state.p_Connected.set(E_Locations.l_6_12, E_Locations.l_6_11);
		state.p_Connected.set(E_Locations.l_10_9, E_Locations.l_11_9);
		state.p_Connected.set(E_Locations.l_7_11, E_Locations.l_6_11);
		state.p_Connected.set(E_Locations.l_13_13, E_Locations.l_14_13);
		state.p_Connected.set(E_Locations.l_5_4, E_Locations.l_4_4);
		state.p_Connected.set(E_Locations.l_12_14, E_Locations.l_12_13);
		state.p_Connected.set(E_Locations.l_14_1, E_Locations.l_15_1);
		state.p_Connected.set(E_Locations.l_14_6, E_Locations.l_14_5);
		state.p_Connected.set(E_Locations.l_6_4, E_Locations.l_6_5);
		state.p_Connected.set(E_Locations.l_7_14, E_Locations.l_7_15);
		state.p_Connected.set(E_Locations.l_11_1, E_Locations.l_10_1);
		state.p_Connected.set(E_Locations.l_14_14, E_Locations.l_14_15);
		state.p_Connected.set(E_Locations.l_1_14, E_Locations.l_2_14);
		state.p_Connected.set(E_Locations.l_6_11, E_Locations.l_5_11);
		state.p_Connected.set(E_Locations.l_8_8, E_Locations.l_8_9);
		state.p_Connected.set(E_Locations.l_1_4, E_Locations.l_1_5);
		state.p_Connected.set(E_Locations.l_2_3, E_Locations.l_2_2);
		state.p_Connected.set(E_Locations.l_9_12, E_Locations.l_8_12);
		state.p_Connected.set(E_Locations.l_10_7, E_Locations.l_10_6);
		state.p_Connected.set(E_Locations.l_15_8, E_Locations.l_15_7);
		state.p_Connected.set(E_Locations.l_4_12, E_Locations.l_3_12);
		state.p_Connected.set(E_Locations.l_4_1, E_Locations.l_3_1);
		state.p_Connected.set(E_Locations.l_13_14, E_Locations.l_13_13);
		state.p_Connected.set(E_Locations.l_4_14, E_Locations.l_4_15);
		state.p_Connected.set(E_Locations.l_12_13, E_Locations.l_12_12);
		state.p_Connected.set(E_Locations.l_5_6, E_Locations.l_4_6);
		state.p_Connected.set(E_Locations.l_4_6, E_Locations.l_3_6);
		state.p_Connected.set(E_Locations.l_9_10, E_Locations.l_9_11);
		state.p_Connected.set(E_Locations.l_11_3, E_Locations.l_11_2);
		state.p_Connected.set(E_Locations.l_7_3, E_Locations.l_8_3);
		state.p_Connected.set(E_Locations.l_8_6, E_Locations.l_9_6);
		state.p_Connected.set(E_Locations.l_2_8, E_Locations.l_3_8);
		state.p_Connected.set(E_Locations.l_13_9, E_Locations.l_12_9);
		state.p_Connected.set(E_Locations.l_8_7, E_Locations.l_8_8);
		state.p_Connected.set(E_Locations.l_4_15, E_Locations.l_3_15);
		state.p_Connected.set(E_Locations.l_8_3, E_Locations.l_8_4);
		state.p_Connected.set(E_Locations.l_7_14, E_Locations.l_6_14);
		state.p_Connected.set(E_Locations.l_14_9, E_Locations.l_15_9);
		state.p_Connected.set(E_Locations.l_15_2, E_Locations.l_15_1);
		state.p_Connected.set(E_Locations.l_4_5, E_Locations.l_3_5);
		state.p_Connected.set(E_Locations.l_4_11, E_Locations.l_5_11);
		state.p_Connected.set(E_Locations.l_7_3, E_Locations.l_6_3);
		state.p_Connected.set(E_Locations.l_8_13, E_Locations.l_8_14);
		state.p_Connected.set(E_Locations.l_3_2, E_Locations.l_3_3);
		state.p_Connected.set(E_Locations.l_7_12, E_Locations.l_8_12);
		state.p_Connected.set(E_Locations.l_1_5, E_Locations.l_2_5);
		state.p_Connected.set(E_Locations.l_11_11, E_Locations.l_12_11);
		state.p_Connected.set(E_Locations.l_11_10, E_Locations.l_10_10);
		state.p_Connected.set(E_Locations.l_10_3, E_Locations.l_10_2);
		state.p_Connected.set(E_Locations.l_2_13, E_Locations.l_2_12);
		state.p_Connected.set(E_Locations.l_9_15, E_Locations.l_9_14);
		state.p_Connected.set(E_Locations.l_13_5, E_Locations.l_13_6);
		state.p_Connected.set(E_Locations.l_4_7, E_Locations.l_4_6);
		state.p_Connected.set(E_Locations.l_15_3, E_Locations.l_15_2);
		state.p_Connected.set(E_Locations.l_7_13, E_Locations.l_8_13);
		state.p_Connected.set(E_Locations.l_14_2, E_Locations.l_14_1);
		state.p_Connected.set(E_Locations.l_2_11, E_Locations.l_1_11);
		state.p_Connected.set(E_Locations.l_12_12, E_Locations.l_12_13);
		state.p_Connected.set(E_Locations.l_8_1, E_Locations.l_7_1);
		state.p_Connected.set(E_Locations.l_9_7, E_Locations.l_9_6);
		state.p_Connected.set(E_Locations.l_3_3, E_Locations.l_2_3);
		state.p_Connected.set(E_Locations.l_8_8, E_Locations.l_7_8);
		state.p_Connected.set(E_Locations.l_6_11, E_Locations.l_7_11);
		state.p_Connected.set(E_Locations.l_6_1, E_Locations.l_5_1);
		state.p_Connected.set(E_Locations.l_5_14, E_Locations.l_5_13);
		state.p_Connected.set(E_Locations.l_3_14, E_Locations.l_4_14);
		state.p_Connected.set(E_Locations.l_13_4, E_Locations.l_14_4);
		state.p_Connected.set(E_Locations.l_10_11, E_Locations.l_10_10);
		state.p_Connected.set(E_Locations.l_13_11, E_Locations.l_13_10);
		state.p_Connected.set(E_Locations.l_2_7, E_Locations.l_1_7);
		state.p_Connected.set(E_Locations.l_10_4, E_Locations.l_10_5);
		state.p_Connected.set(E_Locations.l_3_8, E_Locations.l_3_7);
		state.p_Connected.set(E_Locations.l_12_13, E_Locations.l_11_13);
		state.p_Connected.set(E_Locations.l_12_8, E_Locations.l_13_8);
		state.p_Connected.set(E_Locations.l_1_14, E_Locations.l_1_13);
		state.p_Connected.set(E_Locations.l_7_7, E_Locations.l_6_7);
		state.p_Connected.set(E_Locations.l_5_14, E_Locations.l_6_14);
		state.p_Connected.set(E_Locations.l_12_9, E_Locations.l_13_9);
		state.p_Connected.set(E_Locations.l_6_8, E_Locations.l_7_8);
		state.p_Connected.set(E_Locations.l_3_5, E_Locations.l_3_6);
		state.p_Connected.set(E_Locations.l_3_3, E_Locations.l_3_4);
		state.p_Connected.set(E_Locations.l_7_15, E_Locations.l_7_14);
		state.p_Connected.set(E_Locations.l_2_12, E_Locations.l_3_12);
		state.p_Connected.set(E_Locations.l_8_6, E_Locations.l_8_7);
		state.p_Connected.set(E_Locations.l_10_7, E_Locations.l_10_8);
		state.p_Connected.set(E_Locations.l_10_15, E_Locations.l_11_15);
		state.p_Connected.set(E_Locations.l_4_9, E_Locations.l_4_8);
		state.p_Connected.set(E_Locations.l_5_12, E_Locations.l_5_13);
		state.p_Connected.set(E_Locations.l_1_4, E_Locations.l_2_4);
		state.p_Connected.set(E_Locations.l_6_2, E_Locations.l_6_1);
		state.p_Connected.set(E_Locations.l_3_5, E_Locations.l_3_4);
		state.p_Connected.set(E_Locations.l_2_10, E_Locations.l_3_10);
		state.p_Connected.set(E_Locations.l_10_10, E_Locations.l_10_11);
		state.p_Connected.set(E_Locations.l_6_7, E_Locations.l_6_6);
		state.p_Connected.set(E_Locations.l_4_11, E_Locations.l_4_10);
		state.p_Connected.set(E_Locations.l_15_5, E_Locations.l_15_4);
		state.p_Connected.set(E_Locations.l_5_13, E_Locations.l_4_13);
		state.p_Connected.set(E_Locations.l_12_15, E_Locations.l_13_15);
		state.p_Connected.set(E_Locations.l_7_10, E_Locations.l_8_10);
		state.p_Connected.set(E_Locations.l_2_2, E_Locations.l_2_3);
		state.p_Connected.set(E_Locations.l_6_10, E_Locations.l_6_9);
		state.p_Connected.set(E_Locations.l_10_11, E_Locations.l_10_12);
		state.p_Connected.set(E_Locations.l_14_9, E_Locations.l_13_9);
		state.p_Connected.set(E_Locations.l_1_6, E_Locations.l_1_5);
		state.p_Connected.set(E_Locations.l_15_4, E_Locations.l_15_5);
		state.p_Connected.set(E_Locations.l_9_13, E_Locations.l_9_14);
		state.p_Connected.set(E_Locations.l_7_5, E_Locations.l_6_5);
		state.p_Connected.set(E_Locations.l_6_8, E_Locations.l_6_9);
		state.p_Connected.set(E_Locations.l_2_6, E_Locations.l_2_5);
		state.p_Connected.set(E_Locations.l_2_4, E_Locations.l_2_3);
		state.p_Connected.set(E_Locations.l_6_1, E_Locations.l_7_1);
		state.p_Connected.set(E_Locations.l_6_15, E_Locations.l_6_14);
		state.p_Connected.set(E_Locations.l_9_10, E_Locations.l_9_9);
		state.p_Connected.set(E_Locations.l_12_5, E_Locations.l_12_4);
		state.p_Connected.set(E_Locations.l_8_6, E_Locations.l_8_5);
		state.p_Connected.set(E_Locations.l_3_7, E_Locations.l_3_6);
		state.p_Connected.set(E_Locations.l_6_10, E_Locations.l_5_10);
		state.p_Connected.set(E_Locations.l_6_9, E_Locations.l_6_8);
		state.p_Connected.set(E_Locations.l_11_6, E_Locations.l_11_7);
		state.p_Connected.set(E_Locations.l_11_3, E_Locations.l_10_3);
		state.p_Connected.set(E_Locations.l_3_8, E_Locations.l_3_9);
		state.p_Connected.set(E_Locations.l_5_1, E_Locations.l_6_1);
		state.p_Connected.set(E_Locations.l_10_9, E_Locations.l_9_9);
		state.p_Connected.set(E_Locations.l_15_11, E_Locations.l_15_10);
		state.p_Connected.set(E_Locations.l_12_12, E_Locations.l_12_11);
		state.p_Connected.set(E_Locations.l_10_8, E_Locations.l_11_8);
		state.p_Connected.set(E_Locations.l_13_10, E_Locations.l_13_9);
		state.p_Connected.set(E_Locations.l_3_8, E_Locations.l_4_8);
		state.p_Connected.set(E_Locations.l_14_11, E_Locations.l_14_10);
		state.p_Connected.set(E_Locations.l_2_3, E_Locations.l_2_4);
		state.p_Connected.set(E_Locations.l_9_6, E_Locations.l_9_5);
		state.p_Connected.set(E_Locations.l_9_3, E_Locations.l_9_2);
		state.p_Connected.set(E_Locations.l_3_15, E_Locations.l_3_14);
		state.p_Connected.set(E_Locations.l_15_1, E_Locations.l_15_2);
		state.p_Connected.set(E_Locations.l_9_14, E_Locations.l_9_15);
		state.p_Connected.set(E_Locations.l_14_3, E_Locations.l_14_2);
		state.p_Connected.set(E_Locations.l_14_4, E_Locations.l_13_4);
		state.p_Connected.set(E_Locations.l_11_6, E_Locations.l_11_5);
		state.p_Connected.set(E_Locations.l_7_9, E_Locations.l_7_10);
		state.p_Connected.set(E_Locations.l_13_4, E_Locations.l_12_4);
		state.p_Connected.set(E_Locations.l_13_10, E_Locations.l_13_11);
		state.p_Connected.set(E_Locations.l_12_11, E_Locations.l_12_10);
		state.p_Connected.set(E_Locations.l_3_4, E_Locations.l_4_4);
		state.p_Connected.set(E_Locations.l_7_3, E_Locations.l_7_2);
		state.p_Connected.set(E_Locations.l_14_7, E_Locations.l_15_7);
		state.p_Connected.set(E_Locations.l_7_7, E_Locations.l_8_7);
		state.p_Connected.set(E_Locations.l_2_6, E_Locations.l_2_7);
		state.p_Connected.set(E_Locations.l_14_13, E_Locations.l_13_13);
		state.p_Connected.set(E_Locations.l_8_13, E_Locations.l_7_13);
		state.p_Connected.set(E_Locations.l_2_9, E_Locations.l_2_10);
		state.p_Connected.set(E_Locations.l_10_11, E_Locations.l_11_11);
		state.p_Connected.set(E_Locations.l_6_13, E_Locations.l_5_13);
		state.p_Connected.set(E_Locations.l_5_7, E_Locations.l_5_8);
		state.p_Connected.set(E_Locations.l_7_9, E_Locations.l_8_9);
		state.p_Connected.set(E_Locations.l_3_8, E_Locations.l_2_8);
		state.p_Connected.set(E_Locations.l_4_1, E_Locations.l_4_2);
		state.p_Connected.set(E_Locations.l_7_9, E_Locations.l_6_9);
		state.p_Connected.set(E_Locations.l_2_14, E_Locations.l_2_13);
		state.p_Connected.set(E_Locations.l_3_11, E_Locations.l_3_12);
		state.p_Connected.set(E_Locations.l_5_15, E_Locations.l_4_15);
		state.p_Connected.set(E_Locations.l_14_9, E_Locations.l_14_10);
		state.p_Connected.set(E_Locations.l_14_10, E_Locations.l_14_11);
		state.p_Connected.set(E_Locations.l_3_1, E_Locations.l_4_1);
		state.p_Connected.set(E_Locations.l_11_6, E_Locations.l_10_6);
		state.p_Connected.set(E_Locations.l_11_12, E_Locations.l_11_11);
		state.p_Connected.set(E_Locations.l_5_13, E_Locations.l_6_13);
		state.p_Connected.set(E_Locations.l_12_11, E_Locations.l_13_11);
		state.p_Connected.set(E_Locations.l_4_5, E_Locations.l_4_4);
		state.p_Connected.set(E_Locations.l_10_4, E_Locations.l_10_3);
		state.p_Connected.set(E_Locations.l_9_13, E_Locations.l_9_12);
		state.p_Connected.set(E_Locations.l_4_13, E_Locations.l_4_14);
		state.p_Connected.set(E_Locations.l_5_11, E_Locations.l_5_10);
		state.p_Connected.set(E_Locations.l_12_10, E_Locations.l_12_11);
		state.p_Connected.set(E_Locations.l_4_7, E_Locations.l_4_8);
		state.p_Connected.set(E_Locations.l_7_1, E_Locations.l_6_1);
		state.p_Connected.set(E_Locations.l_3_7, E_Locations.l_2_7);
		state.p_Connected.set(E_Locations.l_1_11, E_Locations.l_1_10);
		state.p_Connected.set(E_Locations.l_12_14, E_Locations.l_11_14);
		state.p_Connected.set(E_Locations.l_15_4, E_Locations.l_15_3);
		state.p_Connected.set(E_Locations.l_13_6, E_Locations.l_13_5);
		state.p_Connected.set(E_Locations.l_12_7, E_Locations.l_12_6);
		state.p_Connected.set(E_Locations.l_1_12, E_Locations.l_2_12);
		state.p_Connected.set(E_Locations.l_3_13, E_Locations.l_3_14);
		state.p_Connected.set(E_Locations.l_3_1, E_Locations.l_3_2);
		state.p_Connected.set(E_Locations.l_15_14, E_Locations.l_15_13);
		state.p_Connected.set(E_Locations.l_14_1, E_Locations.l_13_1);
		state.p_Connected.set(E_Locations.l_5_9, E_Locations.l_6_9);
		state.p_Connected.set(E_Locations.l_14_2, E_Locations.l_15_2);
		state.p_Connected.set(E_Locations.l_7_10, E_Locations.l_7_9);
		state.p_Connected.set(E_Locations.l_3_11, E_Locations.l_3_10);
		state.p_Connected.set(E_Locations.l_5_13, E_Locations.l_5_12);
		state.p_Connected.set(E_Locations.l_7_7, E_Locations.l_7_8);
		state.p_Connected.set(E_Locations.l_9_4, E_Locations.l_10_4);
		state.p_Connected.set(E_Locations.l_5_6, E_Locations.l_6_6);
		state.p_Connected.set(E_Locations.l_5_4, E_Locations.l_5_3);
		state.p_Connected.set(E_Locations.l_5_8, E_Locations.l_5_9);
		state.p_Connected.set(E_Locations.l_10_3, E_Locations.l_11_3);
		state.p_Connected.set(E_Locations.l_9_8, E_Locations.l_9_9);
		state.p_Connected.set(E_Locations.l_10_12, E_Locations.l_9_12);
		state.p_Connected.set(E_Locations.l_4_11, E_Locations.l_3_11);
		state.p_Connected.set(E_Locations.l_1_6, E_Locations.l_2_6);
		state.p_Connected.set(E_Locations.l_12_14, E_Locations.l_13_14);
		state.p_Connected.set(E_Locations.l_5_2, E_Locations.l_6_2);
		state.p_Connected.set(E_Locations.l_11_2, E_Locations.l_10_2);
		state.p_Connected.set(E_Locations.l_6_12, E_Locations.l_7_12);
		state.p_Connected.set(E_Locations.l_12_13, E_Locations.l_13_13);
		state.p_Connected.set(E_Locations.l_3_9, E_Locations.l_2_9);
		state.p_Connected.set(E_Locations.l_7_14, E_Locations.l_7_13);
		state.p_Connected.set(E_Locations.l_11_2, E_Locations.l_11_1);
		state.p_Connected.set(E_Locations.l_8_5, E_Locations.l_7_5);
		state.p_Connected.set(E_Locations.l_7_5, E_Locations.l_7_6);
		state.p_Connected.set(E_Locations.l_12_2, E_Locations.l_11_2);
		state.p_Connected.set(E_Locations.l_6_5, E_Locations.l_6_6);
		state.p_Connected.set(E_Locations.l_13_6, E_Locations.l_14_6);
		state.p_Connected.set(E_Locations.l_13_2, E_Locations.l_12_2);
		state.p_Connected.set(E_Locations.l_14_6, E_Locations.l_15_6);
		state.p_Connected.set(E_Locations.l_2_15, E_Locations.l_3_15);
		state.p_Connected.set(E_Locations.l_7_4, E_Locations.l_7_3);
		state.p_Connected.set(E_Locations.l_8_4, E_Locations.l_8_5);
		state.p_Connected.set(E_Locations.l_10_3, E_Locations.l_10_4);
		state.p_Connected.set(E_Locations.l_11_15, E_Locations.l_10_15);
		state.p_Connected.set(E_Locations.l_2_2, E_Locations.l_1_2);
		state.p_Connected.set(E_Locations.l_4_3, E_Locations.l_5_3);
		state.p_Connected.set(E_Locations.l_9_13, E_Locations.l_10_13);
		state.p_Connected.set(E_Locations.l_6_13, E_Locations.l_7_13);
		state.p_Connected.set(E_Locations.l_9_8, E_Locations.l_8_8);
		state.p_Connected.set(E_Locations.l_11_5, E_Locations.l_12_5);
		state.p_Connected.set(E_Locations.l_6_12, E_Locations.l_6_13);
		state.p_Connected.set(E_Locations.l_2_5, E_Locations.l_3_5);
		state.p_Connected.set(E_Locations.l_15_15, E_Locations.l_15_14);
		state.p_Connected.set(E_Locations.l_2_2, E_Locations.l_3_2);
		state.p_Connected.set(E_Locations.l_2_5, E_Locations.l_2_6);
		state.p_Connected.set(E_Locations.l_3_10, E_Locations.l_2_10);
		state.p_Connected.set(E_Locations.l_9_4, E_Locations.l_9_5);
		state.p_Connected.set(E_Locations.l_1_10, E_Locations.l_2_10);
		state.p_Connected.set(E_Locations.l_1_7, E_Locations.l_1_8);
		state.p_Connected.set(E_Locations.l_2_10, E_Locations.l_2_11);
		state.p_Connected.set(E_Locations.l_7_8, E_Locations.l_7_9);
		state.p_Connected.set(E_Locations.l_9_5, E_Locations.l_9_6);
		state.p_Connected.set(E_Locations.l_12_4, E_Locations.l_12_3);
		state.p_Connected.set(E_Locations.l_13_7, E_Locations.l_14_7);
		state.p_Connected.set(E_Locations.l_1_5, E_Locations.l_1_6);
		state.p_Connected.set(E_Locations.l_10_13, E_Locations.l_10_12);
		state.p_Connected.set(E_Locations.l_14_8, E_Locations.l_13_8);
		state.p_Connected.set(E_Locations.l_3_6, E_Locations.l_4_6);
		state.p_Connected.set(E_Locations.l_1_9, E_Locations.l_1_8);
		state.p_Connected.set(E_Locations.l_1_10, E_Locations.l_1_11);
		state.p_Connected.set(E_Locations.l_5_9, E_Locations.l_5_10);
		state.p_Connected.set(E_Locations.l_4_10, E_Locations.l_3_10);
		state.p_Connected.set(E_Locations.l_3_5, E_Locations.l_4_5);
		state.p_Connected.set(E_Locations.l_13_11, E_Locations.l_13_12);
		state.p_Connected.set(E_Locations.l_9_12, E_Locations.l_10_12);
		state.p_Connected.set(E_Locations.l_4_1, E_Locations.l_5_1);
		state.p_Connected.set(E_Locations.l_11_4, E_Locations.l_11_3);
		state.p_Connected.set(E_Locations.l_7_12, E_Locations.l_6_12);
		state.p_Connected.set(E_Locations.l_13_13, E_Locations.l_13_14);
		state.p_Connected.set(E_Locations.l_1_3, E_Locations.l_1_4);
		state.p_Connected.set(E_Locations.l_7_8, E_Locations.l_8_8);
		state.p_Connected.set(E_Locations.l_2_7, E_Locations.l_3_7);
		state.p_Connected.set(E_Locations.l_11_9, E_Locations.l_12_9);
		state.p_Connected.set(E_Locations.l_11_1, E_Locations.l_12_1);
		state.p_Connected.set(E_Locations.l_8_3, E_Locations.l_8_2);
		state.p_Connected.set(E_Locations.l_11_3, E_Locations.l_11_4);
		state.p_Connected.set(E_Locations.l_10_14, E_Locations.l_10_13);
		state.p_Connected.set(E_Locations.l_11_13, E_Locations.l_12_13);
		state.p_Connected.set(E_Locations.l_5_11, E_Locations.l_5_12);
		state.p_Connected.set(E_Locations.l_12_6, E_Locations.l_13_6);
		state.p_Connected.set(E_Locations.l_3_11, E_Locations.l_2_11);
		state.p_Connected.set(E_Locations.l_5_14, E_Locations.l_5_15);
		state.p_Connected.set(E_Locations.l_15_3, E_Locations.l_15_4);
		state.p_Connected.set(E_Locations.l_8_4, E_Locations.l_7_4);
		state.p_Connected.set(E_Locations.l_5_2, E_Locations.l_5_3);
		state.p_Connected.set(E_Locations.l_13_3, E_Locations.l_13_4);
		state.p_Connected.set(E_Locations.l_10_3, E_Locations.l_9_3);
		state.p_Connected.set(E_Locations.l_13_5, E_Locations.l_14_5);
		state.p_Connected.set(E_Locations.l_9_7, E_Locations.l_10_7);
		state.p_Connected.set(E_Locations.l_13_1, E_Locations.l_13_2);
		state.p_Connected.set(E_Locations.l_3_10, E_Locations.l_3_9);
		state.p_Connected.set(E_Locations.l_13_6, E_Locations.l_13_7);
		state.p_Connected.set(E_Locations.l_13_9, E_Locations.l_14_9);
		state.p_Connected.set(E_Locations.l_1_4, E_Locations.l_1_3);
		state.p_Connected.set(E_Locations.l_5_6, E_Locations.l_5_5);
		state.p_Connected.set(E_Locations.l_6_13, E_Locations.l_6_12);
		state.p_Connected.set(E_Locations.l_14_15, E_Locations.l_13_15);
		state.p_Connected.set(E_Locations.l_6_4, E_Locations.l_7_4);
		state.p_Connected.set(E_Locations.l_10_2, E_Locations.l_9_2);
		state.p_Connected.set(E_Locations.l_5_12, E_Locations.l_4_12);
		state.p_Connected.set(E_Locations.l_1_2, E_Locations.l_2_2);
		state.p_Connected.set(E_Locations.l_8_8, E_Locations.l_8_7);
		state.p_Connected.set(E_Locations.l_14_3, E_Locations.l_15_3);
		state.p_Connected.set(E_Locations.l_13_1, E_Locations.l_14_1);
		state.p_Connected.set(E_Locations.l_14_3, E_Locations.l_13_3);
		state.p_Connected.set(E_Locations.l_10_7, E_Locations.l_9_7);
		state.p_Connected.set(E_Locations.l_13_13, E_Locations.l_12_13);
		state.p_Connected.set(E_Locations.l_15_14, E_Locations.l_14_14);
		state.p_Connected.set(E_Locations.l_7_13, E_Locations.l_6_13);
		state.p_Connected.set(E_Locations.l_8_14, E_Locations.l_8_15);
		state.p_Connected.set(E_Locations.l_6_5, E_Locations.l_5_5);
		state.p_Connected.set(E_Locations.l_14_10, E_Locations.l_13_10);
		state.p_Connected.set(E_Locations.l_7_2, E_Locations.l_8_2);
		state.p_Connected.set(E_Locations.l_3_15, E_Locations.l_4_15);
		state.p_Connected.set(E_Locations.l_5_4, E_Locations.l_5_5);
		state.p_Connected.set(E_Locations.l_6_1, E_Locations.l_6_2);
		state.p_Connected.set(E_Locations.l_7_12, E_Locations.l_7_11);
		state.p_Connected.set(E_Locations.l_15_7, E_Locations.l_15_6);
		state.p_Connected.set(E_Locations.l_13_5, E_Locations.l_13_4);
		state.p_Connected.set(E_Locations.l_6_6, E_Locations.l_5_6);
		state.p_Connected.set(E_Locations.l_12_4, E_Locations.l_12_5);
		state.p_Connected.set(E_Locations.l_12_6, E_Locations.l_12_7);
		state.p_Connected.set(E_Locations.l_4_6, E_Locations.l_4_5);
		state.p_Connected.set(E_Locations.l_9_3, E_Locations.l_9_4);
		state.p_Connected.set(E_Locations.l_8_10, E_Locations.l_7_10);
		state.p_Connected.set(E_Locations.l_12_4, E_Locations.l_11_4);
		state.p_Connected.set(E_Locations.l_14_11, E_Locations.l_15_11);
		state.p_Connected.set(E_Locations.l_3_1, E_Locations.l_2_1);
		state.p_Connected.set(E_Locations.l_6_14, E_Locations.l_6_15);
		state.p_Connected.set(E_Locations.l_8_5, E_Locations.l_9_5);
		state.p_Connected.set(E_Locations.l_9_4, E_Locations.l_9_3);
		state.p_Connected.set(E_Locations.l_8_14, E_Locations.l_8_13);
		state.p_Connected.set(E_Locations.l_14_6, E_Locations.l_13_6);
		state.p_Connected.set(E_Locations.l_4_10, E_Locations.l_4_11);
		state.p_Connected.set(E_Locations.l_11_14, E_Locations.l_10_14);
		state.p_Connected.set(E_Locations.l_4_4, E_Locations.l_4_5);
		state.p_Connected.set(E_Locations.l_7_6, E_Locations.l_6_6);
		state.p_Connected.set(E_Locations.l_9_2, E_Locations.l_10_2);
		state.p_Connected.set(E_Locations.l_9_3, E_Locations.l_8_3);
		state.p_Connected.set(E_Locations.l_6_11, E_Locations.l_6_12);
		state.p_Connected.set(E_Locations.l_9_5, E_Locations.l_8_5);
		state.p_Connected.set(E_Locations.l_12_5, E_Locations.l_12_6);
		state.p_Connected.set(E_Locations.l_5_10, E_Locations.l_5_9);
		state.p_Connected.set(E_Locations.l_7_1, E_Locations.l_7_2);
		state.p_Connected.set(E_Locations.l_6_6, E_Locations.l_7_6);
		state.p_Connected.set(E_Locations.l_2_11, E_Locations.l_2_10);
		state.p_Connected.set(E_Locations.l_10_15, E_Locations.l_9_15);
		state.p_Connected.set(E_Locations.l_2_4, E_Locations.l_1_4);
		state.p_Connected.set(E_Locations.l_11_15, E_Locations.l_12_15);
		state.p_Connected.set(E_Locations.l_1_10, E_Locations.l_1_9);
		state.p_Connected.set(E_Locations.l_8_2, E_Locations.l_8_1);
		state.p_Connected.set(E_Locations.l_4_8, E_Locations.l_4_9);
		state.p_Connected.set(E_Locations.l_11_10, E_Locations.l_11_11);
		state.p_Connected.set(E_Locations.l_7_9, E_Locations.l_7_8);
		state.p_Connected.set(E_Locations.l_1_9, E_Locations.l_2_9);
		state.p_Connected.set(E_Locations.l_1_13, E_Locations.l_1_14);
		state.p_Connected.set(E_Locations.l_9_13, E_Locations.l_8_13);
		state.p_Connected.set(E_Locations.l_8_14, E_Locations.l_9_14);
		state.p_Connected.set(E_Locations.l_12_1, E_Locations.l_11_1);
		state.p_Connected.set(E_Locations.l_8_10, E_Locations.l_8_11);
		state.p_Connected.set(E_Locations.l_10_13, E_Locations.l_9_13);
		state.p_Connected.set(E_Locations.l_12_11, E_Locations.l_12_12);
		state.p_Connected.set(E_Locations.l_14_14, E_Locations.l_13_14);
		state.p_Connected.set(E_Locations.l_5_11, E_Locations.l_6_11);
		state.p_Connected.set(E_Locations.l_10_6, E_Locations.l_10_7);
		state.p_Connected.set(E_Locations.l_8_15, E_Locations.l_7_15);
		state.p_Connected.set(E_Locations.l_9_9, E_Locations.l_8_9);
		state.p_Connected.set(E_Locations.l_7_14, E_Locations.l_8_14);
		state.p_Connected.set(E_Locations.l_8_12, E_Locations.l_7_12);
		state.p_Connected.set(E_Locations.l_2_15, E_Locations.l_1_15);
		state.p_Connected.set(E_Locations.l_9_3, E_Locations.l_10_3);
		state.p_Connected.set(E_Locations.l_6_6, E_Locations.l_6_5);
		state.p_Connected.set(E_Locations.l_12_4, E_Locations.l_13_4);
		state.p_Connected.set(E_Locations.l_2_8, E_Locations.l_1_8);
		state.p_Connected.set(E_Locations.l_13_8, E_Locations.l_13_7);
		state.p_Connected.set(E_Locations.l_2_15, E_Locations.l_2_14);
		state.p_Connected.set(E_Locations.l_3_12, E_Locations.l_3_11);
		state.p_Connected.set(E_Locations.l_2_11, E_Locations.l_3_11);
		state.p_Connected.set(E_Locations.l_9_14, E_Locations.l_9_13);
		state.p_Connected.set(E_Locations.l_4_8, E_Locations.l_5_8);
		state.p_Connected.set(E_Locations.l_8_11, E_Locations.l_7_11);
		state.p_Connected.set(E_Locations.l_2_13, E_Locations.l_2_14);
		state.p_Connected.set(E_Locations.l_4_14, E_Locations.l_3_14);
		state.p_Connected.set(E_Locations.l_3_10, E_Locations.l_4_10);
		state.p_Connected.set(E_Locations.l_13_7, E_Locations.l_13_6);
		state.p_Connected.set(E_Locations.l_14_8, E_Locations.l_14_9);
		state.p_Connected.set(E_Locations.l_3_6, E_Locations.l_3_7);
		state.p_Connected.set(E_Locations.l_1_7, E_Locations.l_1_6);
		state.p_Connected.set(E_Locations.l_10_5, E_Locations.l_9_5);
		state.p_Connected.set(E_Locations.l_3_14, E_Locations.l_2_14);
		state.p_Connected.set(E_Locations.l_8_1, E_Locations.l_8_2);
		state.p_Connected.set(E_Locations.l_1_5, E_Locations.l_1_4);
		state.p_Connected.set(E_Locations.l_14_12, E_Locations.l_15_12);
		state.p_Connected.set(E_Locations.l_6_12, E_Locations.l_5_12);
		state.p_Connected.set(E_Locations.l_15_13, E_Locations.l_15_12);
		state.p_Connected.set(E_Locations.l_7_10, E_Locations.l_6_10);
		state.p_Connected.set(E_Locations.l_8_2, E_Locations.l_8_3);
		state.p_Connected.set(E_Locations.l_7_15, E_Locations.l_8_15);
		state.p_Connected.set(E_Locations.l_9_2, E_Locations.l_9_3);
		state.p_Connected.set(E_Locations.l_12_3, E_Locations.l_13_3);
		state.p_Connected.set(E_Locations.l_13_5, E_Locations.l_12_5);
		state.p_Connected.set(E_Locations.l_9_7, E_Locations.l_8_7);
		state.p_Connected.set(E_Locations.l_10_1, E_Locations.l_10_2);
		state.p_Connected.set(E_Locations.l_13_8, E_Locations.l_12_8);
		state.p_Connected.set(E_Locations.l_5_7, E_Locations.l_6_7);
		state.p_Connected.set(E_Locations.l_6_5, E_Locations.l_7_5);
		state.p_Connected.set(E_Locations.l_10_14, E_Locations.l_11_14);
		state.p_Connected.set(E_Locations.l_6_14, E_Locations.l_7_14);
		state.p_Connected.set(E_Locations.l_4_15, E_Locations.l_5_15);
		state.p_Connected.set(E_Locations.l_6_10, E_Locations.l_6_11);
		state.p_Connected.set(E_Locations.l_10_5, E_Locations.l_10_6);
		state.p_Connected.set(E_Locations.l_11_1, E_Locations.l_11_2);
		state.p_Connected.set(E_Locations.l_11_5, E_Locations.l_11_6);
		state.p_Connected.set(E_Locations.l_11_12, E_Locations.l_11_13);
		state.p_Connected.set(E_Locations.l_4_8, E_Locations.l_4_7);
		state.p_Connected.set(E_Locations.l_8_6, E_Locations.l_7_6);
		state.p_Connected.set(E_Locations.l_6_4, E_Locations.l_5_4);
		state.p_Connected.set(E_Locations.l_3_9, E_Locations.l_4_9);
		state.p_Connected.set(E_Locations.l_12_2, E_Locations.l_12_3);
		state.p_Connected.set(E_Locations.l_9_1, E_Locations.l_8_1);
		state.p_Connected.set(E_Locations.l_9_6, E_Locations.l_10_6);
		state.p_Connected.set(E_Locations.l_10_12, E_Locations.l_11_12);
		state.p_Connected.set(E_Locations.l_5_10, E_Locations.l_4_10);
		state.p_Connected.set(E_Locations.l_2_1, E_Locations.l_1_1);
		state.p_Connected.set(E_Locations.l_4_6, E_Locations.l_5_6);
		state.p_Connected.set(E_Locations.l_6_2, E_Locations.l_5_2);
		state.p_Connected.set(E_Locations.l_10_5, E_Locations.l_11_5);
		state.p_Connected.set(E_Locations.l_5_8, E_Locations.l_6_8);
		state.p_Connected.set(E_Locations.l_3_12, E_Locations.l_2_12);
		state.p_Connected.set(E_Locations.l_12_5, E_Locations.l_13_5);
		state.p_Connected.set(E_Locations.l_12_10, E_Locations.l_13_10);
		state.p_Connected.set(E_Locations.l_4_3, E_Locations.l_4_4);
		state.p_Connected.set(E_Locations.l_1_1, E_Locations.l_2_1);
		state.p_Connected.set(E_Locations.l_4_12, E_Locations.l_4_13);
		state.p_Connected.set(E_Locations.l_14_4, E_Locations.l_14_5);
		state.p_Connected.set(E_Locations.l_15_11, E_Locations.l_15_12);
		state.p_Connected.set(E_Locations.l_2_9, E_Locations.l_2_8);
		state.p_Connected.set(E_Locations.l_12_11, E_Locations.l_11_11);
		state.p_Connected.set(E_Locations.l_13_15, E_Locations.l_14_15);
		state.p_Connected.set(E_Locations.l_10_9, E_Locations.l_10_10);
		state.p_Connected.set(E_Locations.l_10_10, E_Locations.l_10_9);
		state.p_Connected.set(E_Locations.l_14_11, E_Locations.l_13_11);
		state.p_Connected.set(E_Locations.l_15_3, E_Locations.l_14_3);
		state.p_Connected.set(E_Locations.l_13_8, E_Locations.l_13_9);
		state.p_Connected.set(E_Locations.l_3_5, E_Locations.l_2_5);
		state.p_Connected.set(E_Locations.l_5_11, E_Locations.l_4_11);
		state.p_Connected.set(E_Locations.l_7_7, E_Locations.l_7_6);
		state.p_Connected.set(E_Locations.l_12_9, E_Locations.l_11_9);
		state.p_Connected.set(E_Locations.l_7_15, E_Locations.l_6_15);
		state.p_Connected.set(E_Locations.l_10_12, E_Locations.l_10_13);
		state.p_Connected.set(E_Locations.l_12_2, E_Locations.l_13_2);
		state.p_Connected.set(E_Locations.l_10_11, E_Locations.l_9_11);
		state.p_Connected.set(E_Locations.l_14_7, E_Locations.l_14_8);
		state.p_Connected.set(E_Locations.l_6_7, E_Locations.l_5_7);
		state.p_Connected.set(E_Locations.l_11_11, E_Locations.l_10_11);
		state.p_Connected.set(E_Locations.l_2_11, E_Locations.l_2_12);
		state.p_Connected.set(E_Locations.l_5_12, E_Locations.l_6_12);
		state.p_Connected.set(E_Locations.l_14_5, E_Locations.l_14_4);
		state.p_Connected.set(E_Locations.l_14_15, E_Locations.l_14_14);
		state.p_Connected.set(E_Locations.l_6_2, E_Locations.l_6_3);
		state.p_Connected.set(E_Locations.l_11_13, E_Locations.l_11_12);
		state.p_Connected.set(E_Locations.l_5_15, E_Locations.l_6_15);
		state.p_Connected.set(E_Locations.l_8_14, E_Locations.l_7_14);
		state.p_Connected.set(E_Locations.l_13_4, E_Locations.l_13_5);
		state.p_Connected.set(E_Locations.l_2_5, E_Locations.l_1_5);
		state.p_Connected.set(E_Locations.l_9_8, E_Locations.l_10_8);
		state.p_Connected.set(E_Locations.l_7_12, E_Locations.l_7_13);
		state.p_Connected.set(E_Locations.l_3_13, E_Locations.l_2_13);
		state.p_Connected.set(E_Locations.l_4_14, E_Locations.l_4_13);
		state.p_Connected.set(E_Locations.l_15_7, E_Locations.l_14_7);
		state.p_Connected.set(E_Locations.l_1_14, E_Locations.l_1_15);
		state.p_Connected.set(E_Locations.l_4_13, E_Locations.l_4_12);
		state.p_Connected.set(E_Locations.l_11_14, E_Locations.l_11_15);
		state.p_Connected.set(E_Locations.l_3_4, E_Locations.l_3_5);
		state.p_Connected.set(E_Locations.l_14_12, E_Locations.l_14_13);
		state.p_Connected.set(E_Locations.l_11_14, E_Locations.l_12_14);
		state.p_Connected.set(E_Locations.l_4_2, E_Locations.l_4_1);
		state.p_Connected.set(E_Locations.l_11_7, E_Locations.l_12_7);
		state.p_Connected.set(E_Locations.l_8_12, E_Locations.l_8_13);
		state.p_Connected.set(E_Locations.l_15_5, E_Locations.l_14_5);
		state.p_Connected.set(E_Locations.l_1_8, E_Locations.l_1_7);
		state.p_Connected.set(E_Locations.l_4_15, E_Locations.l_4_14);
		state.p_Connected.set(E_Locations.l_7_1, E_Locations.l_8_1);
		state.p_Connected.set(E_Locations.l_8_9, E_Locations.l_8_8);
		state.p_Connected.set(E_Locations.l_1_11, E_Locations.l_1_12);
		state.p_Connected.set(E_Locations.l_6_9, E_Locations.l_7_9);
		state.p_Connected.set(E_Locations.l_9_2, E_Locations.l_9_1);
		state.p_Connected.set(E_Locations.l_11_9, E_Locations.l_11_8);
		state.p_Connected.set(E_Locations.l_13_3, E_Locations.l_12_3);
		state.p_Connected.set(E_Locations.l_15_13, E_Locations.l_14_13);
		state.p_Connected.set(E_Locations.l_3_14, E_Locations.l_3_15);
		state.p_Connected.set(E_Locations.l_5_3, E_Locations.l_4_3);
		state.p_Connected.set(E_Locations.l_12_7, E_Locations.l_12_8);
		state.p_Connected.set(E_Locations.l_11_8, E_Locations.l_11_7);
		state.p_Connected.set(E_Locations.l_2_4, E_Locations.l_2_5);
		state.p_Connected.set(E_Locations.l_8_7, E_Locations.l_9_7);
		state.p_Connected.set(E_Locations.l_4_2, E_Locations.l_3_2);
		state.p_Connected.set(E_Locations.l_14_2, E_Locations.l_13_2);
		state.p_Connected.set(E_Locations.l_4_11, E_Locations.l_4_12);
		state.p_Connected.set(E_Locations.l_15_12, E_Locations.l_15_11);
		state.p_Connected.set(E_Locations.l_9_15, E_Locations.l_8_15);
		state.p_Connected.set(E_Locations.l_14_3, E_Locations.l_14_4);
		state.p_Connected.set(E_Locations.l_2_7, E_Locations.l_2_8);
		state.p_Connected.set(E_Locations.l_6_3, E_Locations.l_7_3);
		state.p_Connected.set(E_Locations.l_1_2, E_Locations.l_1_1);
		state.p_Connected.set(E_Locations.l_9_12, E_Locations.l_9_13);
		state.p_Connected.set(E_Locations.l_15_8, E_Locations.l_14_8);
		state.p_Connected.set(E_Locations.l_3_3, E_Locations.l_3_2);
		state.p_Connected.set(E_Locations.l_10_5, E_Locations.l_10_4);
		state.p_Connected.set(E_Locations.l_6_3, E_Locations.l_5_3);
		state.p_Connected.set(E_Locations.l_8_10, E_Locations.l_8_9);
		state.p_Connected.set(E_Locations.l_6_15, E_Locations.l_5_15);
		state.p_Connected.set(E_Locations.l_1_6, E_Locations.l_1_7);
		state.p_Connected.set(E_Locations.l_9_11, E_Locations.l_10_11);
		state.p_Connected.set(E_Locations.l_15_12, E_Locations.l_15_13);
		state.p_Connected.set(E_Locations.l_9_9, E_Locations.l_9_8);
		state.p_Connected.set(E_Locations.l_13_10, E_Locations.l_14_10);
		state.p_Connected.set(E_Locations.l_4_10, E_Locations.l_5_10);
		state.p_Connected.set(E_Locations.l_7_4, E_Locations.l_6_4);
		state.p_Connected.set(E_Locations.l_12_1, E_Locations.l_12_2);
		state.p_Connected.set(E_Locations.l_3_15, E_Locations.l_2_15);
		state.p_Connected.set(E_Locations.l_1_3, E_Locations.l_2_3);
		state.p_Connected.set(E_Locations.l_13_14, E_Locations.l_12_14);
		state.p_Connected.set(E_Locations.l_2_14, E_Locations.l_2_15);
		state.p_Connected.set(E_Locations.l_5_2, E_Locations.l_4_2);
		state.p_Connected.set(E_Locations.l_9_11, E_Locations.l_9_12);
		state.p_Connected.set(E_Locations.l_9_12, E_Locations.l_9_11);
		state.p_Connected.set(E_Locations.l_10_6, E_Locations.l_10_5);
		state.p_Connected.set(E_Locations.l_1_7, E_Locations.l_2_7);
		state.p_Connected.set(E_Locations.l_10_13, E_Locations.l_11_13);
		state.p_Connected.set(E_Locations.l_6_2, E_Locations.l_7_2);
		state.p_Connected.set(E_Locations.l_2_8, E_Locations.l_2_9);
		state.p_Connected.set(E_Locations.l_8_9, E_Locations.l_9_9);
		state.p_Connected.set(E_Locations.l_2_6, E_Locations.l_3_6);
		state.p_Connected.set(E_Locations.l_5_14, E_Locations.l_4_14);
		state.p_Connected.set(E_Locations.l_13_9, E_Locations.l_13_8);
		state.p_Connected.set(E_Locations.l_5_13, E_Locations.l_5_14);
		state.p_Connected.set(E_Locations.l_10_1, E_Locations.l_9_1);
		state.p_Connected.set(E_Locations.l_13_15, E_Locations.l_12_15);
		state.p_Connected.set(E_Locations.l_10_7, E_Locations.l_11_7);
		state.p_Connected.set(E_Locations.l_6_6, E_Locations.l_6_7);
		state.p_Connected.set(E_Locations.l_1_3, E_Locations.l_1_2);
		state.p_Connected.set(E_Locations.l_4_3, E_Locations.l_4_2);
		state.p_Connected.set(E_Locations.l_14_13, E_Locations.l_14_12);
		state.p_Connected.set(E_Locations.l_3_14, E_Locations.l_3_13);
		state.p_Connected.set(E_Locations.l_11_2, E_Locations.l_11_3);
		state.p_Connected.set(E_Locations.l_11_10, E_Locations.l_12_10);
		state.p_Connected.set(E_Locations.l_9_7, E_Locations.l_9_8);
		state.p_Connected.set(E_Locations.l_15_9, E_Locations.l_14_9);
		state.p_Connected.set(E_Locations.l_8_15, E_Locations.l_8_14);
		state.p_Connected.set(E_Locations.l_11_11, E_Locations.l_11_10);
		state.p_Connected.set(E_Locations.l_12_9, E_Locations.l_12_10);
		state.p_Connected.set(E_Locations.l_3_11, E_Locations.l_4_11);
		state.p_Connected.set(E_Locations.l_5_6, E_Locations.l_5_7);
		state.p_Connected.set(E_Locations.l_13_12, E_Locations.l_13_13);
		state.p_Connected.set(E_Locations.l_1_12, E_Locations.l_1_13);
		state.p_Connected.set(E_Locations.l_8_7, E_Locations.l_8_6);
		state.p_Connected.set(E_Locations.l_15_1, E_Locations.l_14_1);
		state.p_Connected.set(E_Locations.l_4_6, E_Locations.l_4_7);
		state.p_Connected.set(E_Locations.l_5_9, E_Locations.l_4_9);
		state.p_Connected.set(E_Locations.l_15_7, E_Locations.l_15_8);
		state.p_Connected.set(E_Locations.l_3_6, E_Locations.l_2_6);
		state.p_Connected.set(E_Locations.l_15_5, E_Locations.l_15_6);
		state.p_Connected.set(E_Locations.l_4_4, E_Locations.l_4_3);
		state.p_Connected.set(E_Locations.l_9_14, E_Locations.l_10_14);
		state.p_Connected.set(E_Locations.l_5_1, E_Locations.l_4_1);
		state.p_Connected.set(E_Locations.l_2_12, E_Locations.l_2_11);
		state.p_Connected.set(E_Locations.l_2_12, E_Locations.l_1_12);
		state.p_Connected.set(E_Locations.l_13_3, E_Locations.l_13_2);
		state.p_Connected.set(E_Locations.l_4_4, E_Locations.l_5_4);
		state.p_Connected.set(E_Locations.l_5_5, E_Locations.l_5_4);
		state.p_Connected.set(E_Locations.l_11_13, E_Locations.l_11_14);
		state.p_Connected.set(E_Locations.l_2_12, E_Locations.l_2_13);
		state.p_Connected.set(E_Locations.l_4_8, E_Locations.l_3_8);
		state.p_Connected.set(E_Locations.l_15_4, E_Locations.l_14_4);
		state.p_Connected.set(E_Locations.l_12_8, E_Locations.l_11_8);
		state.p_Connected.set(E_Locations.l_1_1, E_Locations.l_1_2);
		state.p_Connected.set(E_Locations.l_6_7, E_Locations.l_7_7);
		state.p_Connected.set(E_Locations.l_7_6, E_Locations.l_7_5);
		state.p_Connected.set(E_Locations.l_7_4, E_Locations.l_7_5);
		state.p_Connected.set(E_Locations.l_8_2, E_Locations.l_7_2);
		state.p_Connected.set(E_Locations.l_14_4, E_Locations.l_14_3);
		state.p_Connected.set(E_Locations.l_4_13, E_Locations.l_5_13);
		state.p_Connected.set(E_Locations.l_8_2, E_Locations.l_9_2);
		state.p_Connected.set(E_Locations.l_8_5, E_Locations.l_8_6);
		state.p_Connected.set(E_Locations.l_1_2, E_Locations.l_1_3);
		state.p_Connected.set(E_Locations.l_9_4, E_Locations.l_8_4);
		state.p_Connected.set(E_Locations.l_10_6, E_Locations.l_11_6);
		state.p_Connected.set(E_Locations.l_11_12, E_Locations.l_12_12);
		state.p_Connected.set(E_Locations.l_5_3, E_Locations.l_5_2);
		state.p_Connected.set(E_Locations.l_5_4, E_Locations.l_6_4);
		state.p_Connected.set(E_Locations.l_8_7, E_Locations.l_7_7);
		state.p_Connected.set(E_Locations.l_2_8, E_Locations.l_2_7);
		state.p_Connected.set(E_Locations.l_9_10, E_Locations.l_8_10);
		state.p_Connected.set(E_Locations.l_10_2, E_Locations.l_11_2);
		state.p_Connected.set(E_Locations.l_8_3, E_Locations.l_7_3);
		state.p_Connected.set(E_Locations.l_8_13, E_Locations.l_8_12);
		state.p_Connected.set(E_Locations.l_1_9, E_Locations.l_1_10);
		state.p_Connected.set(E_Locations.l_1_15, E_Locations.l_2_15);
		state.p_Connected.set(E_Locations.l_14_14, E_Locations.l_15_14);
		state.p_Connected.set(E_Locations.l_7_8, E_Locations.l_7_7);
		state.p_Connected.set(E_Locations.l_9_9, E_Locations.l_10_9);
		state.p_Connected.set(E_Locations.l_5_9, E_Locations.l_5_8);
		state.p_Connected.set(E_Locations.l_9_5, E_Locations.l_9_4);
		state.p_Connected.set(E_Locations.l_12_10, E_Locations.l_12_9);
		state.p_Connected.set(E_Locations.l_3_4, E_Locations.l_2_4);
		state.p_Connected.set(E_Locations.l_15_8, E_Locations.l_15_9);
		state.p_Connected.set(E_Locations.l_3_13, E_Locations.l_4_13);
		state.p_Connected.set(E_Locations.l_8_9, E_Locations.l_7_9);
		state.p_Connected.set(E_Locations.l_15_10, E_Locations.l_15_11);
		state.p_Connected.set(E_Locations.l_6_5, E_Locations.l_6_4);
		state.p_Connected.set(E_Locations.l_10_13, E_Locations.l_10_14);
		state.p_Connected.set(E_Locations.l_7_11, E_Locations.l_7_12);
		state.p_Connected.set(E_Locations.l_6_13, E_Locations.l_6_14);
		state.p_Connected.set(E_Locations.l_3_7, E_Locations.l_4_7);
		state.p_Connected.set(E_Locations.l_15_6, E_Locations.l_15_5);
		

		state.p_Accessible.set(E_Locations.l_8_5);
		state.p_Accessible.set(E_Locations.l_13_7);
		state.p_Accessible.set(E_Locations.l_12_11);
		state.p_Accessible.set(E_Locations.l_2_6);
		state.p_Accessible.set(E_Locations.l_1_5);
		state.p_Accessible.set(E_Locations.l_7_4);
		state.p_Accessible.set(E_Locations.l_9_7);
		state.p_Accessible.set(E_Locations.l_5_3);
		state.p_Accessible.set(E_Locations.l_7_13);
		state.p_Accessible.set(E_Locations.l_6_2);
		state.p_Accessible.set(E_Locations.l_2_2);
		state.p_Accessible.set(E_Locations.l_15_2);
		state.p_Accessible.set(E_Locations.l_12_1);
		state.p_Accessible.set(E_Locations.l_7_12);
		state.p_Accessible.set(E_Locations.l_14_13);
		state.p_Accessible.set(E_Locations.l_3_12);
		state.p_Accessible.set(E_Locations.l_9_3);
		state.p_Accessible.set(E_Locations.l_5_1);
		state.p_Accessible.set(E_Locations.l_5_2);
		state.p_Accessible.set(E_Locations.l_14_2);
		state.p_Accessible.set(E_Locations.l_6_14);
		state.p_Accessible.set(E_Locations.l_9_2);
		state.p_Accessible.set(E_Locations.l_8_9);
		state.p_Accessible.set(E_Locations.l_10_6);
		state.p_Accessible.set(E_Locations.l_5_6);
		state.p_Accessible.set(E_Locations.l_8_4);
		state.p_Accessible.set(E_Locations.l_5_9);
		state.p_Accessible.set(E_Locations.l_10_4);
		state.p_Accessible.set(E_Locations.l_9_14);
		state.p_Accessible.set(E_Locations.l_15_10);
		state.p_Accessible.set(E_Locations.l_3_13);
		state.p_Accessible.set(E_Locations.l_13_9);
		state.p_Accessible.set(E_Locations.l_15_6);
		state.p_Accessible.set(E_Locations.l_2_14);
		state.p_Accessible.set(E_Locations.l_9_12);
		state.p_Accessible.set(E_Locations.l_15_12);
		state.p_Accessible.set(E_Locations.l_14_15);
		state.p_Accessible.set(E_Locations.l_14_11);
		state.p_Accessible.set(E_Locations.l_9_8);
		state.p_Accessible.set(E_Locations.l_3_4);
		state.p_Accessible.set(E_Locations.l_15_5);
		state.p_Accessible.set(E_Locations.l_10_11);
		state.p_Accessible.set(E_Locations.l_13_1);
		state.p_Accessible.set(E_Locations.l_4_13);
		state.p_Accessible.set(E_Locations.l_3_6);
		state.p_Accessible.set(E_Locations.l_12_10);
		state.p_Accessible.set(E_Locations.l_3_1);
		state.p_Accessible.set(E_Locations.l_8_15);
		state.p_Accessible.set(E_Locations.l_3_2);
		state.p_Accessible.set(E_Locations.l_12_8);
		state.p_Accessible.set(E_Locations.l_8_14);
		state.p_Accessible.set(E_Locations.l_6_4);
		state.p_Accessible.set(E_Locations.l_1_11);
		state.p_Accessible.set(E_Locations.l_6_1);
		state.p_Accessible.set(E_Locations.l_13_6);
		state.p_Accessible.set(E_Locations.l_14_14);
		state.p_Accessible.set(E_Locations.l_2_4);
		state.p_Accessible.set(E_Locations.l_3_5);
		state.p_Accessible.set(E_Locations.l_13_11);
		state.p_Accessible.set(E_Locations.l_3_8);
		state.p_Accessible.set(E_Locations.l_8_10);
		state.p_Accessible.set(E_Locations.l_11_13);
		state.p_Accessible.set(E_Locations.l_15_8);
		state.p_Accessible.set(E_Locations.l_10_10);
		state.p_Accessible.set(E_Locations.l_7_1);
		state.p_Accessible.set(E_Locations.l_14_9);
		state.p_Accessible.set(E_Locations.l_15_9);
		state.p_Accessible.set(E_Locations.l_3_3);
		state.p_Accessible.set(E_Locations.l_9_11);
		state.p_Accessible.set(E_Locations.l_2_7);
		state.p_Accessible.set(E_Locations.l_5_5);
		state.p_Accessible.set(E_Locations.l_10_15);
		state.p_Accessible.set(E_Locations.l_15_11);
		state.p_Accessible.set(E_Locations.l_13_5);
		state.p_Accessible.set(E_Locations.l_8_7);
		state.p_Accessible.set(E_Locations.l_9_1);
		state.p_Accessible.set(E_Locations.l_2_3);
		state.p_Accessible.set(E_Locations.l_1_2);
		state.p_Accessible.set(E_Locations.l_10_8);
		state.p_Accessible.set(E_Locations.l_9_4);
		state.p_Accessible.set(E_Locations.l_12_12);
		state.p_Accessible.set(E_Locations.l_8_1);
		state.p_Accessible.set(E_Locations.l_10_5);
		state.p_Accessible.set(E_Locations.l_1_1);
		state.p_Accessible.set(E_Locations.l_2_5);
		state.p_Accessible.set(E_Locations.l_3_14);
		state.p_Accessible.set(E_Locations.l_11_15);
		state.p_Accessible.set(E_Locations.l_8_3);
		state.p_Accessible.set(E_Locations.l_10_3);
		state.p_Accessible.set(E_Locations.l_15_7);
		state.p_Accessible.set(E_Locations.l_10_14);
		state.p_Accessible.set(E_Locations.l_10_1);
		state.p_Accessible.set(E_Locations.l_1_10);
		state.p_Accessible.set(E_Locations.l_6_7);
		state.p_Accessible.set(E_Locations.l_6_11);
		state.p_Accessible.set(E_Locations.l_4_1);
		state.p_Accessible.set(E_Locations.l_12_3);
		state.p_Accessible.set(E_Locations.l_9_5);
		state.p_Accessible.set(E_Locations.l_6_6);
		state.p_Accessible.set(E_Locations.l_5_13);
		state.p_Accessible.set(E_Locations.l_13_10);
		state.p_Accessible.set(E_Locations.l_7_10);
		state.p_Accessible.set(E_Locations.l_3_11);
		state.p_Accessible.set(E_Locations.l_14_6);
		state.p_Accessible.set(E_Locations.l_4_12);
		state.p_Accessible.set(E_Locations.l_6_10);
		state.p_Accessible.set(E_Locations.l_2_11);
		state.p_Accessible.set(E_Locations.l_11_4);
		state.p_Accessible.set(E_Locations.l_13_13);
		state.p_Accessible.set(E_Locations.l_1_6);
		state.p_Accessible.set(E_Locations.l_12_14);
		state.p_Accessible.set(E_Locations.l_14_10);
		state.p_Accessible.set(E_Locations.l_9_15);
		state.p_Accessible.set(E_Locations.l_10_2);
		state.p_Accessible.set(E_Locations.l_14_3);
		state.p_Accessible.set(E_Locations.l_3_9);
		state.p_Accessible.set(E_Locations.l_7_7);
		state.p_Accessible.set(E_Locations.l_9_10);
		state.p_Accessible.set(E_Locations.l_11_6);
		state.p_Accessible.set(E_Locations.l_15_13);
		state.p_Accessible.set(E_Locations.l_12_2);
		state.p_Accessible.set(E_Locations.l_6_3);
		state.p_Accessible.set(E_Locations.l_4_9);
		state.p_Accessible.set(E_Locations.l_7_9);
		state.p_Accessible.set(E_Locations.l_13_12);
		state.p_Accessible.set(E_Locations.l_8_12);
		state.p_Accessible.set(E_Locations.l_4_4);
		state.p_Accessible.set(E_Locations.l_8_6);
		state.p_Accessible.set(E_Locations.l_2_8);
		state.p_Accessible.set(E_Locations.l_11_7);
		state.p_Accessible.set(E_Locations.l_5_8);
		state.p_Accessible.set(E_Locations.l_6_15);
		state.p_Accessible.set(E_Locations.l_4_7);
		state.p_Accessible.set(E_Locations.l_3_15);
		state.p_Accessible.set(E_Locations.l_1_3);
		state.p_Accessible.set(E_Locations.l_4_8);
		state.p_Accessible.set(E_Locations.l_7_2);
		state.p_Accessible.set(E_Locations.l_11_9);
		state.p_Accessible.set(E_Locations.l_15_15);
		state.p_Accessible.set(E_Locations.l_2_10);
		state.p_Accessible.set(E_Locations.l_3_7);
		state.p_Accessible.set(E_Locations.l_2_13);
		state.p_Accessible.set(E_Locations.l_13_15);
		state.p_Accessible.set(E_Locations.l_7_5);
		state.p_Accessible.set(E_Locations.l_8_11);
		state.p_Accessible.set(E_Locations.l_13_8);
		state.p_Accessible.set(E_Locations.l_9_9);
		state.p_Accessible.set(E_Locations.l_11_11);
		state.p_Accessible.set(E_Locations.l_8_8);
		state.p_Accessible.set(E_Locations.l_5_10);
		state.p_Accessible.set(E_Locations.l_15_14);
		state.p_Accessible.set(E_Locations.l_15_4);
		state.p_Accessible.set(E_Locations.l_1_12);
		state.p_Accessible.set(E_Locations.l_3_10);
		state.p_Accessible.set(E_Locations.l_6_5);
		state.p_Accessible.set(E_Locations.l_14_5);
		state.p_Accessible.set(E_Locations.l_13_14);
		state.p_Accessible.set(E_Locations.l_1_4);
		state.p_Accessible.set(E_Locations.l_7_15);
		state.p_Accessible.set(E_Locations.l_1_14);
		state.p_Accessible.set(E_Locations.l_2_1);
		state.p_Accessible.set(E_Locations.l_6_8);
		state.p_Accessible.set(E_Locations.l_4_15);
		state.p_Accessible.set(E_Locations.l_5_15);
		state.p_Accessible.set(E_Locations.l_8_13);
		state.p_Accessible.set(E_Locations.l_8_2);
		state.p_Accessible.set(E_Locations.l_1_15);
		state.p_Accessible.set(E_Locations.l_7_14);
		state.p_Accessible.set(E_Locations.l_11_1);
		state.p_Accessible.set(E_Locations.l_12_13);
		state.p_Accessible.set(E_Locations.l_14_12);
		state.p_Accessible.set(E_Locations.l_12_15);
		state.p_Accessible.set(E_Locations.l_7_11);
		state.p_Accessible.set(E_Locations.l_4_11);
		state.p_Accessible.set(E_Locations.l_15_3);
		state.p_Accessible.set(E_Locations.l_11_10);
		state.p_Accessible.set(E_Locations.l_7_6);
		state.p_Accessible.set(E_Locations.l_2_9);
		state.p_Accessible.set(E_Locations.l_4_10);
		state.p_Accessible.set(E_Locations.l_13_2);
		state.p_Accessible.set(E_Locations.l_7_8);
		state.p_Accessible.set(E_Locations.l_10_13);
		state.p_Accessible.set(E_Locations.l_11_3);
		state.p_Accessible.set(E_Locations.l_11_12);
		state.p_Accessible.set(E_Locations.l_2_15);
		state.p_Accessible.set(E_Locations.l_7_3);
		state.p_Accessible.set(E_Locations.l_15_1);
		state.p_Accessible.set(E_Locations.l_6_12);
		state.p_Accessible.set(E_Locations.l_10_9);
		state.p_Accessible.set(E_Locations.l_6_9);
		state.p_Accessible.set(E_Locations.l_11_5);
		state.p_Accessible.set(E_Locations.l_11_8);
		state.p_Accessible.set(E_Locations.l_12_9);
		state.p_Accessible.set(E_Locations.l_12_5);
		state.p_Accessible.set(E_Locations.l_6_13);
		state.p_Accessible.set(E_Locations.l_12_7);
		state.p_Accessible.set(E_Locations.l_11_14);
		state.p_Accessible.set(E_Locations.l_4_14);
		state.p_Accessible.set(E_Locations.l_13_3);
		state.p_Accessible.set(E_Locations.l_5_12);
		state.p_Accessible.set(E_Locations.l_1_7);
		state.p_Accessible.set(E_Locations.l_12_4);
		state.p_Accessible.set(E_Locations.l_14_4);
		state.p_Accessible.set(E_Locations.l_1_13);
		state.p_Accessible.set(E_Locations.l_1_8);
		state.p_Accessible.set(E_Locations.l_1_9);
		state.p_Accessible.set(E_Locations.l_4_5);
		state.p_Accessible.set(E_Locations.l_4_2);
		state.p_Accessible.set(E_Locations.l_10_7);
		state.p_Accessible.set(E_Locations.l_11_2);
		state.p_Accessible.set(E_Locations.l_4_6);
		state.p_Accessible.set(E_Locations.l_5_7);
		state.p_Accessible.set(E_Locations.l_12_6);
		state.p_Accessible.set(E_Locations.l_14_1);
		state.p_Accessible.set(E_Locations.l_14_7);
		state.p_Accessible.set(E_Locations.l_5_14);
		state.p_Accessible.set(E_Locations.l_9_6);
		state.p_Accessible.set(E_Locations.l_10_12);
		state.p_Accessible.set(E_Locations.l_5_4);
		state.p_Accessible.set(E_Locations.l_9_13);
		state.p_Accessible.set(E_Locations.l_2_12);
		state.p_Accessible.set(E_Locations.l_4_3);
		state.p_Accessible.set(E_Locations.l_14_8);
		state.p_Accessible.set(E_Locations.l_5_11);
		state.p_Accessible.set(E_Locations.l_13_4);
		

		state.p_Solid.set(E_Locations.l_7_1);
		state.p_Solid.set(E_Locations.l_7_2);
		state.p_Solid.set(E_Locations.l_10_13);
		state.p_Solid.set(E_Locations.l_12_4);
		state.p_Solid.set(E_Locations.l_2_4);
		state.p_Solid.set(E_Locations.l_14_6);
		state.p_Solid.set(E_Locations.l_2_6);
		state.p_Solid.set(E_Locations.l_14_3);
		state.p_Solid.set(E_Locations.l_9_11);
		state.p_Solid.set(E_Locations.l_15_1);
		state.p_Solid.set(E_Locations.l_2_11);
		state.p_Solid.set(E_Locations.l_11_15);
		state.p_Solid.set(E_Locations.l_15_12);
		state.p_Solid.set(E_Locations.l_3_10);
		state.p_Solid.set(E_Locations.l_5_7);
		state.p_Solid.set(E_Locations.l_6_10);
		state.p_Solid.set(E_Locations.l_5_2);
		state.p_Solid.set(E_Locations.l_5_14);
		state.p_Solid.set(E_Locations.l_4_4);
		state.p_Solid.set(E_Locations.l_12_13);
		state.p_Solid.set(E_Locations.l_14_13);
		state.p_Solid.set(E_Locations.l_2_10);
		state.p_Solid.set(E_Locations.l_14_9);
		state.p_Solid.set(E_Locations.l_10_10);
		state.p_Solid.set(E_Locations.l_6_2);
		state.p_Solid.set(E_Locations.l_15_2);
		state.p_Solid.set(E_Locations.l_10_6);
		state.p_Solid.set(E_Locations.l_5_8);
		state.p_Solid.set(E_Locations.l_9_10);
		state.p_Solid.set(E_Locations.l_6_4);
		state.p_Solid.set(E_Locations.l_9_5);
		state.p_Solid.set(E_Locations.l_2_1);
		state.p_Solid.set(E_Locations.l_3_6);
		state.p_Solid.set(E_Locations.l_3_13);
		state.p_Solid.set(E_Locations.l_7_7);
		state.p_Solid.set(E_Locations.l_1_6);
		state.p_Solid.set(E_Locations.l_4_3);
		state.p_Solid.set(E_Locations.l_4_1);
		state.p_Solid.set(E_Locations.l_3_1);
		state.p_Solid.set(E_Locations.l_15_6);
		state.p_Solid.set(E_Locations.l_14_2);
		state.p_Solid.set(E_Locations.l_5_13);
		state.p_Solid.set(E_Locations.l_5_15);
		state.p_Solid.set(E_Locations.l_1_14);
		state.p_Solid.set(E_Locations.l_4_8);
		state.p_Solid.set(E_Locations.l_8_2);
		state.p_Solid.set(E_Locations.l_7_13);
		state.p_Solid.set(E_Locations.l_1_7);
		state.p_Solid.set(E_Locations.l_6_9);
		state.p_Solid.set(E_Locations.l_4_11);
		state.p_Solid.set(E_Locations.l_11_3);
		state.p_Solid.set(E_Locations.l_7_8);
		state.p_Solid.set(E_Locations.l_9_14);
		state.p_Solid.set(E_Locations.l_15_11);
		state.p_Solid.set(E_Locations.l_2_13);
		state.p_Solid.set(E_Locations.l_15_3);
		state.p_Solid.set(E_Locations.l_15_14);
		state.p_Solid.set(E_Locations.l_9_2);
		state.p_Solid.set(E_Locations.l_7_3);
		state.p_Solid.set(E_Locations.l_4_7);
		state.p_Solid.set(E_Locations.l_7_5);
		state.p_Solid.set(E_Locations.l_5_11);
		state.p_Solid.set(E_Locations.l_13_4);
		state.p_Solid.set(E_Locations.l_7_6);
		state.p_Solid.set(E_Locations.l_8_4);
		state.p_Solid.set(E_Locations.l_15_8);
		state.p_Solid.set(E_Locations.l_5_6);
		state.p_Solid.set(E_Locations.l_8_15);
		state.p_Solid.set(E_Locations.l_12_7);
		state.p_Solid.set(E_Locations.l_11_9);
		state.p_Solid.set(E_Locations.l_1_1);
		state.p_Solid.set(E_Locations.l_6_1);
		state.p_Solid.set(E_Locations.l_6_15);
		state.p_Solid.set(E_Locations.l_13_8);
		state.p_Solid.set(E_Locations.l_2_2);
		state.p_Solid.set(E_Locations.l_4_12);
		state.p_Solid.set(E_Locations.l_5_4);
		state.p_Solid.set(E_Locations.l_9_6);
		state.p_Solid.set(E_Locations.l_4_13);
		state.p_Solid.set(E_Locations.l_5_12);
		state.p_Solid.set(E_Locations.l_2_15);
		state.p_Solid.set(E_Locations.l_13_3);
		state.p_Solid.set(E_Locations.l_8_7);
		state.p_Solid.set(E_Locations.l_13_5);
		state.p_Solid.set(E_Locations.l_6_5);
		state.p_Solid.set(E_Locations.l_13_11);
		state.p_Solid.set(E_Locations.l_3_5);
		state.p_Solid.set(E_Locations.l_4_5);
		state.p_Solid.set(E_Locations.l_15_13);
		state.p_Solid.set(E_Locations.l_6_11);
		state.p_Solid.set(E_Locations.l_12_9);
		state.p_Solid.set(E_Locations.l_9_4);
		state.p_Solid.set(E_Locations.l_4_14);
		state.p_Solid.set(E_Locations.l_13_10);
		state.p_Solid.set(E_Locations.l_11_14);
		state.p_Solid.set(E_Locations.l_15_7);
		state.p_Solid.set(E_Locations.l_10_12);
		state.p_Solid.set(E_Locations.l_8_9);
		state.p_Solid.set(E_Locations.l_11_13);
		state.p_Solid.set(E_Locations.l_14_4);
		state.p_Solid.set(E_Locations.l_6_7);
		state.p_Solid.set(E_Locations.l_15_10);
		state.p_Solid.set(E_Locations.l_9_3);
		state.p_Solid.set(E_Locations.l_12_14);
		state.p_Solid.set(E_Locations.l_7_11);
		state.p_Solid.set(E_Locations.l_11_11);
		state.p_Solid.set(E_Locations.l_8_11);
		state.p_Solid.set(E_Locations.l_3_7);
		state.p_Solid.set(E_Locations.l_8_12);
		state.p_Solid.set(E_Locations.l_9_1);
		state.p_Solid.set(E_Locations.l_13_14);
		state.p_Solid.set(E_Locations.l_4_10);
		state.p_Solid.set(E_Locations.l_12_5);
		state.p_Solid.set(E_Locations.l_2_7);
		state.p_Solid.set(E_Locations.l_10_7);
		

		state.p_Medium.set(E_Locations.l_11_1);
		state.p_Medium.set(E_Locations.l_11_6);
		state.p_Medium.set(E_Locations.l_14_8);
		state.p_Medium.set(E_Locations.l_6_13);
		state.p_Medium.set(E_Locations.l_4_9);
		state.p_Medium.set(E_Locations.l_3_4);
		state.p_Medium.set(E_Locations.l_2_3);
		state.p_Medium.set(E_Locations.l_1_2);
		state.p_Medium.set(E_Locations.l_13_6);
		state.p_Medium.set(E_Locations.l_5_9);
		state.p_Medium.set(E_Locations.l_12_15);
		state.p_Medium.set(E_Locations.l_15_4);
		state.p_Medium.set(E_Locations.l_14_11);
		state.p_Medium.set(E_Locations.l_2_8);
		state.p_Medium.set(E_Locations.l_4_6);
		state.p_Medium.set(E_Locations.l_14_14);
		state.p_Medium.set(E_Locations.l_2_12);
		state.p_Medium.set(E_Locations.l_12_3);
		state.p_Medium.set(E_Locations.l_2_9);
		state.p_Medium.set(E_Locations.l_12_12);
		state.p_Medium.set(E_Locations.l_8_8);
		state.p_Medium.set(E_Locations.l_5_3);
		state.p_Medium.set(E_Locations.l_1_12);
		state.p_Medium.set(E_Locations.l_4_2);
		state.p_Medium.set(E_Locations.l_11_8);
		state.p_Medium.set(E_Locations.l_10_14);
		state.p_Medium.set(E_Locations.l_12_2);
		state.p_Medium.set(E_Locations.l_11_10);
		state.p_Medium.set(E_Locations.l_1_13);
		state.p_Medium.set(E_Locations.l_13_12);
		state.p_Medium.set(E_Locations.l_11_7);
		state.p_Medium.set(E_Locations.l_10_15);
		state.p_Medium.set(E_Locations.l_6_12);
		state.p_Medium.set(E_Locations.l_13_15);
		state.p_Medium.set(E_Locations.l_9_13);
		state.p_Medium.set(E_Locations.l_2_14);
		state.p_Medium.set(E_Locations.l_6_3);
		state.p_Medium.set(E_Locations.l_8_6);
		

		state.p_Small.set(E_Locations.l_10_5);
		state.p_Small.set(E_Locations.l_15_9);
		state.p_Small.set(E_Locations.l_8_13);
		state.p_Small.set(E_Locations.l_3_15);
		state.p_Small.set(E_Locations.l_9_9);
		state.p_Small.set(E_Locations.l_15_15);
		state.p_Small.set(E_Locations.l_1_3);
		state.p_Small.set(E_Locations.l_5_10);
		state.p_Small.set(E_Locations.l_11_2);
		state.p_Small.set(E_Locations.l_7_15);
		state.p_Small.set(E_Locations.l_1_10);
		state.p_Small.set(E_Locations.l_7_10);
		state.p_Small.set(E_Locations.l_3_9);
		state.p_Small.set(E_Locations.l_11_4);
		state.p_Small.set(E_Locations.l_9_15);
		state.p_Small.set(E_Locations.l_10_3);
		state.p_Small.set(E_Locations.l_3_14);
		state.p_Small.set(E_Locations.l_12_1);
		state.p_Small.set(E_Locations.l_10_8);
		state.p_Small.set(E_Locations.l_3_11);
		state.p_Small.set(E_Locations.l_8_1);
		state.p_Small.set(E_Locations.l_1_11);
		state.p_Small.set(E_Locations.l_3_3);
		state.p_Small.set(E_Locations.l_3_8);
		state.p_Small.set(E_Locations.l_14_10);
		state.p_Small.set(E_Locations.l_5_1);
		state.p_Small.set(E_Locations.l_14_1);
		state.p_Small.set(E_Locations.l_13_9);
		state.p_Small.set(E_Locations.l_10_4);
		state.p_Small.set(E_Locations.l_15_5);
		state.p_Small.set(E_Locations.l_13_7);
		state.p_Small.set(E_Locations.l_12_11);
		state.p_Small.set(E_Locations.l_7_4);
		state.p_Small.set(E_Locations.l_13_2);
		state.p_Small.set(E_Locations.l_11_5);
		state.p_Small.set(E_Locations.l_10_9);
		state.p_Small.set(E_Locations.l_12_8);
		

		state.p_Big.set(E_Locations.l_14_15);
		state.p_Big.set(E_Locations.l_6_6);
		state.p_Big.set(E_Locations.l_8_5);
		state.p_Big.set(E_Locations.l_7_12);
		state.p_Big.set(E_Locations.l_9_12);
		state.p_Big.set(E_Locations.l_13_13);
		state.p_Big.set(E_Locations.l_6_14);
		state.p_Big.set(E_Locations.l_10_2);
		state.p_Big.set(E_Locations.l_8_3);
		state.p_Big.set(E_Locations.l_8_10);
		state.p_Big.set(E_Locations.l_2_5);
		state.p_Big.set(E_Locations.l_3_12);
		state.p_Big.set(E_Locations.l_1_4);
		state.p_Big.set(E_Locations.l_5_5);
		state.p_Big.set(E_Locations.l_14_12);
		state.p_Big.set(E_Locations.l_8_14);
		state.p_Big.set(E_Locations.l_7_9);
		state.p_Big.set(E_Locations.l_10_1);
		state.p_Big.set(E_Locations.l_4_15);
		state.p_Big.set(E_Locations.l_1_5);
		state.p_Big.set(E_Locations.l_1_8);
		state.p_Big.set(E_Locations.l_14_5);
		state.p_Big.set(E_Locations.l_1_15);
		state.p_Big.set(E_Locations.l_6_8);
		state.p_Big.set(E_Locations.l_7_14);
		state.p_Big.set(E_Locations.l_14_7);
		state.p_Big.set(E_Locations.l_13_1);
		state.p_Big.set(E_Locations.l_1_9);
		state.p_Big.set(E_Locations.l_11_12);
		state.p_Big.set(E_Locations.l_9_8);
		state.p_Big.set(E_Locations.l_10_11);
		state.p_Big.set(E_Locations.l_9_7);
		state.p_Big.set(E_Locations.l_12_10);
		state.p_Big.set(E_Locations.l_12_6);
		state.p_Big.set(E_Locations.l_3_2);
		

	}
	
	@Override
	public String getName() {
		return "Perestroika-Problem";
	}
	
	@Override
	public Domain getDomain() {
		return domain;
	}

	@Override
	public State getState() {
		return state;
	}

	@Override
	public Goal getGoal() {
		return goal;
	}	
	
	@Override
	public PDDLDeadEnd getDeadEnd() {
		return deadEnd;
	}
	
}