package cz.cuni.mff.perestroika.perestroika_problem_15_3_0_1_0_1_5;

import cz.cuni.mff.perestroika.domain.types.T_Location;
import cz.cuni.mff.perestroika.problem.E_Location;

public final class E_Locations {

	public static final T_Location l_1_1 = new T_Location("l-1-1");
	public static final T_Location l_1_2 = new T_Location("l-1-2");
	public static final T_Location l_1_3 = new T_Location("l-1-3");
	public static final T_Location l_1_4 = new T_Location("l-1-4");
	public static final T_Location l_1_5 = new T_Location("l-1-5");
	public static final T_Location l_1_6 = new T_Location("l-1-6");
	public static final T_Location l_1_7 = new T_Location("l-1-7");
	public static final T_Location l_1_8 = new T_Location("l-1-8");
	public static final T_Location l_1_9 = new T_Location("l-1-9");
	public static final T_Location l_1_10 = new T_Location("l-1-10");
	public static final T_Location l_1_11 = new T_Location("l-1-11");
	public static final T_Location l_1_12 = new T_Location("l-1-12");
	public static final T_Location l_1_13 = new T_Location("l-1-13");
	public static final T_Location l_1_14 = new T_Location("l-1-14");
	public static final T_Location l_1_15 = new T_Location("l-1-15");
	public static final T_Location l_2_1 = new T_Location("l-2-1");
	public static final T_Location l_2_2 = new T_Location("l-2-2");
	public static final T_Location l_2_3 = new T_Location("l-2-3");
	public static final T_Location l_2_4 = new T_Location("l-2-4");
	public static final T_Location l_2_5 = new T_Location("l-2-5");
	public static final T_Location l_2_6 = new T_Location("l-2-6");
	public static final T_Location l_2_7 = new T_Location("l-2-7");
	public static final T_Location l_2_8 = new T_Location("l-2-8");
	public static final T_Location l_2_9 = new T_Location("l-2-9");
	public static final T_Location l_2_10 = new T_Location("l-2-10");
	public static final T_Location l_2_11 = new T_Location("l-2-11");
	public static final T_Location l_2_12 = new T_Location("l-2-12");
	public static final T_Location l_2_13 = new T_Location("l-2-13");
	public static final T_Location l_2_14 = new T_Location("l-2-14");
	public static final T_Location l_2_15 = new T_Location("l-2-15");
	public static final T_Location l_3_1 = new T_Location("l-3-1");
	public static final T_Location l_3_2 = new T_Location("l-3-2");
	public static final T_Location l_3_3 = new T_Location("l-3-3");
	public static final T_Location l_3_4 = new T_Location("l-3-4");
	public static final T_Location l_3_5 = new T_Location("l-3-5");
	public static final T_Location l_3_6 = new T_Location("l-3-6");
	public static final T_Location l_3_7 = new T_Location("l-3-7");
	public static final T_Location l_3_8 = new T_Location("l-3-8");
	public static final T_Location l_3_9 = new T_Location("l-3-9");
	public static final T_Location l_3_10 = new T_Location("l-3-10");
	public static final T_Location l_3_11 = new T_Location("l-3-11");
	public static final T_Location l_3_12 = new T_Location("l-3-12");
	public static final T_Location l_3_13 = new T_Location("l-3-13");
	public static final T_Location l_3_14 = new T_Location("l-3-14");
	public static final T_Location l_3_15 = new T_Location("l-3-15");
	public static final T_Location l_4_1 = new T_Location("l-4-1");
	public static final T_Location l_4_2 = new T_Location("l-4-2");
	public static final T_Location l_4_3 = new T_Location("l-4-3");
	public static final T_Location l_4_4 = new T_Location("l-4-4");
	public static final T_Location l_4_5 = new T_Location("l-4-5");
	public static final T_Location l_4_6 = new T_Location("l-4-6");
	public static final T_Location l_4_7 = new T_Location("l-4-7");
	public static final T_Location l_4_8 = new T_Location("l-4-8");
	public static final T_Location l_4_9 = new T_Location("l-4-9");
	public static final T_Location l_4_10 = new T_Location("l-4-10");
	public static final T_Location l_4_11 = new T_Location("l-4-11");
	public static final T_Location l_4_12 = new T_Location("l-4-12");
	public static final T_Location l_4_13 = new T_Location("l-4-13");
	public static final T_Location l_4_14 = new T_Location("l-4-14");
	public static final T_Location l_4_15 = new T_Location("l-4-15");
	public static final T_Location l_5_1 = new T_Location("l-5-1");
	public static final T_Location l_5_2 = new T_Location("l-5-2");
	public static final T_Location l_5_3 = new T_Location("l-5-3");
	public static final T_Location l_5_4 = new T_Location("l-5-4");
	public static final T_Location l_5_5 = new T_Location("l-5-5");
	public static final T_Location l_5_6 = new T_Location("l-5-6");
	public static final T_Location l_5_7 = new T_Location("l-5-7");
	public static final T_Location l_5_8 = new T_Location("l-5-8");
	public static final T_Location l_5_9 = new T_Location("l-5-9");
	public static final T_Location l_5_10 = new T_Location("l-5-10");
	public static final T_Location l_5_11 = new T_Location("l-5-11");
	public static final T_Location l_5_12 = new T_Location("l-5-12");
	public static final T_Location l_5_13 = new T_Location("l-5-13");
	public static final T_Location l_5_14 = new T_Location("l-5-14");
	public static final T_Location l_5_15 = new T_Location("l-5-15");
	public static final T_Location l_6_1 = new T_Location("l-6-1");
	public static final T_Location l_6_2 = new T_Location("l-6-2");
	public static final T_Location l_6_3 = new T_Location("l-6-3");
	public static final T_Location l_6_4 = new T_Location("l-6-4");
	public static final T_Location l_6_5 = new T_Location("l-6-5");
	public static final T_Location l_6_6 = new T_Location("l-6-6");
	public static final T_Location l_6_7 = new T_Location("l-6-7");
	public static final T_Location l_6_8 = new T_Location("l-6-8");
	public static final T_Location l_6_9 = new T_Location("l-6-9");
	public static final T_Location l_6_10 = new T_Location("l-6-10");
	public static final T_Location l_6_11 = new T_Location("l-6-11");
	public static final T_Location l_6_12 = new T_Location("l-6-12");
	public static final T_Location l_6_13 = new T_Location("l-6-13");
	public static final T_Location l_6_14 = new T_Location("l-6-14");
	public static final T_Location l_6_15 = new T_Location("l-6-15");
	public static final T_Location l_7_1 = new T_Location("l-7-1");
	public static final T_Location l_7_2 = new T_Location("l-7-2");
	public static final T_Location l_7_3 = new T_Location("l-7-3");
	public static final T_Location l_7_4 = new T_Location("l-7-4");
	public static final T_Location l_7_5 = new T_Location("l-7-5");
	public static final T_Location l_7_6 = new T_Location("l-7-6");
	public static final T_Location l_7_7 = new T_Location("l-7-7");
	public static final T_Location l_7_8 = new T_Location("l-7-8");
	public static final T_Location l_7_9 = new T_Location("l-7-9");
	public static final T_Location l_7_10 = new T_Location("l-7-10");
	public static final T_Location l_7_11 = new T_Location("l-7-11");
	public static final T_Location l_7_12 = new T_Location("l-7-12");
	public static final T_Location l_7_13 = new T_Location("l-7-13");
	public static final T_Location l_7_14 = new T_Location("l-7-14");
	public static final T_Location l_7_15 = new T_Location("l-7-15");
	public static final T_Location l_8_1 = new T_Location("l-8-1");
	public static final T_Location l_8_2 = new T_Location("l-8-2");
	public static final T_Location l_8_3 = new T_Location("l-8-3");
	public static final T_Location l_8_4 = new T_Location("l-8-4");
	public static final T_Location l_8_5 = new T_Location("l-8-5");
	public static final T_Location l_8_6 = new T_Location("l-8-6");
	public static final T_Location l_8_7 = new T_Location("l-8-7");
	public static final T_Location l_8_8 = new T_Location("l-8-8");
	public static final T_Location l_8_9 = new T_Location("l-8-9");
	public static final T_Location l_8_10 = new T_Location("l-8-10");
	public static final T_Location l_8_11 = new T_Location("l-8-11");
	public static final T_Location l_8_12 = new T_Location("l-8-12");
	public static final T_Location l_8_13 = new T_Location("l-8-13");
	public static final T_Location l_8_14 = new T_Location("l-8-14");
	public static final T_Location l_8_15 = new T_Location("l-8-15");
	public static final T_Location l_9_1 = new T_Location("l-9-1");
	public static final T_Location l_9_2 = new T_Location("l-9-2");
	public static final T_Location l_9_3 = new T_Location("l-9-3");
	public static final T_Location l_9_4 = new T_Location("l-9-4");
	public static final T_Location l_9_5 = new T_Location("l-9-5");
	public static final T_Location l_9_6 = new T_Location("l-9-6");
	public static final T_Location l_9_7 = new T_Location("l-9-7");
	public static final T_Location l_9_8 = new T_Location("l-9-8");
	public static final T_Location l_9_9 = new T_Location("l-9-9");
	public static final T_Location l_9_10 = new T_Location("l-9-10");
	public static final T_Location l_9_11 = new T_Location("l-9-11");
	public static final T_Location l_9_12 = new T_Location("l-9-12");
	public static final T_Location l_9_13 = new T_Location("l-9-13");
	public static final T_Location l_9_14 = new T_Location("l-9-14");
	public static final T_Location l_9_15 = new T_Location("l-9-15");
	public static final T_Location l_10_1 = new T_Location("l-10-1");
	public static final T_Location l_10_2 = new T_Location("l-10-2");
	public static final T_Location l_10_3 = new T_Location("l-10-3");
	public static final T_Location l_10_4 = new T_Location("l-10-4");
	public static final T_Location l_10_5 = new T_Location("l-10-5");
	public static final T_Location l_10_6 = new T_Location("l-10-6");
	public static final T_Location l_10_7 = new T_Location("l-10-7");
	public static final T_Location l_10_8 = new T_Location("l-10-8");
	public static final T_Location l_10_9 = new T_Location("l-10-9");
	public static final T_Location l_10_10 = new T_Location("l-10-10");
	public static final T_Location l_10_11 = new T_Location("l-10-11");
	public static final T_Location l_10_12 = new T_Location("l-10-12");
	public static final T_Location l_10_13 = new T_Location("l-10-13");
	public static final T_Location l_10_14 = new T_Location("l-10-14");
	public static final T_Location l_10_15 = new T_Location("l-10-15");
	public static final T_Location l_11_1 = new T_Location("l-11-1");
	public static final T_Location l_11_2 = new T_Location("l-11-2");
	public static final T_Location l_11_3 = new T_Location("l-11-3");
	public static final T_Location l_11_4 = new T_Location("l-11-4");
	public static final T_Location l_11_5 = new T_Location("l-11-5");
	public static final T_Location l_11_6 = new T_Location("l-11-6");
	public static final T_Location l_11_7 = new T_Location("l-11-7");
	public static final T_Location l_11_8 = new T_Location("l-11-8");
	public static final T_Location l_11_9 = new T_Location("l-11-9");
	public static final T_Location l_11_10 = new T_Location("l-11-10");
	public static final T_Location l_11_11 = new T_Location("l-11-11");
	public static final T_Location l_11_12 = new T_Location("l-11-12");
	public static final T_Location l_11_13 = new T_Location("l-11-13");
	public static final T_Location l_11_14 = new T_Location("l-11-14");
	public static final T_Location l_11_15 = new T_Location("l-11-15");
	public static final T_Location l_12_1 = new T_Location("l-12-1");
	public static final T_Location l_12_2 = new T_Location("l-12-2");
	public static final T_Location l_12_3 = new T_Location("l-12-3");
	public static final T_Location l_12_4 = new T_Location("l-12-4");
	public static final T_Location l_12_5 = new T_Location("l-12-5");
	public static final T_Location l_12_6 = new T_Location("l-12-6");
	public static final T_Location l_12_7 = new T_Location("l-12-7");
	public static final T_Location l_12_8 = new T_Location("l-12-8");
	public static final T_Location l_12_9 = new T_Location("l-12-9");
	public static final T_Location l_12_10 = new T_Location("l-12-10");
	public static final T_Location l_12_11 = new T_Location("l-12-11");
	public static final T_Location l_12_12 = new T_Location("l-12-12");
	public static final T_Location l_12_13 = new T_Location("l-12-13");
	public static final T_Location l_12_14 = new T_Location("l-12-14");
	public static final T_Location l_12_15 = new T_Location("l-12-15");
	public static final T_Location l_13_1 = new T_Location("l-13-1");
	public static final T_Location l_13_2 = new T_Location("l-13-2");
	public static final T_Location l_13_3 = new T_Location("l-13-3");
	public static final T_Location l_13_4 = new T_Location("l-13-4");
	public static final T_Location l_13_5 = new T_Location("l-13-5");
	public static final T_Location l_13_6 = new T_Location("l-13-6");
	public static final T_Location l_13_7 = new T_Location("l-13-7");
	public static final T_Location l_13_8 = new T_Location("l-13-8");
	public static final T_Location l_13_9 = new T_Location("l-13-9");
	public static final T_Location l_13_10 = new T_Location("l-13-10");
	public static final T_Location l_13_11 = new T_Location("l-13-11");
	public static final T_Location l_13_12 = new T_Location("l-13-12");
	public static final T_Location l_13_13 = new T_Location("l-13-13");
	public static final T_Location l_13_14 = new T_Location("l-13-14");
	public static final T_Location l_13_15 = new T_Location("l-13-15");
	public static final T_Location l_14_1 = new T_Location("l-14-1");
	public static final T_Location l_14_2 = new T_Location("l-14-2");
	public static final T_Location l_14_3 = new T_Location("l-14-3");
	public static final T_Location l_14_4 = new T_Location("l-14-4");
	public static final T_Location l_14_5 = new T_Location("l-14-5");
	public static final T_Location l_14_6 = new T_Location("l-14-6");
	public static final T_Location l_14_7 = new T_Location("l-14-7");
	public static final T_Location l_14_8 = new T_Location("l-14-8");
	public static final T_Location l_14_9 = new T_Location("l-14-9");
	public static final T_Location l_14_10 = new T_Location("l-14-10");
	public static final T_Location l_14_11 = new T_Location("l-14-11");
	public static final T_Location l_14_12 = new T_Location("l-14-12");
	public static final T_Location l_14_13 = new T_Location("l-14-13");
	public static final T_Location l_14_14 = new T_Location("l-14-14");
	public static final T_Location l_14_15 = new T_Location("l-14-15");
	public static final T_Location l_15_1 = new T_Location("l-15-1");
	public static final T_Location l_15_2 = new T_Location("l-15-2");
	public static final T_Location l_15_3 = new T_Location("l-15-3");
	public static final T_Location l_15_4 = new T_Location("l-15-4");
	public static final T_Location l_15_5 = new T_Location("l-15-5");
	public static final T_Location l_15_6 = new T_Location("l-15-6");
	public static final T_Location l_15_7 = new T_Location("l-15-7");
	public static final T_Location l_15_8 = new T_Location("l-15-8");
	public static final T_Location l_15_9 = new T_Location("l-15-9");
	public static final T_Location l_15_10 = new T_Location("l-15-10");
	public static final T_Location l_15_11 = new T_Location("l-15-11");
	public static final T_Location l_15_12 = new T_Location("l-15-12");
	public static final T_Location l_15_13 = new T_Location("l-15-13");
	public static final T_Location l_15_14 = new T_Location("l-15-14");
	public static final T_Location l_15_15 = new T_Location("l-15-15");
	

	static {

		E_Location.THIS.register(T_Location.getIndex(l_1_1), l_1_1);
		E_Location.THIS.register(T_Location.getIndex(l_1_2), l_1_2);
		E_Location.THIS.register(T_Location.getIndex(l_1_3), l_1_3);
		E_Location.THIS.register(T_Location.getIndex(l_1_4), l_1_4);
		E_Location.THIS.register(T_Location.getIndex(l_1_5), l_1_5);
		E_Location.THIS.register(T_Location.getIndex(l_1_6), l_1_6);
		E_Location.THIS.register(T_Location.getIndex(l_1_7), l_1_7);
		E_Location.THIS.register(T_Location.getIndex(l_1_8), l_1_8);
		E_Location.THIS.register(T_Location.getIndex(l_1_9), l_1_9);
		E_Location.THIS.register(T_Location.getIndex(l_1_10), l_1_10);
		E_Location.THIS.register(T_Location.getIndex(l_1_11), l_1_11);
		E_Location.THIS.register(T_Location.getIndex(l_1_12), l_1_12);
		E_Location.THIS.register(T_Location.getIndex(l_1_13), l_1_13);
		E_Location.THIS.register(T_Location.getIndex(l_1_14), l_1_14);
		E_Location.THIS.register(T_Location.getIndex(l_1_15), l_1_15);
		E_Location.THIS.register(T_Location.getIndex(l_2_1), l_2_1);
		E_Location.THIS.register(T_Location.getIndex(l_2_2), l_2_2);
		E_Location.THIS.register(T_Location.getIndex(l_2_3), l_2_3);
		E_Location.THIS.register(T_Location.getIndex(l_2_4), l_2_4);
		E_Location.THIS.register(T_Location.getIndex(l_2_5), l_2_5);
		E_Location.THIS.register(T_Location.getIndex(l_2_6), l_2_6);
		E_Location.THIS.register(T_Location.getIndex(l_2_7), l_2_7);
		E_Location.THIS.register(T_Location.getIndex(l_2_8), l_2_8);
		E_Location.THIS.register(T_Location.getIndex(l_2_9), l_2_9);
		E_Location.THIS.register(T_Location.getIndex(l_2_10), l_2_10);
		E_Location.THIS.register(T_Location.getIndex(l_2_11), l_2_11);
		E_Location.THIS.register(T_Location.getIndex(l_2_12), l_2_12);
		E_Location.THIS.register(T_Location.getIndex(l_2_13), l_2_13);
		E_Location.THIS.register(T_Location.getIndex(l_2_14), l_2_14);
		E_Location.THIS.register(T_Location.getIndex(l_2_15), l_2_15);
		E_Location.THIS.register(T_Location.getIndex(l_3_1), l_3_1);
		E_Location.THIS.register(T_Location.getIndex(l_3_2), l_3_2);
		E_Location.THIS.register(T_Location.getIndex(l_3_3), l_3_3);
		E_Location.THIS.register(T_Location.getIndex(l_3_4), l_3_4);
		E_Location.THIS.register(T_Location.getIndex(l_3_5), l_3_5);
		E_Location.THIS.register(T_Location.getIndex(l_3_6), l_3_6);
		E_Location.THIS.register(T_Location.getIndex(l_3_7), l_3_7);
		E_Location.THIS.register(T_Location.getIndex(l_3_8), l_3_8);
		E_Location.THIS.register(T_Location.getIndex(l_3_9), l_3_9);
		E_Location.THIS.register(T_Location.getIndex(l_3_10), l_3_10);
		E_Location.THIS.register(T_Location.getIndex(l_3_11), l_3_11);
		E_Location.THIS.register(T_Location.getIndex(l_3_12), l_3_12);
		E_Location.THIS.register(T_Location.getIndex(l_3_13), l_3_13);
		E_Location.THIS.register(T_Location.getIndex(l_3_14), l_3_14);
		E_Location.THIS.register(T_Location.getIndex(l_3_15), l_3_15);
		E_Location.THIS.register(T_Location.getIndex(l_4_1), l_4_1);
		E_Location.THIS.register(T_Location.getIndex(l_4_2), l_4_2);
		E_Location.THIS.register(T_Location.getIndex(l_4_3), l_4_3);
		E_Location.THIS.register(T_Location.getIndex(l_4_4), l_4_4);
		E_Location.THIS.register(T_Location.getIndex(l_4_5), l_4_5);
		E_Location.THIS.register(T_Location.getIndex(l_4_6), l_4_6);
		E_Location.THIS.register(T_Location.getIndex(l_4_7), l_4_7);
		E_Location.THIS.register(T_Location.getIndex(l_4_8), l_4_8);
		E_Location.THIS.register(T_Location.getIndex(l_4_9), l_4_9);
		E_Location.THIS.register(T_Location.getIndex(l_4_10), l_4_10);
		E_Location.THIS.register(T_Location.getIndex(l_4_11), l_4_11);
		E_Location.THIS.register(T_Location.getIndex(l_4_12), l_4_12);
		E_Location.THIS.register(T_Location.getIndex(l_4_13), l_4_13);
		E_Location.THIS.register(T_Location.getIndex(l_4_14), l_4_14);
		E_Location.THIS.register(T_Location.getIndex(l_4_15), l_4_15);
		E_Location.THIS.register(T_Location.getIndex(l_5_1), l_5_1);
		E_Location.THIS.register(T_Location.getIndex(l_5_2), l_5_2);
		E_Location.THIS.register(T_Location.getIndex(l_5_3), l_5_3);
		E_Location.THIS.register(T_Location.getIndex(l_5_4), l_5_4);
		E_Location.THIS.register(T_Location.getIndex(l_5_5), l_5_5);
		E_Location.THIS.register(T_Location.getIndex(l_5_6), l_5_6);
		E_Location.THIS.register(T_Location.getIndex(l_5_7), l_5_7);
		E_Location.THIS.register(T_Location.getIndex(l_5_8), l_5_8);
		E_Location.THIS.register(T_Location.getIndex(l_5_9), l_5_9);
		E_Location.THIS.register(T_Location.getIndex(l_5_10), l_5_10);
		E_Location.THIS.register(T_Location.getIndex(l_5_11), l_5_11);
		E_Location.THIS.register(T_Location.getIndex(l_5_12), l_5_12);
		E_Location.THIS.register(T_Location.getIndex(l_5_13), l_5_13);
		E_Location.THIS.register(T_Location.getIndex(l_5_14), l_5_14);
		E_Location.THIS.register(T_Location.getIndex(l_5_15), l_5_15);
		E_Location.THIS.register(T_Location.getIndex(l_6_1), l_6_1);
		E_Location.THIS.register(T_Location.getIndex(l_6_2), l_6_2);
		E_Location.THIS.register(T_Location.getIndex(l_6_3), l_6_3);
		E_Location.THIS.register(T_Location.getIndex(l_6_4), l_6_4);
		E_Location.THIS.register(T_Location.getIndex(l_6_5), l_6_5);
		E_Location.THIS.register(T_Location.getIndex(l_6_6), l_6_6);
		E_Location.THIS.register(T_Location.getIndex(l_6_7), l_6_7);
		E_Location.THIS.register(T_Location.getIndex(l_6_8), l_6_8);
		E_Location.THIS.register(T_Location.getIndex(l_6_9), l_6_9);
		E_Location.THIS.register(T_Location.getIndex(l_6_10), l_6_10);
		E_Location.THIS.register(T_Location.getIndex(l_6_11), l_6_11);
		E_Location.THIS.register(T_Location.getIndex(l_6_12), l_6_12);
		E_Location.THIS.register(T_Location.getIndex(l_6_13), l_6_13);
		E_Location.THIS.register(T_Location.getIndex(l_6_14), l_6_14);
		E_Location.THIS.register(T_Location.getIndex(l_6_15), l_6_15);
		E_Location.THIS.register(T_Location.getIndex(l_7_1), l_7_1);
		E_Location.THIS.register(T_Location.getIndex(l_7_2), l_7_2);
		E_Location.THIS.register(T_Location.getIndex(l_7_3), l_7_3);
		E_Location.THIS.register(T_Location.getIndex(l_7_4), l_7_4);
		E_Location.THIS.register(T_Location.getIndex(l_7_5), l_7_5);
		E_Location.THIS.register(T_Location.getIndex(l_7_6), l_7_6);
		E_Location.THIS.register(T_Location.getIndex(l_7_7), l_7_7);
		E_Location.THIS.register(T_Location.getIndex(l_7_8), l_7_8);
		E_Location.THIS.register(T_Location.getIndex(l_7_9), l_7_9);
		E_Location.THIS.register(T_Location.getIndex(l_7_10), l_7_10);
		E_Location.THIS.register(T_Location.getIndex(l_7_11), l_7_11);
		E_Location.THIS.register(T_Location.getIndex(l_7_12), l_7_12);
		E_Location.THIS.register(T_Location.getIndex(l_7_13), l_7_13);
		E_Location.THIS.register(T_Location.getIndex(l_7_14), l_7_14);
		E_Location.THIS.register(T_Location.getIndex(l_7_15), l_7_15);
		E_Location.THIS.register(T_Location.getIndex(l_8_1), l_8_1);
		E_Location.THIS.register(T_Location.getIndex(l_8_2), l_8_2);
		E_Location.THIS.register(T_Location.getIndex(l_8_3), l_8_3);
		E_Location.THIS.register(T_Location.getIndex(l_8_4), l_8_4);
		E_Location.THIS.register(T_Location.getIndex(l_8_5), l_8_5);
		E_Location.THIS.register(T_Location.getIndex(l_8_6), l_8_6);
		E_Location.THIS.register(T_Location.getIndex(l_8_7), l_8_7);
		E_Location.THIS.register(T_Location.getIndex(l_8_8), l_8_8);
		E_Location.THIS.register(T_Location.getIndex(l_8_9), l_8_9);
		E_Location.THIS.register(T_Location.getIndex(l_8_10), l_8_10);
		E_Location.THIS.register(T_Location.getIndex(l_8_11), l_8_11);
		E_Location.THIS.register(T_Location.getIndex(l_8_12), l_8_12);
		E_Location.THIS.register(T_Location.getIndex(l_8_13), l_8_13);
		E_Location.THIS.register(T_Location.getIndex(l_8_14), l_8_14);
		E_Location.THIS.register(T_Location.getIndex(l_8_15), l_8_15);
		E_Location.THIS.register(T_Location.getIndex(l_9_1), l_9_1);
		E_Location.THIS.register(T_Location.getIndex(l_9_2), l_9_2);
		E_Location.THIS.register(T_Location.getIndex(l_9_3), l_9_3);
		E_Location.THIS.register(T_Location.getIndex(l_9_4), l_9_4);
		E_Location.THIS.register(T_Location.getIndex(l_9_5), l_9_5);
		E_Location.THIS.register(T_Location.getIndex(l_9_6), l_9_6);
		E_Location.THIS.register(T_Location.getIndex(l_9_7), l_9_7);
		E_Location.THIS.register(T_Location.getIndex(l_9_8), l_9_8);
		E_Location.THIS.register(T_Location.getIndex(l_9_9), l_9_9);
		E_Location.THIS.register(T_Location.getIndex(l_9_10), l_9_10);
		E_Location.THIS.register(T_Location.getIndex(l_9_11), l_9_11);
		E_Location.THIS.register(T_Location.getIndex(l_9_12), l_9_12);
		E_Location.THIS.register(T_Location.getIndex(l_9_13), l_9_13);
		E_Location.THIS.register(T_Location.getIndex(l_9_14), l_9_14);
		E_Location.THIS.register(T_Location.getIndex(l_9_15), l_9_15);
		E_Location.THIS.register(T_Location.getIndex(l_10_1), l_10_1);
		E_Location.THIS.register(T_Location.getIndex(l_10_2), l_10_2);
		E_Location.THIS.register(T_Location.getIndex(l_10_3), l_10_3);
		E_Location.THIS.register(T_Location.getIndex(l_10_4), l_10_4);
		E_Location.THIS.register(T_Location.getIndex(l_10_5), l_10_5);
		E_Location.THIS.register(T_Location.getIndex(l_10_6), l_10_6);
		E_Location.THIS.register(T_Location.getIndex(l_10_7), l_10_7);
		E_Location.THIS.register(T_Location.getIndex(l_10_8), l_10_8);
		E_Location.THIS.register(T_Location.getIndex(l_10_9), l_10_9);
		E_Location.THIS.register(T_Location.getIndex(l_10_10), l_10_10);
		E_Location.THIS.register(T_Location.getIndex(l_10_11), l_10_11);
		E_Location.THIS.register(T_Location.getIndex(l_10_12), l_10_12);
		E_Location.THIS.register(T_Location.getIndex(l_10_13), l_10_13);
		E_Location.THIS.register(T_Location.getIndex(l_10_14), l_10_14);
		E_Location.THIS.register(T_Location.getIndex(l_10_15), l_10_15);
		E_Location.THIS.register(T_Location.getIndex(l_11_1), l_11_1);
		E_Location.THIS.register(T_Location.getIndex(l_11_2), l_11_2);
		E_Location.THIS.register(T_Location.getIndex(l_11_3), l_11_3);
		E_Location.THIS.register(T_Location.getIndex(l_11_4), l_11_4);
		E_Location.THIS.register(T_Location.getIndex(l_11_5), l_11_5);
		E_Location.THIS.register(T_Location.getIndex(l_11_6), l_11_6);
		E_Location.THIS.register(T_Location.getIndex(l_11_7), l_11_7);
		E_Location.THIS.register(T_Location.getIndex(l_11_8), l_11_8);
		E_Location.THIS.register(T_Location.getIndex(l_11_9), l_11_9);
		E_Location.THIS.register(T_Location.getIndex(l_11_10), l_11_10);
		E_Location.THIS.register(T_Location.getIndex(l_11_11), l_11_11);
		E_Location.THIS.register(T_Location.getIndex(l_11_12), l_11_12);
		E_Location.THIS.register(T_Location.getIndex(l_11_13), l_11_13);
		E_Location.THIS.register(T_Location.getIndex(l_11_14), l_11_14);
		E_Location.THIS.register(T_Location.getIndex(l_11_15), l_11_15);
		E_Location.THIS.register(T_Location.getIndex(l_12_1), l_12_1);
		E_Location.THIS.register(T_Location.getIndex(l_12_2), l_12_2);
		E_Location.THIS.register(T_Location.getIndex(l_12_3), l_12_3);
		E_Location.THIS.register(T_Location.getIndex(l_12_4), l_12_4);
		E_Location.THIS.register(T_Location.getIndex(l_12_5), l_12_5);
		E_Location.THIS.register(T_Location.getIndex(l_12_6), l_12_6);
		E_Location.THIS.register(T_Location.getIndex(l_12_7), l_12_7);
		E_Location.THIS.register(T_Location.getIndex(l_12_8), l_12_8);
		E_Location.THIS.register(T_Location.getIndex(l_12_9), l_12_9);
		E_Location.THIS.register(T_Location.getIndex(l_12_10), l_12_10);
		E_Location.THIS.register(T_Location.getIndex(l_12_11), l_12_11);
		E_Location.THIS.register(T_Location.getIndex(l_12_12), l_12_12);
		E_Location.THIS.register(T_Location.getIndex(l_12_13), l_12_13);
		E_Location.THIS.register(T_Location.getIndex(l_12_14), l_12_14);
		E_Location.THIS.register(T_Location.getIndex(l_12_15), l_12_15);
		E_Location.THIS.register(T_Location.getIndex(l_13_1), l_13_1);
		E_Location.THIS.register(T_Location.getIndex(l_13_2), l_13_2);
		E_Location.THIS.register(T_Location.getIndex(l_13_3), l_13_3);
		E_Location.THIS.register(T_Location.getIndex(l_13_4), l_13_4);
		E_Location.THIS.register(T_Location.getIndex(l_13_5), l_13_5);
		E_Location.THIS.register(T_Location.getIndex(l_13_6), l_13_6);
		E_Location.THIS.register(T_Location.getIndex(l_13_7), l_13_7);
		E_Location.THIS.register(T_Location.getIndex(l_13_8), l_13_8);
		E_Location.THIS.register(T_Location.getIndex(l_13_9), l_13_9);
		E_Location.THIS.register(T_Location.getIndex(l_13_10), l_13_10);
		E_Location.THIS.register(T_Location.getIndex(l_13_11), l_13_11);
		E_Location.THIS.register(T_Location.getIndex(l_13_12), l_13_12);
		E_Location.THIS.register(T_Location.getIndex(l_13_13), l_13_13);
		E_Location.THIS.register(T_Location.getIndex(l_13_14), l_13_14);
		E_Location.THIS.register(T_Location.getIndex(l_13_15), l_13_15);
		E_Location.THIS.register(T_Location.getIndex(l_14_1), l_14_1);
		E_Location.THIS.register(T_Location.getIndex(l_14_2), l_14_2);
		E_Location.THIS.register(T_Location.getIndex(l_14_3), l_14_3);
		E_Location.THIS.register(T_Location.getIndex(l_14_4), l_14_4);
		E_Location.THIS.register(T_Location.getIndex(l_14_5), l_14_5);
		E_Location.THIS.register(T_Location.getIndex(l_14_6), l_14_6);
		E_Location.THIS.register(T_Location.getIndex(l_14_7), l_14_7);
		E_Location.THIS.register(T_Location.getIndex(l_14_8), l_14_8);
		E_Location.THIS.register(T_Location.getIndex(l_14_9), l_14_9);
		E_Location.THIS.register(T_Location.getIndex(l_14_10), l_14_10);
		E_Location.THIS.register(T_Location.getIndex(l_14_11), l_14_11);
		E_Location.THIS.register(T_Location.getIndex(l_14_12), l_14_12);
		E_Location.THIS.register(T_Location.getIndex(l_14_13), l_14_13);
		E_Location.THIS.register(T_Location.getIndex(l_14_14), l_14_14);
		E_Location.THIS.register(T_Location.getIndex(l_14_15), l_14_15);
		E_Location.THIS.register(T_Location.getIndex(l_15_1), l_15_1);
		E_Location.THIS.register(T_Location.getIndex(l_15_2), l_15_2);
		E_Location.THIS.register(T_Location.getIndex(l_15_3), l_15_3);
		E_Location.THIS.register(T_Location.getIndex(l_15_4), l_15_4);
		E_Location.THIS.register(T_Location.getIndex(l_15_5), l_15_5);
		E_Location.THIS.register(T_Location.getIndex(l_15_6), l_15_6);
		E_Location.THIS.register(T_Location.getIndex(l_15_7), l_15_7);
		E_Location.THIS.register(T_Location.getIndex(l_15_8), l_15_8);
		E_Location.THIS.register(T_Location.getIndex(l_15_9), l_15_9);
		E_Location.THIS.register(T_Location.getIndex(l_15_10), l_15_10);
		E_Location.THIS.register(T_Location.getIndex(l_15_11), l_15_11);
		E_Location.THIS.register(T_Location.getIndex(l_15_12), l_15_12);
		E_Location.THIS.register(T_Location.getIndex(l_15_13), l_15_13);
		E_Location.THIS.register(T_Location.getIndex(l_15_14), l_15_14);
		E_Location.THIS.register(T_Location.getIndex(l_15_15), l_15_15);
		
	}
		
	protected E_Locations() {
	}

}