package cz.cuni.mff.perestroika.perestroika_problem_25_3_0_3_0_3_6;

import cz.cuni.mff.perestroika.domain.types.T_Resource;
import cz.cuni.mff.perestroika.problem.E_Resource;

public final class E_Resources {

	public static final T_Resource r1 = new T_Resource("r1");
	public static final T_Resource r2 = new T_Resource("r2");
	public static final T_Resource r3 = new T_Resource("r3");
	public static final T_Resource r4 = new T_Resource("r4");
	public static final T_Resource r5 = new T_Resource("r5");
	public static final T_Resource r6 = new T_Resource("r6");
	public static final T_Resource r7 = new T_Resource("r7");
	public static final T_Resource r8 = new T_Resource("r8");
	public static final T_Resource r9 = new T_Resource("r9");
	public static final T_Resource r10 = new T_Resource("r10");
	public static final T_Resource r11 = new T_Resource("r11");
	public static final T_Resource r12 = new T_Resource("r12");
	public static final T_Resource r13 = new T_Resource("r13");
	public static final T_Resource r14 = new T_Resource("r14");
	public static final T_Resource r15 = new T_Resource("r15");
	public static final T_Resource r16 = new T_Resource("r16");
	public static final T_Resource r17 = new T_Resource("r17");
	public static final T_Resource r18 = new T_Resource("r18");
	public static final T_Resource r19 = new T_Resource("r19");
	public static final T_Resource r20 = new T_Resource("r20");
	public static final T_Resource r21 = new T_Resource("r21");
	public static final T_Resource r22 = new T_Resource("r22");
	public static final T_Resource r23 = new T_Resource("r23");
	public static final T_Resource r24 = new T_Resource("r24");
	public static final T_Resource r25 = new T_Resource("r25");
	public static final T_Resource r26 = new T_Resource("r26");
	public static final T_Resource r27 = new T_Resource("r27");
	public static final T_Resource r28 = new T_Resource("r28");
	public static final T_Resource r29 = new T_Resource("r29");
	public static final T_Resource r30 = new T_Resource("r30");
	public static final T_Resource r31 = new T_Resource("r31");
	public static final T_Resource r32 = new T_Resource("r32");
	public static final T_Resource r33 = new T_Resource("r33");
	public static final T_Resource r34 = new T_Resource("r34");
	public static final T_Resource r35 = new T_Resource("r35");
	public static final T_Resource r36 = new T_Resource("r36");
	public static final T_Resource r37 = new T_Resource("r37");
	public static final T_Resource r38 = new T_Resource("r38");
	public static final T_Resource r39 = new T_Resource("r39");
	public static final T_Resource r40 = new T_Resource("r40");
	public static final T_Resource r41 = new T_Resource("r41");
	public static final T_Resource r42 = new T_Resource("r42");
	public static final T_Resource r43 = new T_Resource("r43");
	public static final T_Resource r44 = new T_Resource("r44");
	public static final T_Resource r45 = new T_Resource("r45");
	public static final T_Resource r46 = new T_Resource("r46");
	public static final T_Resource r47 = new T_Resource("r47");
	public static final T_Resource r48 = new T_Resource("r48");
	public static final T_Resource r49 = new T_Resource("r49");
	public static final T_Resource r50 = new T_Resource("r50");
	public static final T_Resource r51 = new T_Resource("r51");
	public static final T_Resource r52 = new T_Resource("r52");
	public static final T_Resource r53 = new T_Resource("r53");
	public static final T_Resource r54 = new T_Resource("r54");
	public static final T_Resource r55 = new T_Resource("r55");
	public static final T_Resource r56 = new T_Resource("r56");
	public static final T_Resource r57 = new T_Resource("r57");
	public static final T_Resource r58 = new T_Resource("r58");
	public static final T_Resource r59 = new T_Resource("r59");
	public static final T_Resource r60 = new T_Resource("r60");
	public static final T_Resource r61 = new T_Resource("r61");
	public static final T_Resource r62 = new T_Resource("r62");
	public static final T_Resource r63 = new T_Resource("r63");
	public static final T_Resource r64 = new T_Resource("r64");
	public static final T_Resource r65 = new T_Resource("r65");
	public static final T_Resource r66 = new T_Resource("r66");
	public static final T_Resource r67 = new T_Resource("r67");
	public static final T_Resource r68 = new T_Resource("r68");
	public static final T_Resource r69 = new T_Resource("r69");
	public static final T_Resource r70 = new T_Resource("r70");
	public static final T_Resource r71 = new T_Resource("r71");
	public static final T_Resource r72 = new T_Resource("r72");
	public static final T_Resource r73 = new T_Resource("r73");
	public static final T_Resource r74 = new T_Resource("r74");
	public static final T_Resource r75 = new T_Resource("r75");
	public static final T_Resource r76 = new T_Resource("r76");
	public static final T_Resource r77 = new T_Resource("r77");
	public static final T_Resource r78 = new T_Resource("r78");
	public static final T_Resource r79 = new T_Resource("r79");
	public static final T_Resource r80 = new T_Resource("r80");
	public static final T_Resource r81 = new T_Resource("r81");
	public static final T_Resource r82 = new T_Resource("r82");
	public static final T_Resource r83 = new T_Resource("r83");
	public static final T_Resource r84 = new T_Resource("r84");
	public static final T_Resource r85 = new T_Resource("r85");
	public static final T_Resource r86 = new T_Resource("r86");
	public static final T_Resource r87 = new T_Resource("r87");
	public static final T_Resource r88 = new T_Resource("r88");
	public static final T_Resource r89 = new T_Resource("r89");
	public static final T_Resource r90 = new T_Resource("r90");
	public static final T_Resource r91 = new T_Resource("r91");
	public static final T_Resource r92 = new T_Resource("r92");
	public static final T_Resource r93 = new T_Resource("r93");
	public static final T_Resource r94 = new T_Resource("r94");
	public static final T_Resource r95 = new T_Resource("r95");
	public static final T_Resource r96 = new T_Resource("r96");
	public static final T_Resource r97 = new T_Resource("r97");
	public static final T_Resource r98 = new T_Resource("r98");
	public static final T_Resource r99 = new T_Resource("r99");
	public static final T_Resource r100 = new T_Resource("r100");
	public static final T_Resource r101 = new T_Resource("r101");
	public static final T_Resource r102 = new T_Resource("r102");
	public static final T_Resource r103 = new T_Resource("r103");
	public static final T_Resource r104 = new T_Resource("r104");
	public static final T_Resource r105 = new T_Resource("r105");
	public static final T_Resource r106 = new T_Resource("r106");
	public static final T_Resource r107 = new T_Resource("r107");
	public static final T_Resource r108 = new T_Resource("r108");
	public static final T_Resource r109 = new T_Resource("r109");
	public static final T_Resource r110 = new T_Resource("r110");
	public static final T_Resource r111 = new T_Resource("r111");
	public static final T_Resource r112 = new T_Resource("r112");
	public static final T_Resource r113 = new T_Resource("r113");
	public static final T_Resource r114 = new T_Resource("r114");
	public static final T_Resource r115 = new T_Resource("r115");
	public static final T_Resource r116 = new T_Resource("r116");
	public static final T_Resource r117 = new T_Resource("r117");
	public static final T_Resource r118 = new T_Resource("r118");
	public static final T_Resource r119 = new T_Resource("r119");
	public static final T_Resource r120 = new T_Resource("r120");
	public static final T_Resource r121 = new T_Resource("r121");
	public static final T_Resource r122 = new T_Resource("r122");
	public static final T_Resource r123 = new T_Resource("r123");
	public static final T_Resource r124 = new T_Resource("r124");
	public static final T_Resource r125 = new T_Resource("r125");
	public static final T_Resource r126 = new T_Resource("r126");
	public static final T_Resource r127 = new T_Resource("r127");
	public static final T_Resource r128 = new T_Resource("r128");
	public static final T_Resource r129 = new T_Resource("r129");
	public static final T_Resource r130 = new T_Resource("r130");
	public static final T_Resource r131 = new T_Resource("r131");
	public static final T_Resource r132 = new T_Resource("r132");
	public static final T_Resource r133 = new T_Resource("r133");
	public static final T_Resource r134 = new T_Resource("r134");
	public static final T_Resource r135 = new T_Resource("r135");
	public static final T_Resource r136 = new T_Resource("r136");
	public static final T_Resource r137 = new T_Resource("r137");
	public static final T_Resource r138 = new T_Resource("r138");
	public static final T_Resource r139 = new T_Resource("r139");
	public static final T_Resource r140 = new T_Resource("r140");
	public static final T_Resource r141 = new T_Resource("r141");
	public static final T_Resource r142 = new T_Resource("r142");
	

	static {

		E_Resource.THIS.register(T_Resource.getIndex(r1), r1);
		E_Resource.THIS.register(T_Resource.getIndex(r2), r2);
		E_Resource.THIS.register(T_Resource.getIndex(r3), r3);
		E_Resource.THIS.register(T_Resource.getIndex(r4), r4);
		E_Resource.THIS.register(T_Resource.getIndex(r5), r5);
		E_Resource.THIS.register(T_Resource.getIndex(r6), r6);
		E_Resource.THIS.register(T_Resource.getIndex(r7), r7);
		E_Resource.THIS.register(T_Resource.getIndex(r8), r8);
		E_Resource.THIS.register(T_Resource.getIndex(r9), r9);
		E_Resource.THIS.register(T_Resource.getIndex(r10), r10);
		E_Resource.THIS.register(T_Resource.getIndex(r11), r11);
		E_Resource.THIS.register(T_Resource.getIndex(r12), r12);
		E_Resource.THIS.register(T_Resource.getIndex(r13), r13);
		E_Resource.THIS.register(T_Resource.getIndex(r14), r14);
		E_Resource.THIS.register(T_Resource.getIndex(r15), r15);
		E_Resource.THIS.register(T_Resource.getIndex(r16), r16);
		E_Resource.THIS.register(T_Resource.getIndex(r17), r17);
		E_Resource.THIS.register(T_Resource.getIndex(r18), r18);
		E_Resource.THIS.register(T_Resource.getIndex(r19), r19);
		E_Resource.THIS.register(T_Resource.getIndex(r20), r20);
		E_Resource.THIS.register(T_Resource.getIndex(r21), r21);
		E_Resource.THIS.register(T_Resource.getIndex(r22), r22);
		E_Resource.THIS.register(T_Resource.getIndex(r23), r23);
		E_Resource.THIS.register(T_Resource.getIndex(r24), r24);
		E_Resource.THIS.register(T_Resource.getIndex(r25), r25);
		E_Resource.THIS.register(T_Resource.getIndex(r26), r26);
		E_Resource.THIS.register(T_Resource.getIndex(r27), r27);
		E_Resource.THIS.register(T_Resource.getIndex(r28), r28);
		E_Resource.THIS.register(T_Resource.getIndex(r29), r29);
		E_Resource.THIS.register(T_Resource.getIndex(r30), r30);
		E_Resource.THIS.register(T_Resource.getIndex(r31), r31);
		E_Resource.THIS.register(T_Resource.getIndex(r32), r32);
		E_Resource.THIS.register(T_Resource.getIndex(r33), r33);
		E_Resource.THIS.register(T_Resource.getIndex(r34), r34);
		E_Resource.THIS.register(T_Resource.getIndex(r35), r35);
		E_Resource.THIS.register(T_Resource.getIndex(r36), r36);
		E_Resource.THIS.register(T_Resource.getIndex(r37), r37);
		E_Resource.THIS.register(T_Resource.getIndex(r38), r38);
		E_Resource.THIS.register(T_Resource.getIndex(r39), r39);
		E_Resource.THIS.register(T_Resource.getIndex(r40), r40);
		E_Resource.THIS.register(T_Resource.getIndex(r41), r41);
		E_Resource.THIS.register(T_Resource.getIndex(r42), r42);
		E_Resource.THIS.register(T_Resource.getIndex(r43), r43);
		E_Resource.THIS.register(T_Resource.getIndex(r44), r44);
		E_Resource.THIS.register(T_Resource.getIndex(r45), r45);
		E_Resource.THIS.register(T_Resource.getIndex(r46), r46);
		E_Resource.THIS.register(T_Resource.getIndex(r47), r47);
		E_Resource.THIS.register(T_Resource.getIndex(r48), r48);
		E_Resource.THIS.register(T_Resource.getIndex(r49), r49);
		E_Resource.THIS.register(T_Resource.getIndex(r50), r50);
		E_Resource.THIS.register(T_Resource.getIndex(r51), r51);
		E_Resource.THIS.register(T_Resource.getIndex(r52), r52);
		E_Resource.THIS.register(T_Resource.getIndex(r53), r53);
		E_Resource.THIS.register(T_Resource.getIndex(r54), r54);
		E_Resource.THIS.register(T_Resource.getIndex(r55), r55);
		E_Resource.THIS.register(T_Resource.getIndex(r56), r56);
		E_Resource.THIS.register(T_Resource.getIndex(r57), r57);
		E_Resource.THIS.register(T_Resource.getIndex(r58), r58);
		E_Resource.THIS.register(T_Resource.getIndex(r59), r59);
		E_Resource.THIS.register(T_Resource.getIndex(r60), r60);
		E_Resource.THIS.register(T_Resource.getIndex(r61), r61);
		E_Resource.THIS.register(T_Resource.getIndex(r62), r62);
		E_Resource.THIS.register(T_Resource.getIndex(r63), r63);
		E_Resource.THIS.register(T_Resource.getIndex(r64), r64);
		E_Resource.THIS.register(T_Resource.getIndex(r65), r65);
		E_Resource.THIS.register(T_Resource.getIndex(r66), r66);
		E_Resource.THIS.register(T_Resource.getIndex(r67), r67);
		E_Resource.THIS.register(T_Resource.getIndex(r68), r68);
		E_Resource.THIS.register(T_Resource.getIndex(r69), r69);
		E_Resource.THIS.register(T_Resource.getIndex(r70), r70);
		E_Resource.THIS.register(T_Resource.getIndex(r71), r71);
		E_Resource.THIS.register(T_Resource.getIndex(r72), r72);
		E_Resource.THIS.register(T_Resource.getIndex(r73), r73);
		E_Resource.THIS.register(T_Resource.getIndex(r74), r74);
		E_Resource.THIS.register(T_Resource.getIndex(r75), r75);
		E_Resource.THIS.register(T_Resource.getIndex(r76), r76);
		E_Resource.THIS.register(T_Resource.getIndex(r77), r77);
		E_Resource.THIS.register(T_Resource.getIndex(r78), r78);
		E_Resource.THIS.register(T_Resource.getIndex(r79), r79);
		E_Resource.THIS.register(T_Resource.getIndex(r80), r80);
		E_Resource.THIS.register(T_Resource.getIndex(r81), r81);
		E_Resource.THIS.register(T_Resource.getIndex(r82), r82);
		E_Resource.THIS.register(T_Resource.getIndex(r83), r83);
		E_Resource.THIS.register(T_Resource.getIndex(r84), r84);
		E_Resource.THIS.register(T_Resource.getIndex(r85), r85);
		E_Resource.THIS.register(T_Resource.getIndex(r86), r86);
		E_Resource.THIS.register(T_Resource.getIndex(r87), r87);
		E_Resource.THIS.register(T_Resource.getIndex(r88), r88);
		E_Resource.THIS.register(T_Resource.getIndex(r89), r89);
		E_Resource.THIS.register(T_Resource.getIndex(r90), r90);
		E_Resource.THIS.register(T_Resource.getIndex(r91), r91);
		E_Resource.THIS.register(T_Resource.getIndex(r92), r92);
		E_Resource.THIS.register(T_Resource.getIndex(r93), r93);
		E_Resource.THIS.register(T_Resource.getIndex(r94), r94);
		E_Resource.THIS.register(T_Resource.getIndex(r95), r95);
		E_Resource.THIS.register(T_Resource.getIndex(r96), r96);
		E_Resource.THIS.register(T_Resource.getIndex(r97), r97);
		E_Resource.THIS.register(T_Resource.getIndex(r98), r98);
		E_Resource.THIS.register(T_Resource.getIndex(r99), r99);
		E_Resource.THIS.register(T_Resource.getIndex(r100), r100);
		E_Resource.THIS.register(T_Resource.getIndex(r101), r101);
		E_Resource.THIS.register(T_Resource.getIndex(r102), r102);
		E_Resource.THIS.register(T_Resource.getIndex(r103), r103);
		E_Resource.THIS.register(T_Resource.getIndex(r104), r104);
		E_Resource.THIS.register(T_Resource.getIndex(r105), r105);
		E_Resource.THIS.register(T_Resource.getIndex(r106), r106);
		E_Resource.THIS.register(T_Resource.getIndex(r107), r107);
		E_Resource.THIS.register(T_Resource.getIndex(r108), r108);
		E_Resource.THIS.register(T_Resource.getIndex(r109), r109);
		E_Resource.THIS.register(T_Resource.getIndex(r110), r110);
		E_Resource.THIS.register(T_Resource.getIndex(r111), r111);
		E_Resource.THIS.register(T_Resource.getIndex(r112), r112);
		E_Resource.THIS.register(T_Resource.getIndex(r113), r113);
		E_Resource.THIS.register(T_Resource.getIndex(r114), r114);
		E_Resource.THIS.register(T_Resource.getIndex(r115), r115);
		E_Resource.THIS.register(T_Resource.getIndex(r116), r116);
		E_Resource.THIS.register(T_Resource.getIndex(r117), r117);
		E_Resource.THIS.register(T_Resource.getIndex(r118), r118);
		E_Resource.THIS.register(T_Resource.getIndex(r119), r119);
		E_Resource.THIS.register(T_Resource.getIndex(r120), r120);
		E_Resource.THIS.register(T_Resource.getIndex(r121), r121);
		E_Resource.THIS.register(T_Resource.getIndex(r122), r122);
		E_Resource.THIS.register(T_Resource.getIndex(r123), r123);
		E_Resource.THIS.register(T_Resource.getIndex(r124), r124);
		E_Resource.THIS.register(T_Resource.getIndex(r125), r125);
		E_Resource.THIS.register(T_Resource.getIndex(r126), r126);
		E_Resource.THIS.register(T_Resource.getIndex(r127), r127);
		E_Resource.THIS.register(T_Resource.getIndex(r128), r128);
		E_Resource.THIS.register(T_Resource.getIndex(r129), r129);
		E_Resource.THIS.register(T_Resource.getIndex(r130), r130);
		E_Resource.THIS.register(T_Resource.getIndex(r131), r131);
		E_Resource.THIS.register(T_Resource.getIndex(r132), r132);
		E_Resource.THIS.register(T_Resource.getIndex(r133), r133);
		E_Resource.THIS.register(T_Resource.getIndex(r134), r134);
		E_Resource.THIS.register(T_Resource.getIndex(r135), r135);
		E_Resource.THIS.register(T_Resource.getIndex(r136), r136);
		E_Resource.THIS.register(T_Resource.getIndex(r137), r137);
		E_Resource.THIS.register(T_Resource.getIndex(r138), r138);
		E_Resource.THIS.register(T_Resource.getIndex(r139), r139);
		E_Resource.THIS.register(T_Resource.getIndex(r140), r140);
		E_Resource.THIS.register(T_Resource.getIndex(r141), r141);
		E_Resource.THIS.register(T_Resource.getIndex(r142), r142);
		
	}
		
	protected E_Resources() {
	}

}