call Sim-AUV-Problem1.bat
call Sim-AUV-Problem2.bat
call Sim-AUV-Problem3.bat
call Sim-AUV-Problem4.bat
call Sim-AUV-Problem5.bat
call Sim-AUV-Problem6.bat
call Sim-Perestroika-Problem1.bat
call Sim-Perestroika-Problem2.bat
call Sim-Perestroika-Problem3.bat
call Sim-Perestroika-Problem4.bat
call Sim-Perestroika-Problem5.bat
call Sim-Perestroika-Problem6.bat
