package cz.cuni.mff.perestroika.perestroika_problem_20_3_0_1_0_2_8;

import cz.cuni.mff.perestroika.domain.types.T_Location;
import cz.cuni.mff.perestroika.problem.E_Location;

public final class E_Locations {

	public static final T_Location l_1_1 = new T_Location("l-1-1");
	public static final T_Location l_1_2 = new T_Location("l-1-2");
	public static final T_Location l_1_3 = new T_Location("l-1-3");
	public static final T_Location l_1_4 = new T_Location("l-1-4");
	public static final T_Location l_1_5 = new T_Location("l-1-5");
	public static final T_Location l_1_6 = new T_Location("l-1-6");
	public static final T_Location l_1_7 = new T_Location("l-1-7");
	public static final T_Location l_1_8 = new T_Location("l-1-8");
	public static final T_Location l_1_9 = new T_Location("l-1-9");
	public static final T_Location l_1_10 = new T_Location("l-1-10");
	public static final T_Location l_1_11 = new T_Location("l-1-11");
	public static final T_Location l_1_12 = new T_Location("l-1-12");
	public static final T_Location l_1_13 = new T_Location("l-1-13");
	public static final T_Location l_1_14 = new T_Location("l-1-14");
	public static final T_Location l_1_15 = new T_Location("l-1-15");
	public static final T_Location l_1_16 = new T_Location("l-1-16");
	public static final T_Location l_1_17 = new T_Location("l-1-17");
	public static final T_Location l_1_18 = new T_Location("l-1-18");
	public static final T_Location l_1_19 = new T_Location("l-1-19");
	public static final T_Location l_1_20 = new T_Location("l-1-20");
	public static final T_Location l_2_1 = new T_Location("l-2-1");
	public static final T_Location l_2_2 = new T_Location("l-2-2");
	public static final T_Location l_2_3 = new T_Location("l-2-3");
	public static final T_Location l_2_4 = new T_Location("l-2-4");
	public static final T_Location l_2_5 = new T_Location("l-2-5");
	public static final T_Location l_2_6 = new T_Location("l-2-6");
	public static final T_Location l_2_7 = new T_Location("l-2-7");
	public static final T_Location l_2_8 = new T_Location("l-2-8");
	public static final T_Location l_2_9 = new T_Location("l-2-9");
	public static final T_Location l_2_10 = new T_Location("l-2-10");
	public static final T_Location l_2_11 = new T_Location("l-2-11");
	public static final T_Location l_2_12 = new T_Location("l-2-12");
	public static final T_Location l_2_13 = new T_Location("l-2-13");
	public static final T_Location l_2_14 = new T_Location("l-2-14");
	public static final T_Location l_2_15 = new T_Location("l-2-15");
	public static final T_Location l_2_16 = new T_Location("l-2-16");
	public static final T_Location l_2_17 = new T_Location("l-2-17");
	public static final T_Location l_2_18 = new T_Location("l-2-18");
	public static final T_Location l_2_19 = new T_Location("l-2-19");
	public static final T_Location l_2_20 = new T_Location("l-2-20");
	public static final T_Location l_3_1 = new T_Location("l-3-1");
	public static final T_Location l_3_2 = new T_Location("l-3-2");
	public static final T_Location l_3_3 = new T_Location("l-3-3");
	public static final T_Location l_3_4 = new T_Location("l-3-4");
	public static final T_Location l_3_5 = new T_Location("l-3-5");
	public static final T_Location l_3_6 = new T_Location("l-3-6");
	public static final T_Location l_3_7 = new T_Location("l-3-7");
	public static final T_Location l_3_8 = new T_Location("l-3-8");
	public static final T_Location l_3_9 = new T_Location("l-3-9");
	public static final T_Location l_3_10 = new T_Location("l-3-10");
	public static final T_Location l_3_11 = new T_Location("l-3-11");
	public static final T_Location l_3_12 = new T_Location("l-3-12");
	public static final T_Location l_3_13 = new T_Location("l-3-13");
	public static final T_Location l_3_14 = new T_Location("l-3-14");
	public static final T_Location l_3_15 = new T_Location("l-3-15");
	public static final T_Location l_3_16 = new T_Location("l-3-16");
	public static final T_Location l_3_17 = new T_Location("l-3-17");
	public static final T_Location l_3_18 = new T_Location("l-3-18");
	public static final T_Location l_3_19 = new T_Location("l-3-19");
	public static final T_Location l_3_20 = new T_Location("l-3-20");
	public static final T_Location l_4_1 = new T_Location("l-4-1");
	public static final T_Location l_4_2 = new T_Location("l-4-2");
	public static final T_Location l_4_3 = new T_Location("l-4-3");
	public static final T_Location l_4_4 = new T_Location("l-4-4");
	public static final T_Location l_4_5 = new T_Location("l-4-5");
	public static final T_Location l_4_6 = new T_Location("l-4-6");
	public static final T_Location l_4_7 = new T_Location("l-4-7");
	public static final T_Location l_4_8 = new T_Location("l-4-8");
	public static final T_Location l_4_9 = new T_Location("l-4-9");
	public static final T_Location l_4_10 = new T_Location("l-4-10");
	public static final T_Location l_4_11 = new T_Location("l-4-11");
	public static final T_Location l_4_12 = new T_Location("l-4-12");
	public static final T_Location l_4_13 = new T_Location("l-4-13");
	public static final T_Location l_4_14 = new T_Location("l-4-14");
	public static final T_Location l_4_15 = new T_Location("l-4-15");
	public static final T_Location l_4_16 = new T_Location("l-4-16");
	public static final T_Location l_4_17 = new T_Location("l-4-17");
	public static final T_Location l_4_18 = new T_Location("l-4-18");
	public static final T_Location l_4_19 = new T_Location("l-4-19");
	public static final T_Location l_4_20 = new T_Location("l-4-20");
	public static final T_Location l_5_1 = new T_Location("l-5-1");
	public static final T_Location l_5_2 = new T_Location("l-5-2");
	public static final T_Location l_5_3 = new T_Location("l-5-3");
	public static final T_Location l_5_4 = new T_Location("l-5-4");
	public static final T_Location l_5_5 = new T_Location("l-5-5");
	public static final T_Location l_5_6 = new T_Location("l-5-6");
	public static final T_Location l_5_7 = new T_Location("l-5-7");
	public static final T_Location l_5_8 = new T_Location("l-5-8");
	public static final T_Location l_5_9 = new T_Location("l-5-9");
	public static final T_Location l_5_10 = new T_Location("l-5-10");
	public static final T_Location l_5_11 = new T_Location("l-5-11");
	public static final T_Location l_5_12 = new T_Location("l-5-12");
	public static final T_Location l_5_13 = new T_Location("l-5-13");
	public static final T_Location l_5_14 = new T_Location("l-5-14");
	public static final T_Location l_5_15 = new T_Location("l-5-15");
	public static final T_Location l_5_16 = new T_Location("l-5-16");
	public static final T_Location l_5_17 = new T_Location("l-5-17");
	public static final T_Location l_5_18 = new T_Location("l-5-18");
	public static final T_Location l_5_19 = new T_Location("l-5-19");
	public static final T_Location l_5_20 = new T_Location("l-5-20");
	public static final T_Location l_6_1 = new T_Location("l-6-1");
	public static final T_Location l_6_2 = new T_Location("l-6-2");
	public static final T_Location l_6_3 = new T_Location("l-6-3");
	public static final T_Location l_6_4 = new T_Location("l-6-4");
	public static final T_Location l_6_5 = new T_Location("l-6-5");
	public static final T_Location l_6_6 = new T_Location("l-6-6");
	public static final T_Location l_6_7 = new T_Location("l-6-7");
	public static final T_Location l_6_8 = new T_Location("l-6-8");
	public static final T_Location l_6_9 = new T_Location("l-6-9");
	public static final T_Location l_6_10 = new T_Location("l-6-10");
	public static final T_Location l_6_11 = new T_Location("l-6-11");
	public static final T_Location l_6_12 = new T_Location("l-6-12");
	public static final T_Location l_6_13 = new T_Location("l-6-13");
	public static final T_Location l_6_14 = new T_Location("l-6-14");
	public static final T_Location l_6_15 = new T_Location("l-6-15");
	public static final T_Location l_6_16 = new T_Location("l-6-16");
	public static final T_Location l_6_17 = new T_Location("l-6-17");
	public static final T_Location l_6_18 = new T_Location("l-6-18");
	public static final T_Location l_6_19 = new T_Location("l-6-19");
	public static final T_Location l_6_20 = new T_Location("l-6-20");
	public static final T_Location l_7_1 = new T_Location("l-7-1");
	public static final T_Location l_7_2 = new T_Location("l-7-2");
	public static final T_Location l_7_3 = new T_Location("l-7-3");
	public static final T_Location l_7_4 = new T_Location("l-7-4");
	public static final T_Location l_7_5 = new T_Location("l-7-5");
	public static final T_Location l_7_6 = new T_Location("l-7-6");
	public static final T_Location l_7_7 = new T_Location("l-7-7");
	public static final T_Location l_7_8 = new T_Location("l-7-8");
	public static final T_Location l_7_9 = new T_Location("l-7-9");
	public static final T_Location l_7_10 = new T_Location("l-7-10");
	public static final T_Location l_7_11 = new T_Location("l-7-11");
	public static final T_Location l_7_12 = new T_Location("l-7-12");
	public static final T_Location l_7_13 = new T_Location("l-7-13");
	public static final T_Location l_7_14 = new T_Location("l-7-14");
	public static final T_Location l_7_15 = new T_Location("l-7-15");
	public static final T_Location l_7_16 = new T_Location("l-7-16");
	public static final T_Location l_7_17 = new T_Location("l-7-17");
	public static final T_Location l_7_18 = new T_Location("l-7-18");
	public static final T_Location l_7_19 = new T_Location("l-7-19");
	public static final T_Location l_7_20 = new T_Location("l-7-20");
	public static final T_Location l_8_1 = new T_Location("l-8-1");
	public static final T_Location l_8_2 = new T_Location("l-8-2");
	public static final T_Location l_8_3 = new T_Location("l-8-3");
	public static final T_Location l_8_4 = new T_Location("l-8-4");
	public static final T_Location l_8_5 = new T_Location("l-8-5");
	public static final T_Location l_8_6 = new T_Location("l-8-6");
	public static final T_Location l_8_7 = new T_Location("l-8-7");
	public static final T_Location l_8_8 = new T_Location("l-8-8");
	public static final T_Location l_8_9 = new T_Location("l-8-9");
	public static final T_Location l_8_10 = new T_Location("l-8-10");
	public static final T_Location l_8_11 = new T_Location("l-8-11");
	public static final T_Location l_8_12 = new T_Location("l-8-12");
	public static final T_Location l_8_13 = new T_Location("l-8-13");
	public static final T_Location l_8_14 = new T_Location("l-8-14");
	public static final T_Location l_8_15 = new T_Location("l-8-15");
	public static final T_Location l_8_16 = new T_Location("l-8-16");
	public static final T_Location l_8_17 = new T_Location("l-8-17");
	public static final T_Location l_8_18 = new T_Location("l-8-18");
	public static final T_Location l_8_19 = new T_Location("l-8-19");
	public static final T_Location l_8_20 = new T_Location("l-8-20");
	public static final T_Location l_9_1 = new T_Location("l-9-1");
	public static final T_Location l_9_2 = new T_Location("l-9-2");
	public static final T_Location l_9_3 = new T_Location("l-9-3");
	public static final T_Location l_9_4 = new T_Location("l-9-4");
	public static final T_Location l_9_5 = new T_Location("l-9-5");
	public static final T_Location l_9_6 = new T_Location("l-9-6");
	public static final T_Location l_9_7 = new T_Location("l-9-7");
	public static final T_Location l_9_8 = new T_Location("l-9-8");
	public static final T_Location l_9_9 = new T_Location("l-9-9");
	public static final T_Location l_9_10 = new T_Location("l-9-10");
	public static final T_Location l_9_11 = new T_Location("l-9-11");
	public static final T_Location l_9_12 = new T_Location("l-9-12");
	public static final T_Location l_9_13 = new T_Location("l-9-13");
	public static final T_Location l_9_14 = new T_Location("l-9-14");
	public static final T_Location l_9_15 = new T_Location("l-9-15");
	public static final T_Location l_9_16 = new T_Location("l-9-16");
	public static final T_Location l_9_17 = new T_Location("l-9-17");
	public static final T_Location l_9_18 = new T_Location("l-9-18");
	public static final T_Location l_9_19 = new T_Location("l-9-19");
	public static final T_Location l_9_20 = new T_Location("l-9-20");
	public static final T_Location l_10_1 = new T_Location("l-10-1");
	public static final T_Location l_10_2 = new T_Location("l-10-2");
	public static final T_Location l_10_3 = new T_Location("l-10-3");
	public static final T_Location l_10_4 = new T_Location("l-10-4");
	public static final T_Location l_10_5 = new T_Location("l-10-5");
	public static final T_Location l_10_6 = new T_Location("l-10-6");
	public static final T_Location l_10_7 = new T_Location("l-10-7");
	public static final T_Location l_10_8 = new T_Location("l-10-8");
	public static final T_Location l_10_9 = new T_Location("l-10-9");
	public static final T_Location l_10_10 = new T_Location("l-10-10");
	public static final T_Location l_10_11 = new T_Location("l-10-11");
	public static final T_Location l_10_12 = new T_Location("l-10-12");
	public static final T_Location l_10_13 = new T_Location("l-10-13");
	public static final T_Location l_10_14 = new T_Location("l-10-14");
	public static final T_Location l_10_15 = new T_Location("l-10-15");
	public static final T_Location l_10_16 = new T_Location("l-10-16");
	public static final T_Location l_10_17 = new T_Location("l-10-17");
	public static final T_Location l_10_18 = new T_Location("l-10-18");
	public static final T_Location l_10_19 = new T_Location("l-10-19");
	public static final T_Location l_10_20 = new T_Location("l-10-20");
	public static final T_Location l_11_1 = new T_Location("l-11-1");
	public static final T_Location l_11_2 = new T_Location("l-11-2");
	public static final T_Location l_11_3 = new T_Location("l-11-3");
	public static final T_Location l_11_4 = new T_Location("l-11-4");
	public static final T_Location l_11_5 = new T_Location("l-11-5");
	public static final T_Location l_11_6 = new T_Location("l-11-6");
	public static final T_Location l_11_7 = new T_Location("l-11-7");
	public static final T_Location l_11_8 = new T_Location("l-11-8");
	public static final T_Location l_11_9 = new T_Location("l-11-9");
	public static final T_Location l_11_10 = new T_Location("l-11-10");
	public static final T_Location l_11_11 = new T_Location("l-11-11");
	public static final T_Location l_11_12 = new T_Location("l-11-12");
	public static final T_Location l_11_13 = new T_Location("l-11-13");
	public static final T_Location l_11_14 = new T_Location("l-11-14");
	public static final T_Location l_11_15 = new T_Location("l-11-15");
	public static final T_Location l_11_16 = new T_Location("l-11-16");
	public static final T_Location l_11_17 = new T_Location("l-11-17");
	public static final T_Location l_11_18 = new T_Location("l-11-18");
	public static final T_Location l_11_19 = new T_Location("l-11-19");
	public static final T_Location l_11_20 = new T_Location("l-11-20");
	public static final T_Location l_12_1 = new T_Location("l-12-1");
	public static final T_Location l_12_2 = new T_Location("l-12-2");
	public static final T_Location l_12_3 = new T_Location("l-12-3");
	public static final T_Location l_12_4 = new T_Location("l-12-4");
	public static final T_Location l_12_5 = new T_Location("l-12-5");
	public static final T_Location l_12_6 = new T_Location("l-12-6");
	public static final T_Location l_12_7 = new T_Location("l-12-7");
	public static final T_Location l_12_8 = new T_Location("l-12-8");
	public static final T_Location l_12_9 = new T_Location("l-12-9");
	public static final T_Location l_12_10 = new T_Location("l-12-10");
	public static final T_Location l_12_11 = new T_Location("l-12-11");
	public static final T_Location l_12_12 = new T_Location("l-12-12");
	public static final T_Location l_12_13 = new T_Location("l-12-13");
	public static final T_Location l_12_14 = new T_Location("l-12-14");
	public static final T_Location l_12_15 = new T_Location("l-12-15");
	public static final T_Location l_12_16 = new T_Location("l-12-16");
	public static final T_Location l_12_17 = new T_Location("l-12-17");
	public static final T_Location l_12_18 = new T_Location("l-12-18");
	public static final T_Location l_12_19 = new T_Location("l-12-19");
	public static final T_Location l_12_20 = new T_Location("l-12-20");
	public static final T_Location l_13_1 = new T_Location("l-13-1");
	public static final T_Location l_13_2 = new T_Location("l-13-2");
	public static final T_Location l_13_3 = new T_Location("l-13-3");
	public static final T_Location l_13_4 = new T_Location("l-13-4");
	public static final T_Location l_13_5 = new T_Location("l-13-5");
	public static final T_Location l_13_6 = new T_Location("l-13-6");
	public static final T_Location l_13_7 = new T_Location("l-13-7");
	public static final T_Location l_13_8 = new T_Location("l-13-8");
	public static final T_Location l_13_9 = new T_Location("l-13-9");
	public static final T_Location l_13_10 = new T_Location("l-13-10");
	public static final T_Location l_13_11 = new T_Location("l-13-11");
	public static final T_Location l_13_12 = new T_Location("l-13-12");
	public static final T_Location l_13_13 = new T_Location("l-13-13");
	public static final T_Location l_13_14 = new T_Location("l-13-14");
	public static final T_Location l_13_15 = new T_Location("l-13-15");
	public static final T_Location l_13_16 = new T_Location("l-13-16");
	public static final T_Location l_13_17 = new T_Location("l-13-17");
	public static final T_Location l_13_18 = new T_Location("l-13-18");
	public static final T_Location l_13_19 = new T_Location("l-13-19");
	public static final T_Location l_13_20 = new T_Location("l-13-20");
	public static final T_Location l_14_1 = new T_Location("l-14-1");
	public static final T_Location l_14_2 = new T_Location("l-14-2");
	public static final T_Location l_14_3 = new T_Location("l-14-3");
	public static final T_Location l_14_4 = new T_Location("l-14-4");
	public static final T_Location l_14_5 = new T_Location("l-14-5");
	public static final T_Location l_14_6 = new T_Location("l-14-6");
	public static final T_Location l_14_7 = new T_Location("l-14-7");
	public static final T_Location l_14_8 = new T_Location("l-14-8");
	public static final T_Location l_14_9 = new T_Location("l-14-9");
	public static final T_Location l_14_10 = new T_Location("l-14-10");
	public static final T_Location l_14_11 = new T_Location("l-14-11");
	public static final T_Location l_14_12 = new T_Location("l-14-12");
	public static final T_Location l_14_13 = new T_Location("l-14-13");
	public static final T_Location l_14_14 = new T_Location("l-14-14");
	public static final T_Location l_14_15 = new T_Location("l-14-15");
	public static final T_Location l_14_16 = new T_Location("l-14-16");
	public static final T_Location l_14_17 = new T_Location("l-14-17");
	public static final T_Location l_14_18 = new T_Location("l-14-18");
	public static final T_Location l_14_19 = new T_Location("l-14-19");
	public static final T_Location l_14_20 = new T_Location("l-14-20");
	public static final T_Location l_15_1 = new T_Location("l-15-1");
	public static final T_Location l_15_2 = new T_Location("l-15-2");
	public static final T_Location l_15_3 = new T_Location("l-15-3");
	public static final T_Location l_15_4 = new T_Location("l-15-4");
	public static final T_Location l_15_5 = new T_Location("l-15-5");
	public static final T_Location l_15_6 = new T_Location("l-15-6");
	public static final T_Location l_15_7 = new T_Location("l-15-7");
	public static final T_Location l_15_8 = new T_Location("l-15-8");
	public static final T_Location l_15_9 = new T_Location("l-15-9");
	public static final T_Location l_15_10 = new T_Location("l-15-10");
	public static final T_Location l_15_11 = new T_Location("l-15-11");
	public static final T_Location l_15_12 = new T_Location("l-15-12");
	public static final T_Location l_15_13 = new T_Location("l-15-13");
	public static final T_Location l_15_14 = new T_Location("l-15-14");
	public static final T_Location l_15_15 = new T_Location("l-15-15");
	public static final T_Location l_15_16 = new T_Location("l-15-16");
	public static final T_Location l_15_17 = new T_Location("l-15-17");
	public static final T_Location l_15_18 = new T_Location("l-15-18");
	public static final T_Location l_15_19 = new T_Location("l-15-19");
	public static final T_Location l_15_20 = new T_Location("l-15-20");
	public static final T_Location l_16_1 = new T_Location("l-16-1");
	public static final T_Location l_16_2 = new T_Location("l-16-2");
	public static final T_Location l_16_3 = new T_Location("l-16-3");
	public static final T_Location l_16_4 = new T_Location("l-16-4");
	public static final T_Location l_16_5 = new T_Location("l-16-5");
	public static final T_Location l_16_6 = new T_Location("l-16-6");
	public static final T_Location l_16_7 = new T_Location("l-16-7");
	public static final T_Location l_16_8 = new T_Location("l-16-8");
	public static final T_Location l_16_9 = new T_Location("l-16-9");
	public static final T_Location l_16_10 = new T_Location("l-16-10");
	public static final T_Location l_16_11 = new T_Location("l-16-11");
	public static final T_Location l_16_12 = new T_Location("l-16-12");
	public static final T_Location l_16_13 = new T_Location("l-16-13");
	public static final T_Location l_16_14 = new T_Location("l-16-14");
	public static final T_Location l_16_15 = new T_Location("l-16-15");
	public static final T_Location l_16_16 = new T_Location("l-16-16");
	public static final T_Location l_16_17 = new T_Location("l-16-17");
	public static final T_Location l_16_18 = new T_Location("l-16-18");
	public static final T_Location l_16_19 = new T_Location("l-16-19");
	public static final T_Location l_16_20 = new T_Location("l-16-20");
	public static final T_Location l_17_1 = new T_Location("l-17-1");
	public static final T_Location l_17_2 = new T_Location("l-17-2");
	public static final T_Location l_17_3 = new T_Location("l-17-3");
	public static final T_Location l_17_4 = new T_Location("l-17-4");
	public static final T_Location l_17_5 = new T_Location("l-17-5");
	public static final T_Location l_17_6 = new T_Location("l-17-6");
	public static final T_Location l_17_7 = new T_Location("l-17-7");
	public static final T_Location l_17_8 = new T_Location("l-17-8");
	public static final T_Location l_17_9 = new T_Location("l-17-9");
	public static final T_Location l_17_10 = new T_Location("l-17-10");
	public static final T_Location l_17_11 = new T_Location("l-17-11");
	public static final T_Location l_17_12 = new T_Location("l-17-12");
	public static final T_Location l_17_13 = new T_Location("l-17-13");
	public static final T_Location l_17_14 = new T_Location("l-17-14");
	public static final T_Location l_17_15 = new T_Location("l-17-15");
	public static final T_Location l_17_16 = new T_Location("l-17-16");
	public static final T_Location l_17_17 = new T_Location("l-17-17");
	public static final T_Location l_17_18 = new T_Location("l-17-18");
	public static final T_Location l_17_19 = new T_Location("l-17-19");
	public static final T_Location l_17_20 = new T_Location("l-17-20");
	public static final T_Location l_18_1 = new T_Location("l-18-1");
	public static final T_Location l_18_2 = new T_Location("l-18-2");
	public static final T_Location l_18_3 = new T_Location("l-18-3");
	public static final T_Location l_18_4 = new T_Location("l-18-4");
	public static final T_Location l_18_5 = new T_Location("l-18-5");
	public static final T_Location l_18_6 = new T_Location("l-18-6");
	public static final T_Location l_18_7 = new T_Location("l-18-7");
	public static final T_Location l_18_8 = new T_Location("l-18-8");
	public static final T_Location l_18_9 = new T_Location("l-18-9");
	public static final T_Location l_18_10 = new T_Location("l-18-10");
	public static final T_Location l_18_11 = new T_Location("l-18-11");
	public static final T_Location l_18_12 = new T_Location("l-18-12");
	public static final T_Location l_18_13 = new T_Location("l-18-13");
	public static final T_Location l_18_14 = new T_Location("l-18-14");
	public static final T_Location l_18_15 = new T_Location("l-18-15");
	public static final T_Location l_18_16 = new T_Location("l-18-16");
	public static final T_Location l_18_17 = new T_Location("l-18-17");
	public static final T_Location l_18_18 = new T_Location("l-18-18");
	public static final T_Location l_18_19 = new T_Location("l-18-19");
	public static final T_Location l_18_20 = new T_Location("l-18-20");
	public static final T_Location l_19_1 = new T_Location("l-19-1");
	public static final T_Location l_19_2 = new T_Location("l-19-2");
	public static final T_Location l_19_3 = new T_Location("l-19-3");
	public static final T_Location l_19_4 = new T_Location("l-19-4");
	public static final T_Location l_19_5 = new T_Location("l-19-5");
	public static final T_Location l_19_6 = new T_Location("l-19-6");
	public static final T_Location l_19_7 = new T_Location("l-19-7");
	public static final T_Location l_19_8 = new T_Location("l-19-8");
	public static final T_Location l_19_9 = new T_Location("l-19-9");
	public static final T_Location l_19_10 = new T_Location("l-19-10");
	public static final T_Location l_19_11 = new T_Location("l-19-11");
	public static final T_Location l_19_12 = new T_Location("l-19-12");
	public static final T_Location l_19_13 = new T_Location("l-19-13");
	public static final T_Location l_19_14 = new T_Location("l-19-14");
	public static final T_Location l_19_15 = new T_Location("l-19-15");
	public static final T_Location l_19_16 = new T_Location("l-19-16");
	public static final T_Location l_19_17 = new T_Location("l-19-17");
	public static final T_Location l_19_18 = new T_Location("l-19-18");
	public static final T_Location l_19_19 = new T_Location("l-19-19");
	public static final T_Location l_19_20 = new T_Location("l-19-20");
	public static final T_Location l_20_1 = new T_Location("l-20-1");
	public static final T_Location l_20_2 = new T_Location("l-20-2");
	public static final T_Location l_20_3 = new T_Location("l-20-3");
	public static final T_Location l_20_4 = new T_Location("l-20-4");
	public static final T_Location l_20_5 = new T_Location("l-20-5");
	public static final T_Location l_20_6 = new T_Location("l-20-6");
	public static final T_Location l_20_7 = new T_Location("l-20-7");
	public static final T_Location l_20_8 = new T_Location("l-20-8");
	public static final T_Location l_20_9 = new T_Location("l-20-9");
	public static final T_Location l_20_10 = new T_Location("l-20-10");
	public static final T_Location l_20_11 = new T_Location("l-20-11");
	public static final T_Location l_20_12 = new T_Location("l-20-12");
	public static final T_Location l_20_13 = new T_Location("l-20-13");
	public static final T_Location l_20_14 = new T_Location("l-20-14");
	public static final T_Location l_20_15 = new T_Location("l-20-15");
	public static final T_Location l_20_16 = new T_Location("l-20-16");
	public static final T_Location l_20_17 = new T_Location("l-20-17");
	public static final T_Location l_20_18 = new T_Location("l-20-18");
	public static final T_Location l_20_19 = new T_Location("l-20-19");
	public static final T_Location l_20_20 = new T_Location("l-20-20");
	

	static {

		E_Location.THIS.register(T_Location.getIndex(l_1_1), l_1_1);
		E_Location.THIS.register(T_Location.getIndex(l_1_2), l_1_2);
		E_Location.THIS.register(T_Location.getIndex(l_1_3), l_1_3);
		E_Location.THIS.register(T_Location.getIndex(l_1_4), l_1_4);
		E_Location.THIS.register(T_Location.getIndex(l_1_5), l_1_5);
		E_Location.THIS.register(T_Location.getIndex(l_1_6), l_1_6);
		E_Location.THIS.register(T_Location.getIndex(l_1_7), l_1_7);
		E_Location.THIS.register(T_Location.getIndex(l_1_8), l_1_8);
		E_Location.THIS.register(T_Location.getIndex(l_1_9), l_1_9);
		E_Location.THIS.register(T_Location.getIndex(l_1_10), l_1_10);
		E_Location.THIS.register(T_Location.getIndex(l_1_11), l_1_11);
		E_Location.THIS.register(T_Location.getIndex(l_1_12), l_1_12);
		E_Location.THIS.register(T_Location.getIndex(l_1_13), l_1_13);
		E_Location.THIS.register(T_Location.getIndex(l_1_14), l_1_14);
		E_Location.THIS.register(T_Location.getIndex(l_1_15), l_1_15);
		E_Location.THIS.register(T_Location.getIndex(l_1_16), l_1_16);
		E_Location.THIS.register(T_Location.getIndex(l_1_17), l_1_17);
		E_Location.THIS.register(T_Location.getIndex(l_1_18), l_1_18);
		E_Location.THIS.register(T_Location.getIndex(l_1_19), l_1_19);
		E_Location.THIS.register(T_Location.getIndex(l_1_20), l_1_20);
		E_Location.THIS.register(T_Location.getIndex(l_2_1), l_2_1);
		E_Location.THIS.register(T_Location.getIndex(l_2_2), l_2_2);
		E_Location.THIS.register(T_Location.getIndex(l_2_3), l_2_3);
		E_Location.THIS.register(T_Location.getIndex(l_2_4), l_2_4);
		E_Location.THIS.register(T_Location.getIndex(l_2_5), l_2_5);
		E_Location.THIS.register(T_Location.getIndex(l_2_6), l_2_6);
		E_Location.THIS.register(T_Location.getIndex(l_2_7), l_2_7);
		E_Location.THIS.register(T_Location.getIndex(l_2_8), l_2_8);
		E_Location.THIS.register(T_Location.getIndex(l_2_9), l_2_9);
		E_Location.THIS.register(T_Location.getIndex(l_2_10), l_2_10);
		E_Location.THIS.register(T_Location.getIndex(l_2_11), l_2_11);
		E_Location.THIS.register(T_Location.getIndex(l_2_12), l_2_12);
		E_Location.THIS.register(T_Location.getIndex(l_2_13), l_2_13);
		E_Location.THIS.register(T_Location.getIndex(l_2_14), l_2_14);
		E_Location.THIS.register(T_Location.getIndex(l_2_15), l_2_15);
		E_Location.THIS.register(T_Location.getIndex(l_2_16), l_2_16);
		E_Location.THIS.register(T_Location.getIndex(l_2_17), l_2_17);
		E_Location.THIS.register(T_Location.getIndex(l_2_18), l_2_18);
		E_Location.THIS.register(T_Location.getIndex(l_2_19), l_2_19);
		E_Location.THIS.register(T_Location.getIndex(l_2_20), l_2_20);
		E_Location.THIS.register(T_Location.getIndex(l_3_1), l_3_1);
		E_Location.THIS.register(T_Location.getIndex(l_3_2), l_3_2);
		E_Location.THIS.register(T_Location.getIndex(l_3_3), l_3_3);
		E_Location.THIS.register(T_Location.getIndex(l_3_4), l_3_4);
		E_Location.THIS.register(T_Location.getIndex(l_3_5), l_3_5);
		E_Location.THIS.register(T_Location.getIndex(l_3_6), l_3_6);
		E_Location.THIS.register(T_Location.getIndex(l_3_7), l_3_7);
		E_Location.THIS.register(T_Location.getIndex(l_3_8), l_3_8);
		E_Location.THIS.register(T_Location.getIndex(l_3_9), l_3_9);
		E_Location.THIS.register(T_Location.getIndex(l_3_10), l_3_10);
		E_Location.THIS.register(T_Location.getIndex(l_3_11), l_3_11);
		E_Location.THIS.register(T_Location.getIndex(l_3_12), l_3_12);
		E_Location.THIS.register(T_Location.getIndex(l_3_13), l_3_13);
		E_Location.THIS.register(T_Location.getIndex(l_3_14), l_3_14);
		E_Location.THIS.register(T_Location.getIndex(l_3_15), l_3_15);
		E_Location.THIS.register(T_Location.getIndex(l_3_16), l_3_16);
		E_Location.THIS.register(T_Location.getIndex(l_3_17), l_3_17);
		E_Location.THIS.register(T_Location.getIndex(l_3_18), l_3_18);
		E_Location.THIS.register(T_Location.getIndex(l_3_19), l_3_19);
		E_Location.THIS.register(T_Location.getIndex(l_3_20), l_3_20);
		E_Location.THIS.register(T_Location.getIndex(l_4_1), l_4_1);
		E_Location.THIS.register(T_Location.getIndex(l_4_2), l_4_2);
		E_Location.THIS.register(T_Location.getIndex(l_4_3), l_4_3);
		E_Location.THIS.register(T_Location.getIndex(l_4_4), l_4_4);
		E_Location.THIS.register(T_Location.getIndex(l_4_5), l_4_5);
		E_Location.THIS.register(T_Location.getIndex(l_4_6), l_4_6);
		E_Location.THIS.register(T_Location.getIndex(l_4_7), l_4_7);
		E_Location.THIS.register(T_Location.getIndex(l_4_8), l_4_8);
		E_Location.THIS.register(T_Location.getIndex(l_4_9), l_4_9);
		E_Location.THIS.register(T_Location.getIndex(l_4_10), l_4_10);
		E_Location.THIS.register(T_Location.getIndex(l_4_11), l_4_11);
		E_Location.THIS.register(T_Location.getIndex(l_4_12), l_4_12);
		E_Location.THIS.register(T_Location.getIndex(l_4_13), l_4_13);
		E_Location.THIS.register(T_Location.getIndex(l_4_14), l_4_14);
		E_Location.THIS.register(T_Location.getIndex(l_4_15), l_4_15);
		E_Location.THIS.register(T_Location.getIndex(l_4_16), l_4_16);
		E_Location.THIS.register(T_Location.getIndex(l_4_17), l_4_17);
		E_Location.THIS.register(T_Location.getIndex(l_4_18), l_4_18);
		E_Location.THIS.register(T_Location.getIndex(l_4_19), l_4_19);
		E_Location.THIS.register(T_Location.getIndex(l_4_20), l_4_20);
		E_Location.THIS.register(T_Location.getIndex(l_5_1), l_5_1);
		E_Location.THIS.register(T_Location.getIndex(l_5_2), l_5_2);
		E_Location.THIS.register(T_Location.getIndex(l_5_3), l_5_3);
		E_Location.THIS.register(T_Location.getIndex(l_5_4), l_5_4);
		E_Location.THIS.register(T_Location.getIndex(l_5_5), l_5_5);
		E_Location.THIS.register(T_Location.getIndex(l_5_6), l_5_6);
		E_Location.THIS.register(T_Location.getIndex(l_5_7), l_5_7);
		E_Location.THIS.register(T_Location.getIndex(l_5_8), l_5_8);
		E_Location.THIS.register(T_Location.getIndex(l_5_9), l_5_9);
		E_Location.THIS.register(T_Location.getIndex(l_5_10), l_5_10);
		E_Location.THIS.register(T_Location.getIndex(l_5_11), l_5_11);
		E_Location.THIS.register(T_Location.getIndex(l_5_12), l_5_12);
		E_Location.THIS.register(T_Location.getIndex(l_5_13), l_5_13);
		E_Location.THIS.register(T_Location.getIndex(l_5_14), l_5_14);
		E_Location.THIS.register(T_Location.getIndex(l_5_15), l_5_15);
		E_Location.THIS.register(T_Location.getIndex(l_5_16), l_5_16);
		E_Location.THIS.register(T_Location.getIndex(l_5_17), l_5_17);
		E_Location.THIS.register(T_Location.getIndex(l_5_18), l_5_18);
		E_Location.THIS.register(T_Location.getIndex(l_5_19), l_5_19);
		E_Location.THIS.register(T_Location.getIndex(l_5_20), l_5_20);
		E_Location.THIS.register(T_Location.getIndex(l_6_1), l_6_1);
		E_Location.THIS.register(T_Location.getIndex(l_6_2), l_6_2);
		E_Location.THIS.register(T_Location.getIndex(l_6_3), l_6_3);
		E_Location.THIS.register(T_Location.getIndex(l_6_4), l_6_4);
		E_Location.THIS.register(T_Location.getIndex(l_6_5), l_6_5);
		E_Location.THIS.register(T_Location.getIndex(l_6_6), l_6_6);
		E_Location.THIS.register(T_Location.getIndex(l_6_7), l_6_7);
		E_Location.THIS.register(T_Location.getIndex(l_6_8), l_6_8);
		E_Location.THIS.register(T_Location.getIndex(l_6_9), l_6_9);
		E_Location.THIS.register(T_Location.getIndex(l_6_10), l_6_10);
		E_Location.THIS.register(T_Location.getIndex(l_6_11), l_6_11);
		E_Location.THIS.register(T_Location.getIndex(l_6_12), l_6_12);
		E_Location.THIS.register(T_Location.getIndex(l_6_13), l_6_13);
		E_Location.THIS.register(T_Location.getIndex(l_6_14), l_6_14);
		E_Location.THIS.register(T_Location.getIndex(l_6_15), l_6_15);
		E_Location.THIS.register(T_Location.getIndex(l_6_16), l_6_16);
		E_Location.THIS.register(T_Location.getIndex(l_6_17), l_6_17);
		E_Location.THIS.register(T_Location.getIndex(l_6_18), l_6_18);
		E_Location.THIS.register(T_Location.getIndex(l_6_19), l_6_19);
		E_Location.THIS.register(T_Location.getIndex(l_6_20), l_6_20);
		E_Location.THIS.register(T_Location.getIndex(l_7_1), l_7_1);
		E_Location.THIS.register(T_Location.getIndex(l_7_2), l_7_2);
		E_Location.THIS.register(T_Location.getIndex(l_7_3), l_7_3);
		E_Location.THIS.register(T_Location.getIndex(l_7_4), l_7_4);
		E_Location.THIS.register(T_Location.getIndex(l_7_5), l_7_5);
		E_Location.THIS.register(T_Location.getIndex(l_7_6), l_7_6);
		E_Location.THIS.register(T_Location.getIndex(l_7_7), l_7_7);
		E_Location.THIS.register(T_Location.getIndex(l_7_8), l_7_8);
		E_Location.THIS.register(T_Location.getIndex(l_7_9), l_7_9);
		E_Location.THIS.register(T_Location.getIndex(l_7_10), l_7_10);
		E_Location.THIS.register(T_Location.getIndex(l_7_11), l_7_11);
		E_Location.THIS.register(T_Location.getIndex(l_7_12), l_7_12);
		E_Location.THIS.register(T_Location.getIndex(l_7_13), l_7_13);
		E_Location.THIS.register(T_Location.getIndex(l_7_14), l_7_14);
		E_Location.THIS.register(T_Location.getIndex(l_7_15), l_7_15);
		E_Location.THIS.register(T_Location.getIndex(l_7_16), l_7_16);
		E_Location.THIS.register(T_Location.getIndex(l_7_17), l_7_17);
		E_Location.THIS.register(T_Location.getIndex(l_7_18), l_7_18);
		E_Location.THIS.register(T_Location.getIndex(l_7_19), l_7_19);
		E_Location.THIS.register(T_Location.getIndex(l_7_20), l_7_20);
		E_Location.THIS.register(T_Location.getIndex(l_8_1), l_8_1);
		E_Location.THIS.register(T_Location.getIndex(l_8_2), l_8_2);
		E_Location.THIS.register(T_Location.getIndex(l_8_3), l_8_3);
		E_Location.THIS.register(T_Location.getIndex(l_8_4), l_8_4);
		E_Location.THIS.register(T_Location.getIndex(l_8_5), l_8_5);
		E_Location.THIS.register(T_Location.getIndex(l_8_6), l_8_6);
		E_Location.THIS.register(T_Location.getIndex(l_8_7), l_8_7);
		E_Location.THIS.register(T_Location.getIndex(l_8_8), l_8_8);
		E_Location.THIS.register(T_Location.getIndex(l_8_9), l_8_9);
		E_Location.THIS.register(T_Location.getIndex(l_8_10), l_8_10);
		E_Location.THIS.register(T_Location.getIndex(l_8_11), l_8_11);
		E_Location.THIS.register(T_Location.getIndex(l_8_12), l_8_12);
		E_Location.THIS.register(T_Location.getIndex(l_8_13), l_8_13);
		E_Location.THIS.register(T_Location.getIndex(l_8_14), l_8_14);
		E_Location.THIS.register(T_Location.getIndex(l_8_15), l_8_15);
		E_Location.THIS.register(T_Location.getIndex(l_8_16), l_8_16);
		E_Location.THIS.register(T_Location.getIndex(l_8_17), l_8_17);
		E_Location.THIS.register(T_Location.getIndex(l_8_18), l_8_18);
		E_Location.THIS.register(T_Location.getIndex(l_8_19), l_8_19);
		E_Location.THIS.register(T_Location.getIndex(l_8_20), l_8_20);
		E_Location.THIS.register(T_Location.getIndex(l_9_1), l_9_1);
		E_Location.THIS.register(T_Location.getIndex(l_9_2), l_9_2);
		E_Location.THIS.register(T_Location.getIndex(l_9_3), l_9_3);
		E_Location.THIS.register(T_Location.getIndex(l_9_4), l_9_4);
		E_Location.THIS.register(T_Location.getIndex(l_9_5), l_9_5);
		E_Location.THIS.register(T_Location.getIndex(l_9_6), l_9_6);
		E_Location.THIS.register(T_Location.getIndex(l_9_7), l_9_7);
		E_Location.THIS.register(T_Location.getIndex(l_9_8), l_9_8);
		E_Location.THIS.register(T_Location.getIndex(l_9_9), l_9_9);
		E_Location.THIS.register(T_Location.getIndex(l_9_10), l_9_10);
		E_Location.THIS.register(T_Location.getIndex(l_9_11), l_9_11);
		E_Location.THIS.register(T_Location.getIndex(l_9_12), l_9_12);
		E_Location.THIS.register(T_Location.getIndex(l_9_13), l_9_13);
		E_Location.THIS.register(T_Location.getIndex(l_9_14), l_9_14);
		E_Location.THIS.register(T_Location.getIndex(l_9_15), l_9_15);
		E_Location.THIS.register(T_Location.getIndex(l_9_16), l_9_16);
		E_Location.THIS.register(T_Location.getIndex(l_9_17), l_9_17);
		E_Location.THIS.register(T_Location.getIndex(l_9_18), l_9_18);
		E_Location.THIS.register(T_Location.getIndex(l_9_19), l_9_19);
		E_Location.THIS.register(T_Location.getIndex(l_9_20), l_9_20);
		E_Location.THIS.register(T_Location.getIndex(l_10_1), l_10_1);
		E_Location.THIS.register(T_Location.getIndex(l_10_2), l_10_2);
		E_Location.THIS.register(T_Location.getIndex(l_10_3), l_10_3);
		E_Location.THIS.register(T_Location.getIndex(l_10_4), l_10_4);
		E_Location.THIS.register(T_Location.getIndex(l_10_5), l_10_5);
		E_Location.THIS.register(T_Location.getIndex(l_10_6), l_10_6);
		E_Location.THIS.register(T_Location.getIndex(l_10_7), l_10_7);
		E_Location.THIS.register(T_Location.getIndex(l_10_8), l_10_8);
		E_Location.THIS.register(T_Location.getIndex(l_10_9), l_10_9);
		E_Location.THIS.register(T_Location.getIndex(l_10_10), l_10_10);
		E_Location.THIS.register(T_Location.getIndex(l_10_11), l_10_11);
		E_Location.THIS.register(T_Location.getIndex(l_10_12), l_10_12);
		E_Location.THIS.register(T_Location.getIndex(l_10_13), l_10_13);
		E_Location.THIS.register(T_Location.getIndex(l_10_14), l_10_14);
		E_Location.THIS.register(T_Location.getIndex(l_10_15), l_10_15);
		E_Location.THIS.register(T_Location.getIndex(l_10_16), l_10_16);
		E_Location.THIS.register(T_Location.getIndex(l_10_17), l_10_17);
		E_Location.THIS.register(T_Location.getIndex(l_10_18), l_10_18);
		E_Location.THIS.register(T_Location.getIndex(l_10_19), l_10_19);
		E_Location.THIS.register(T_Location.getIndex(l_10_20), l_10_20);
		E_Location.THIS.register(T_Location.getIndex(l_11_1), l_11_1);
		E_Location.THIS.register(T_Location.getIndex(l_11_2), l_11_2);
		E_Location.THIS.register(T_Location.getIndex(l_11_3), l_11_3);
		E_Location.THIS.register(T_Location.getIndex(l_11_4), l_11_4);
		E_Location.THIS.register(T_Location.getIndex(l_11_5), l_11_5);
		E_Location.THIS.register(T_Location.getIndex(l_11_6), l_11_6);
		E_Location.THIS.register(T_Location.getIndex(l_11_7), l_11_7);
		E_Location.THIS.register(T_Location.getIndex(l_11_8), l_11_8);
		E_Location.THIS.register(T_Location.getIndex(l_11_9), l_11_9);
		E_Location.THIS.register(T_Location.getIndex(l_11_10), l_11_10);
		E_Location.THIS.register(T_Location.getIndex(l_11_11), l_11_11);
		E_Location.THIS.register(T_Location.getIndex(l_11_12), l_11_12);
		E_Location.THIS.register(T_Location.getIndex(l_11_13), l_11_13);
		E_Location.THIS.register(T_Location.getIndex(l_11_14), l_11_14);
		E_Location.THIS.register(T_Location.getIndex(l_11_15), l_11_15);
		E_Location.THIS.register(T_Location.getIndex(l_11_16), l_11_16);
		E_Location.THIS.register(T_Location.getIndex(l_11_17), l_11_17);
		E_Location.THIS.register(T_Location.getIndex(l_11_18), l_11_18);
		E_Location.THIS.register(T_Location.getIndex(l_11_19), l_11_19);
		E_Location.THIS.register(T_Location.getIndex(l_11_20), l_11_20);
		E_Location.THIS.register(T_Location.getIndex(l_12_1), l_12_1);
		E_Location.THIS.register(T_Location.getIndex(l_12_2), l_12_2);
		E_Location.THIS.register(T_Location.getIndex(l_12_3), l_12_3);
		E_Location.THIS.register(T_Location.getIndex(l_12_4), l_12_4);
		E_Location.THIS.register(T_Location.getIndex(l_12_5), l_12_5);
		E_Location.THIS.register(T_Location.getIndex(l_12_6), l_12_6);
		E_Location.THIS.register(T_Location.getIndex(l_12_7), l_12_7);
		E_Location.THIS.register(T_Location.getIndex(l_12_8), l_12_8);
		E_Location.THIS.register(T_Location.getIndex(l_12_9), l_12_9);
		E_Location.THIS.register(T_Location.getIndex(l_12_10), l_12_10);
		E_Location.THIS.register(T_Location.getIndex(l_12_11), l_12_11);
		E_Location.THIS.register(T_Location.getIndex(l_12_12), l_12_12);
		E_Location.THIS.register(T_Location.getIndex(l_12_13), l_12_13);
		E_Location.THIS.register(T_Location.getIndex(l_12_14), l_12_14);
		E_Location.THIS.register(T_Location.getIndex(l_12_15), l_12_15);
		E_Location.THIS.register(T_Location.getIndex(l_12_16), l_12_16);
		E_Location.THIS.register(T_Location.getIndex(l_12_17), l_12_17);
		E_Location.THIS.register(T_Location.getIndex(l_12_18), l_12_18);
		E_Location.THIS.register(T_Location.getIndex(l_12_19), l_12_19);
		E_Location.THIS.register(T_Location.getIndex(l_12_20), l_12_20);
		E_Location.THIS.register(T_Location.getIndex(l_13_1), l_13_1);
		E_Location.THIS.register(T_Location.getIndex(l_13_2), l_13_2);
		E_Location.THIS.register(T_Location.getIndex(l_13_3), l_13_3);
		E_Location.THIS.register(T_Location.getIndex(l_13_4), l_13_4);
		E_Location.THIS.register(T_Location.getIndex(l_13_5), l_13_5);
		E_Location.THIS.register(T_Location.getIndex(l_13_6), l_13_6);
		E_Location.THIS.register(T_Location.getIndex(l_13_7), l_13_7);
		E_Location.THIS.register(T_Location.getIndex(l_13_8), l_13_8);
		E_Location.THIS.register(T_Location.getIndex(l_13_9), l_13_9);
		E_Location.THIS.register(T_Location.getIndex(l_13_10), l_13_10);
		E_Location.THIS.register(T_Location.getIndex(l_13_11), l_13_11);
		E_Location.THIS.register(T_Location.getIndex(l_13_12), l_13_12);
		E_Location.THIS.register(T_Location.getIndex(l_13_13), l_13_13);
		E_Location.THIS.register(T_Location.getIndex(l_13_14), l_13_14);
		E_Location.THIS.register(T_Location.getIndex(l_13_15), l_13_15);
		E_Location.THIS.register(T_Location.getIndex(l_13_16), l_13_16);
		E_Location.THIS.register(T_Location.getIndex(l_13_17), l_13_17);
		E_Location.THIS.register(T_Location.getIndex(l_13_18), l_13_18);
		E_Location.THIS.register(T_Location.getIndex(l_13_19), l_13_19);
		E_Location.THIS.register(T_Location.getIndex(l_13_20), l_13_20);
		E_Location.THIS.register(T_Location.getIndex(l_14_1), l_14_1);
		E_Location.THIS.register(T_Location.getIndex(l_14_2), l_14_2);
		E_Location.THIS.register(T_Location.getIndex(l_14_3), l_14_3);
		E_Location.THIS.register(T_Location.getIndex(l_14_4), l_14_4);
		E_Location.THIS.register(T_Location.getIndex(l_14_5), l_14_5);
		E_Location.THIS.register(T_Location.getIndex(l_14_6), l_14_6);
		E_Location.THIS.register(T_Location.getIndex(l_14_7), l_14_7);
		E_Location.THIS.register(T_Location.getIndex(l_14_8), l_14_8);
		E_Location.THIS.register(T_Location.getIndex(l_14_9), l_14_9);
		E_Location.THIS.register(T_Location.getIndex(l_14_10), l_14_10);
		E_Location.THIS.register(T_Location.getIndex(l_14_11), l_14_11);
		E_Location.THIS.register(T_Location.getIndex(l_14_12), l_14_12);
		E_Location.THIS.register(T_Location.getIndex(l_14_13), l_14_13);
		E_Location.THIS.register(T_Location.getIndex(l_14_14), l_14_14);
		E_Location.THIS.register(T_Location.getIndex(l_14_15), l_14_15);
		E_Location.THIS.register(T_Location.getIndex(l_14_16), l_14_16);
		E_Location.THIS.register(T_Location.getIndex(l_14_17), l_14_17);
		E_Location.THIS.register(T_Location.getIndex(l_14_18), l_14_18);
		E_Location.THIS.register(T_Location.getIndex(l_14_19), l_14_19);
		E_Location.THIS.register(T_Location.getIndex(l_14_20), l_14_20);
		E_Location.THIS.register(T_Location.getIndex(l_15_1), l_15_1);
		E_Location.THIS.register(T_Location.getIndex(l_15_2), l_15_2);
		E_Location.THIS.register(T_Location.getIndex(l_15_3), l_15_3);
		E_Location.THIS.register(T_Location.getIndex(l_15_4), l_15_4);
		E_Location.THIS.register(T_Location.getIndex(l_15_5), l_15_5);
		E_Location.THIS.register(T_Location.getIndex(l_15_6), l_15_6);
		E_Location.THIS.register(T_Location.getIndex(l_15_7), l_15_7);
		E_Location.THIS.register(T_Location.getIndex(l_15_8), l_15_8);
		E_Location.THIS.register(T_Location.getIndex(l_15_9), l_15_9);
		E_Location.THIS.register(T_Location.getIndex(l_15_10), l_15_10);
		E_Location.THIS.register(T_Location.getIndex(l_15_11), l_15_11);
		E_Location.THIS.register(T_Location.getIndex(l_15_12), l_15_12);
		E_Location.THIS.register(T_Location.getIndex(l_15_13), l_15_13);
		E_Location.THIS.register(T_Location.getIndex(l_15_14), l_15_14);
		E_Location.THIS.register(T_Location.getIndex(l_15_15), l_15_15);
		E_Location.THIS.register(T_Location.getIndex(l_15_16), l_15_16);
		E_Location.THIS.register(T_Location.getIndex(l_15_17), l_15_17);
		E_Location.THIS.register(T_Location.getIndex(l_15_18), l_15_18);
		E_Location.THIS.register(T_Location.getIndex(l_15_19), l_15_19);
		E_Location.THIS.register(T_Location.getIndex(l_15_20), l_15_20);
		E_Location.THIS.register(T_Location.getIndex(l_16_1), l_16_1);
		E_Location.THIS.register(T_Location.getIndex(l_16_2), l_16_2);
		E_Location.THIS.register(T_Location.getIndex(l_16_3), l_16_3);
		E_Location.THIS.register(T_Location.getIndex(l_16_4), l_16_4);
		E_Location.THIS.register(T_Location.getIndex(l_16_5), l_16_5);
		E_Location.THIS.register(T_Location.getIndex(l_16_6), l_16_6);
		E_Location.THIS.register(T_Location.getIndex(l_16_7), l_16_7);
		E_Location.THIS.register(T_Location.getIndex(l_16_8), l_16_8);
		E_Location.THIS.register(T_Location.getIndex(l_16_9), l_16_9);
		E_Location.THIS.register(T_Location.getIndex(l_16_10), l_16_10);
		E_Location.THIS.register(T_Location.getIndex(l_16_11), l_16_11);
		E_Location.THIS.register(T_Location.getIndex(l_16_12), l_16_12);
		E_Location.THIS.register(T_Location.getIndex(l_16_13), l_16_13);
		E_Location.THIS.register(T_Location.getIndex(l_16_14), l_16_14);
		E_Location.THIS.register(T_Location.getIndex(l_16_15), l_16_15);
		E_Location.THIS.register(T_Location.getIndex(l_16_16), l_16_16);
		E_Location.THIS.register(T_Location.getIndex(l_16_17), l_16_17);
		E_Location.THIS.register(T_Location.getIndex(l_16_18), l_16_18);
		E_Location.THIS.register(T_Location.getIndex(l_16_19), l_16_19);
		E_Location.THIS.register(T_Location.getIndex(l_16_20), l_16_20);
		E_Location.THIS.register(T_Location.getIndex(l_17_1), l_17_1);
		E_Location.THIS.register(T_Location.getIndex(l_17_2), l_17_2);
		E_Location.THIS.register(T_Location.getIndex(l_17_3), l_17_3);
		E_Location.THIS.register(T_Location.getIndex(l_17_4), l_17_4);
		E_Location.THIS.register(T_Location.getIndex(l_17_5), l_17_5);
		E_Location.THIS.register(T_Location.getIndex(l_17_6), l_17_6);
		E_Location.THIS.register(T_Location.getIndex(l_17_7), l_17_7);
		E_Location.THIS.register(T_Location.getIndex(l_17_8), l_17_8);
		E_Location.THIS.register(T_Location.getIndex(l_17_9), l_17_9);
		E_Location.THIS.register(T_Location.getIndex(l_17_10), l_17_10);
		E_Location.THIS.register(T_Location.getIndex(l_17_11), l_17_11);
		E_Location.THIS.register(T_Location.getIndex(l_17_12), l_17_12);
		E_Location.THIS.register(T_Location.getIndex(l_17_13), l_17_13);
		E_Location.THIS.register(T_Location.getIndex(l_17_14), l_17_14);
		E_Location.THIS.register(T_Location.getIndex(l_17_15), l_17_15);
		E_Location.THIS.register(T_Location.getIndex(l_17_16), l_17_16);
		E_Location.THIS.register(T_Location.getIndex(l_17_17), l_17_17);
		E_Location.THIS.register(T_Location.getIndex(l_17_18), l_17_18);
		E_Location.THIS.register(T_Location.getIndex(l_17_19), l_17_19);
		E_Location.THIS.register(T_Location.getIndex(l_17_20), l_17_20);
		E_Location.THIS.register(T_Location.getIndex(l_18_1), l_18_1);
		E_Location.THIS.register(T_Location.getIndex(l_18_2), l_18_2);
		E_Location.THIS.register(T_Location.getIndex(l_18_3), l_18_3);
		E_Location.THIS.register(T_Location.getIndex(l_18_4), l_18_4);
		E_Location.THIS.register(T_Location.getIndex(l_18_5), l_18_5);
		E_Location.THIS.register(T_Location.getIndex(l_18_6), l_18_6);
		E_Location.THIS.register(T_Location.getIndex(l_18_7), l_18_7);
		E_Location.THIS.register(T_Location.getIndex(l_18_8), l_18_8);
		E_Location.THIS.register(T_Location.getIndex(l_18_9), l_18_9);
		E_Location.THIS.register(T_Location.getIndex(l_18_10), l_18_10);
		E_Location.THIS.register(T_Location.getIndex(l_18_11), l_18_11);
		E_Location.THIS.register(T_Location.getIndex(l_18_12), l_18_12);
		E_Location.THIS.register(T_Location.getIndex(l_18_13), l_18_13);
		E_Location.THIS.register(T_Location.getIndex(l_18_14), l_18_14);
		E_Location.THIS.register(T_Location.getIndex(l_18_15), l_18_15);
		E_Location.THIS.register(T_Location.getIndex(l_18_16), l_18_16);
		E_Location.THIS.register(T_Location.getIndex(l_18_17), l_18_17);
		E_Location.THIS.register(T_Location.getIndex(l_18_18), l_18_18);
		E_Location.THIS.register(T_Location.getIndex(l_18_19), l_18_19);
		E_Location.THIS.register(T_Location.getIndex(l_18_20), l_18_20);
		E_Location.THIS.register(T_Location.getIndex(l_19_1), l_19_1);
		E_Location.THIS.register(T_Location.getIndex(l_19_2), l_19_2);
		E_Location.THIS.register(T_Location.getIndex(l_19_3), l_19_3);
		E_Location.THIS.register(T_Location.getIndex(l_19_4), l_19_4);
		E_Location.THIS.register(T_Location.getIndex(l_19_5), l_19_5);
		E_Location.THIS.register(T_Location.getIndex(l_19_6), l_19_6);
		E_Location.THIS.register(T_Location.getIndex(l_19_7), l_19_7);
		E_Location.THIS.register(T_Location.getIndex(l_19_8), l_19_8);
		E_Location.THIS.register(T_Location.getIndex(l_19_9), l_19_9);
		E_Location.THIS.register(T_Location.getIndex(l_19_10), l_19_10);
		E_Location.THIS.register(T_Location.getIndex(l_19_11), l_19_11);
		E_Location.THIS.register(T_Location.getIndex(l_19_12), l_19_12);
		E_Location.THIS.register(T_Location.getIndex(l_19_13), l_19_13);
		E_Location.THIS.register(T_Location.getIndex(l_19_14), l_19_14);
		E_Location.THIS.register(T_Location.getIndex(l_19_15), l_19_15);
		E_Location.THIS.register(T_Location.getIndex(l_19_16), l_19_16);
		E_Location.THIS.register(T_Location.getIndex(l_19_17), l_19_17);
		E_Location.THIS.register(T_Location.getIndex(l_19_18), l_19_18);
		E_Location.THIS.register(T_Location.getIndex(l_19_19), l_19_19);
		E_Location.THIS.register(T_Location.getIndex(l_19_20), l_19_20);
		E_Location.THIS.register(T_Location.getIndex(l_20_1), l_20_1);
		E_Location.THIS.register(T_Location.getIndex(l_20_2), l_20_2);
		E_Location.THIS.register(T_Location.getIndex(l_20_3), l_20_3);
		E_Location.THIS.register(T_Location.getIndex(l_20_4), l_20_4);
		E_Location.THIS.register(T_Location.getIndex(l_20_5), l_20_5);
		E_Location.THIS.register(T_Location.getIndex(l_20_6), l_20_6);
		E_Location.THIS.register(T_Location.getIndex(l_20_7), l_20_7);
		E_Location.THIS.register(T_Location.getIndex(l_20_8), l_20_8);
		E_Location.THIS.register(T_Location.getIndex(l_20_9), l_20_9);
		E_Location.THIS.register(T_Location.getIndex(l_20_10), l_20_10);
		E_Location.THIS.register(T_Location.getIndex(l_20_11), l_20_11);
		E_Location.THIS.register(T_Location.getIndex(l_20_12), l_20_12);
		E_Location.THIS.register(T_Location.getIndex(l_20_13), l_20_13);
		E_Location.THIS.register(T_Location.getIndex(l_20_14), l_20_14);
		E_Location.THIS.register(T_Location.getIndex(l_20_15), l_20_15);
		E_Location.THIS.register(T_Location.getIndex(l_20_16), l_20_16);
		E_Location.THIS.register(T_Location.getIndex(l_20_17), l_20_17);
		E_Location.THIS.register(T_Location.getIndex(l_20_18), l_20_18);
		E_Location.THIS.register(T_Location.getIndex(l_20_19), l_20_19);
		E_Location.THIS.register(T_Location.getIndex(l_20_20), l_20_20);
		
	}
		
	protected E_Locations() {
	}

}